<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="VDST_CPM.xsd"/>
      <rootElement name="CPM-Load" namespace="http://schema.emerson.com/VDST_FTP_GET_ChannelPartner_PartMap"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="VDSTDBINSChannelPartnerPartMap_table.xsd"/>
      <rootElement name="VdstChnlpartnerPartNumberCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/VDSTDBINSChannelPartnerPartMap"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [THU JUL 02 17:11:42 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://schema.emerson.com/VDST_FTP_GET_ChannelPartner_PartMap"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/VDSTDBINSChannelPartnerPartMap"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:emr="http://www.oracle.com/XSL/Transform/java/com.emerson.date.formatter.ConvertFormat"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl xsd tns nxsd ns0 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns0:VdstChnlpartnerPartNumberCollection>
      <xsl:for-each select="/tns:CPM-Load/tns:cpm">
        <ns0:VdstChnlpartnerPartNumber>
          <ns0:partNumber>
            <xsl:value-of select="tns:PART_NUMBER"/>
          </ns0:partNumber>
          <ns0:channelPartnerId>
            <xsl:value-of select="tns:CHANNEL_PARTNER_ID"/>
          </ns0:channelPartnerId>
          <ns0:channelPartnerPartNumber>
            <xsl:value-of select="tns:CHANNEL_PARTNER_PART_NUMBER"/>
          </ns0:channelPartnerPartNumber>
          <ns0:generatedTimestamp>
            <!--<xsl:value-of select="tns:GENERATED_TIMESTAMP"/>-->
            <xsl:value-of select='emr:toISODate(tns:GENERATED_TIMESTAMP,"MM/dd/yyyy HH:mm")'/>
          </ns0:generatedTimestamp>
        </ns0:VdstChnlpartnerPartNumber>
      </xsl:for-each>
    </ns0:VdstChnlpartnerPartNumberCollection>
  </xsl:template>
</xsl:stylesheet>
