<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="PollItemNumberDB_table.xsd"/>
      <rootElement name="ItemNumberOutboundCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollItemNumberDB"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="DBUpdITEMNUMOUTBOUND_table.xsd"/>
      <rootElement name="ItemNumberOutboundCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBUpdITEMNUMOUTBOUND"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE OCT 06 11:00:48 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollItemNumberDB"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBUpdITEMNUMOUTBOUND"
                exclude-result-prefixes="xsl ns0 xs ns1 xref xp20 bpws ora ehdr orcl ids hwf">
  <xsl:template match="/">
    <ns1:ItemNumberOutboundCollection>
      <xsl:for-each select="/ns0:ItemNumberOutboundCollection/ns0:ItemNumberOutbound">
        <ns1:ItemNumberOutbound>
          <ns1:itemNbr>
            <xsl:value-of select="ns0:itemNbr"/>
          </ns1:itemNbr>
          <ns1:itemDescription>
            <xsl:value-of select="ns0:itemDescription"/>
          </ns1:itemDescription>
          <ns1:centerOfExpertiseId>
            <xsl:value-of select="ns0:centerOfExpertiseId"/>
          </ns1:centerOfExpertiseId>
          <ns1:productSegmentId>
            <xsl:value-of select="ns0:productSegmentId"/>
          </ns1:productSegmentId>
          <ns1:productlineCode>
            <xsl:value-of select="ns0:productlineCode"/>
          </ns1:productlineCode>
          <ns1:modellineCode>
            <xsl:value-of select="ns0:modellineCode"/>
          </ns1:modellineCode>
          <ns1:submodellineCode>
            <xsl:value-of select="ns0:submodellineCode"/>
          </ns1:submodellineCode>
          <ns1:issueUomName>
            <xsl:value-of select="ns0:issueUomName"/>
          </ns1:issueUomName>
          <ns1:itemStatus>
            <xsl:value-of select="ns0:itemStatus"/>
          </ns1:itemStatus>
          <ns1:targetState>
            <xsl:value-of select="ns0:targetState"/>
          </ns1:targetState>
          <ns1:localFlag>
            <xsl:value-of select="ns0:localFlag"/>
          </ns1:localFlag>
          <ns1:serviceFlag>
            <xsl:value-of select="ns0:serviceFlag"/>
          </ns1:serviceFlag>
          <ns1:processFlag>
            <xsl:value-of select="ns0:processFlag"/>
          </ns1:processFlag>
        </ns1:ItemNumberOutbound>
      </xsl:for-each>
    </ns1:ItemNumberOutboundCollection>
  </xsl:template>
</xsl:stylesheet>
