<definitions
     name="MDMSearchRecord"
     targetNamespace="http://www.gssamerica.com/mdm/services/MDMSearchRecord/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.gssamerica.com/mdm/services/MDMSearchRecord/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <import namespace="http://www.gssamerica.com/mdm/services/MDMSearchRecord/" location="http://GDC-18:8888/MDM_Services/MDMSearchRecordSOAP?wsdl"/>
    <plnk:partnerLinkType name="MDMSearchRecord_PL">
        <plnk:role name="MDMSearchRecord_Role">
            <plnk:portType name="tns:MDMSearchRecord"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
