<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../FileIn.wsdl"/>
      <rootElement name="CustomerData" namespace="http://xmlns.oracle.com/Esb/CustomerData"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../FileOut.wsdl"/>
      <rootElement name="Customer" namespace="http://xmlns.oracle.com/Esb/CustomerData"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.2.0(build 090825.1400.3156) AT [FRI AUG 28 12:11:27 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/App_Mediator_basic/Callout/FileOut/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:imp1="http://xmlns.oracle.com/Esb/CustomerData"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/App_Mediator_basic/Callout/FileIn/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl imp1 plt xsd tns wsdl ns0 xpath20 bpws mhdr oraext dvm hwf med ids xdk xref ora socket ldap">
  <xsl:template match="/">
    <imp1:Customer>
      <CustomerId>
        <xsl:value-of select="/imp1:CustomerData/CustomerId"/>
      </CustomerId>
      <CustomerName>
        <xsl:value-of select="/imp1:CustomerData/CustomerName"/>
      </CustomerName>
      <Address>
        <xsl:value-of select="/imp1:CustomerData/Address"/>
      </Address>
      <City>
        <xsl:value-of select="/imp1:CustomerData/City"/>
      </City>
      <State>
        <xsl:value-of select="/imp1:CustomerData/State"/>
      </State>
      <Zip>
        <xsl:value-of select="/imp1:CustomerData/Zip"/>
      </Zip>
      <Country>
        <xsl:value-of select="/imp1:CustomerData/Country"/>
      </Country>
      <Phone>
        <xsl:value-of select="/imp1:CustomerData/Phone"/>
      </Phone>
      <ContactName>
        <xsl:value-of select="/imp1:CustomerData/ContactName"/>
      </ContactName>
      <ContactPhone>
        <xsl:value-of select="/imp1:CustomerData/ContactPhone"/>
      </ContactPhone>
    </imp1:Customer>
  </xsl:template>
</xsl:stylesheet>
