<definitions
     name="ClosetMaid"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ClosetMaid/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ClosetMaid/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterInboundHeader.wsdl"/>
    <types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </types>
    <message name="Get_msg">
        <part name="opaque" element="opaque:opaqueElement"/>
    </message>
    <portType name="Get_ptt">
        <operation name="Get">
            <input message="tns:Get_msg"/>
        </operation>
    </portType>
    <binding name="Get_binding" type="tns:Get_ptt">
    <pc:inbound_binding  />
        <operation name="Get">
      <jca:operation
          FileType="binary"
          LogicalDirectory="IN_DIR"
          ActivationSpec="oracle.tip.adapter.ftp.inbound.FTPActivationSpec"
          LogicalArchiveDirectory="archiveDIR"
          DeleteFile="false"
          IncludeFiles="test_.*\..*"
          PollingFrequency="40"
          MinimumAge="0"
          FileNameSubstringBegin="5"
          FileNameSubstringEnd="17"
          FileModificationTime="Filename"
          ModificationTimeFormat="yyyyMMddHHmm"
          OpaqueSchema="true"
          UseHeaders="true"><!-- UseHeaders="true"  -->
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="ClosetMaid">
        <port name="Get_pt" binding="tns:Get_binding">
      <jca:address location="eis/FTP/ClosetMaidTest" UIincludeWildcard="test_*.*" />
        </port>
    </service>
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
