// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.emerson.services.types.com.emerson.schemas.customer;


public class CustomerType implements java.io.Serializable {
    protected com.emerson.services.types.com.emerson.schemas.customer.NameType name;
    protected java.math.BigInteger age;
    protected java.lang.String company;
    
    public CustomerType() {
    }
    
    public com.emerson.services.types.com.emerson.schemas.customer.NameType getName() {
        return name;
    }
    
    public void setName(com.emerson.services.types.com.emerson.schemas.customer.NameType name) {
        this.name = name;
    }
    
    public java.math.BigInteger getAge() {
        return age;
    }
    
    public void setAge(java.math.BigInteger age) {
        this.age = age;
    }
    
    public java.lang.String getCompany() {
        return company;
    }
    
    public void setCompany(java.lang.String company) {
        this.company = company;
    }
}
