<definitions
     name="VDST_FTP_GET_CADFile"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/VDST_FTP_GET_CADFile/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/VDST_FTP_GET_CADFile/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterInboundHeader.wsdl"/>
    <types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </types>
    <message name="Get_msg">
        <part name="opaque" element="opaque:opaqueElement"/>
    </message>
    <portType name="Get_ptt">
        <operation name="Get">
            <input message="tns:Get_msg"/>
        </operation>
    </portType>
    <binding name="Get_binding" type="tns:Get_ptt">
    <pc:inbound_binding  />
        <operation name="Get">
      <jca:operation
          FileType="ascii"
          PhysicalDirectory="$input_dir"
          ActivationSpec="oracle.tip.adapter.ftp.inbound.FTPActivationSpec"
          PhysicalArchiveDirectory="$archive_dir"
          DeleteFile="false"
          IncludeFiles=".*"
          ExcludeFiles="dummy.*\.txt"
          PollingFrequency="60"
          MinimumAge="120"
          FileModificationTime="FileSystem"
          ModificationTimeFormat="4,18,yyyyMMddHHmmss"
          OpaqueSchema="true"
          UseHeaders="true"
          UseRemoteArchive="true" >
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="VDST_FTP_GET_CADFile">
        <port name="Get_pt" binding="tns:Get_binding">
      <jca:address location="$FTP_JNDI" UIincludeWildcard="*" UIexcludeWildcard="dummy*.txt" />
        </port>
    </service>
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
