<definitions
     name="Test1PollAQ"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/Test1PollAQ/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/Test1PollAQ/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:obj1="http://xmlns.oracle.com/xdb/AQ"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/aq/inbound/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/aq/inbound/" location="aqAdapterInboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/xdb/AQ" schemaLocation="AQ_MESSAGE_TYP.xsd" />
      </schema>
    </types>
    <message name="MESSAGE_TYP_msg">
        <part name="MESSAGE_TYP" element="obj1:MESSAGE_TYP"/>
    </message>
    <portType name="Dequeue_ptt">
        <operation name="Dequeue">
            <input message="tns:MESSAGE_TYP_msg"/>
        </operation>
    </portType>
    <binding name="Dequeue_binding" type="tns:Dequeue_ptt">
    <pc:inbound_binding  />
        <operation name="Dequeue">
      <jca:operation
          ActivationSpec="oracle.tip.adapter.aq.inbound.AQDequeueActivationSpec"
          QueueName="TEST1_QUEUE"
          DatabaseSchema="AQ"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:Header" part="Header"/>
      </input>
        </operation>
    </binding>
    <service name="Test1PollAQ">
        <port name="Dequeue_pt" binding="tns:Dequeue_binding">
<!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/AqAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/AQ/OracleXE is missing. 
These mcf properties are safe to remove.-->
      <jca:address location="eis/AQ/OracleXE" UIConnectionName="OracleXE"
          ManagedConnectionFactory="oracle.tip.adapter.aq.AQManagedConnectionFactory"
          mcf.ConnectionString="jdbc:oracle:thin:@//localhost:1521/xe"
          mcf.UserName="system"
          mcf.Password="47E570316F19A1CFFD2E2104BF5CA8FE" />
        </port>
    </service>
  <plt:partnerLinkType name="Dequeue_plt" >
    <plt:role name="Dequeue_role" >
      <plt:portType name="tns:Dequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
