<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ETH_BPEL_Sarah_ConnectorService"
     targetNamespace="http://xmlns.oracle.com/Dhami_SOA/ETH_Sarah_ConnectorService/ETH_BPEL_Sarah_ConnectorService"
     xmlns:ns1="http://schema.emerson.com/ETH/Header"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:client="http://xmlns.oracle.com/Dhami_SOA/ETH_Sarah_ConnectorService/ETH_BPEL_Sarah_ConnectorService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ETH_BPEL_Sarah_ConnectorService">
        <plnk:role name="ETH_BPEL_Sarah_ConnectorServiceProvider" portType="client:ETH_BPEL_Sarah_ConnectorService"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/Dhami_SOA/ETH_Sarah_ConnectorService/ETH_BPEL_Sarah_ConnectorService"
                 schemaLocation="xsd/ETH_BPEL_Sarah_ConnectorService.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schema.emerson.com/ETH/Header" schemaLocation="oramds:/apps/ETH3/XMLGatewayInputServices/ETH_SARAH_ReqstABC_Router/xsd/ETH_Header.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ETH_BPEL_Sarah_ConnectorServiceRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ETH_BPEL_Sarah_ConnectorServiceResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ETH_BPEL_Sarah_ConnectorService">
        <wsdl:operation name="process">
            <wsdl:input message="client:ETH_BPEL_Sarah_ConnectorServiceRequestMessage"/>
            <wsdl:output message="client:ETH_BPEL_Sarah_ConnectorServiceResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
