<?binding.jca sadfasdas_file.jca?>
<wsdl:definitions name="sadfasdas" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Dhami-SOA/Sarah_RequestService/sadfasdas" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Dhami-SOA/Sarah_RequestService/sadfasdas" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://TargetNamespace.com/dsfgxcv" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="Read_plt">
        <plt:role name="Read_role">
            <plt:portType name="tns:Read_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://TargetNamespace.com/dsfgxcv" schemaLocation="xsd/PROCESS_PO_007.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="Read_msg">
        <wsdl:part name="body" element="imp1:PROCESS_PO_007"/>
    </wsdl:message>
    <wsdl:portType name="Read_ptt">
        <wsdl:operation name="Read">
            <wsdl:input message="tns:Read_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
