// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.gssamerica.mdm.services;


public class DataElementCriteriaType implements java.io.Serializable {
    protected java.lang.String fieldCode;
    protected java.lang.String taxonomyFieldCode;
    protected java.lang.String dataType;
    protected java.lang.String logicOperator;
    protected com.gssamerica.mdm.services.SimpleValueCriteriaType simpleValueCriteria;
    protected com.gssamerica.mdm.services.LookupValueCriteria lookupValueCriteria;
    
    public DataElementCriteriaType() {
    }
    
    public java.lang.String getFieldCode() {
        return fieldCode;
    }
    
    public void setFieldCode(java.lang.String fieldCode) {
        this.fieldCode = fieldCode;
    }
    
    public java.lang.String getTaxonomyFieldCode() {
        return taxonomyFieldCode;
    }
    
    public void setTaxonomyFieldCode(java.lang.String taxonomyFieldCode) {
        this.taxonomyFieldCode = taxonomyFieldCode;
    }
    
    public java.lang.String getDataType() {
        return dataType;
    }
    
    public void setDataType(java.lang.String dataType) {
        this.dataType = dataType;
    }
    
    public java.lang.String getLogicOperator() {
        return logicOperator;
    }
    
    public void setLogicOperator(java.lang.String logicOperator) {
        this.logicOperator = logicOperator;
    }
    
    public com.gssamerica.mdm.services.SimpleValueCriteriaType getSimpleValueCriteria() {
        return simpleValueCriteria;
    }
    
    public void setSimpleValueCriteria(com.gssamerica.mdm.services.SimpleValueCriteriaType simpleValueCriteria) {
        this.simpleValueCriteria = simpleValueCriteria;
    }
    
    public com.gssamerica.mdm.services.LookupValueCriteria getLookupValueCriteria() {
        return lookupValueCriteria;
    }
    
    public void setLookupValueCriteria(com.gssamerica.mdm.services.LookupValueCriteria lookupValueCriteria) {
        this.lookupValueCriteria = lookupValueCriteria;
    }
}
