// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.gssamerica.mdm.services;


public class FieldDefinitionType implements java.io.Serializable {
    protected boolean loadAttributes;
    protected java.math.BigInteger lookupLevel;
    protected java.lang.String fieldCode;
    
    public FieldDefinitionType() {
    }
    
    public boolean isLoadAttributes() {
        return loadAttributes;
    }
    
    public void setLoadAttributes(boolean loadAttributes) {
        this.loadAttributes = loadAttributes;
    }
    
    public java.math.BigInteger getLookupLevel() {
        return lookupLevel;
    }
    
    public void setLookupLevel(java.math.BigInteger lookupLevel) {
        this.lookupLevel = lookupLevel;
    }
    
    public java.lang.String getFieldCode() {
        return fieldCode;
    }
    
    public void setFieldCode(java.lang.String fieldCode) {
        this.fieldCode = fieldCode;
    }
}
