// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.gssamerica.mdm.services;


public class KeyType implements java.io.Serializable {
    protected java.lang.String isDefault;
    protected java.lang.String value;
    
    public KeyType() {
    }
    
    public java.lang.String getIsDefault() {
        return isDefault;
    }
    
    public void setIsDefault(java.lang.String isDefault) {
        this.isDefault = isDefault;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
