// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.gssamerica.mdm.services;


public class RecordIdentifierCriteriaType implements java.io.Serializable {
    protected java.math.BigInteger autoId;
    protected java.lang.String externalId;
    protected java.lang.String recordId;
    protected com.gssamerica.mdm.services.RemoteKeyType remoteKey;
    
    public RecordIdentifierCriteriaType() {
    }
    
    public java.math.BigInteger getAutoId() {
        return autoId;
    }
    
    public void setAutoId(java.math.BigInteger autoId) {
        this.autoId = autoId;
    }
    
    public java.lang.String getExternalId() {
        return externalId;
    }
    
    public void setExternalId(java.lang.String externalId) {
        this.externalId = externalId;
    }
    
    public java.lang.String getRecordId() {
        return recordId;
    }
    
    public void setRecordId(java.lang.String recordId) {
        this.recordId = recordId;
    }
    
    public com.gssamerica.mdm.services.RemoteKeyType getRemoteKey() {
        return remoteKey;
    }
    
    public void setRemoteKey(com.gssamerica.mdm.services.RemoteKeyType remoteKey) {
        this.remoteKey = remoteKey;
    }
}
