// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.emerson.service.vdst;


public class ImportOtherModelRequestType implements java.io.Serializable {
    protected java.lang.String sessionID;
    protected java.lang.String filename;
    protected java.lang.String productID;
    
    public ImportOtherModelRequestType() {
    }
    
    public java.lang.String getSessionID() {
        return sessionID;
    }
    
    public void setSessionID(java.lang.String sessionID) {
        this.sessionID = sessionID;
    }
    
    public java.lang.String getFilename() {
        return filename;
    }
    
    public void setFilename(java.lang.String filename) {
        this.filename = filename;
    }
    
    public java.lang.String getProductID() {
        return productID;
    }
    
    public void setProductID(java.lang.String productID) {
        this.productID = productID;
    }
}
