// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.emerson.service.vdst;


public class UpdateProductContentRequestType implements java.io.Serializable {
    protected java.lang.String sessionID;
    protected java.lang.String productID;
    protected byte[] content;
    protected com.emerson.service.vdst.ContentType contentType;
    
    public UpdateProductContentRequestType() {
    }
    
    public java.lang.String getSessionID() {
        return sessionID;
    }
    
    public void setSessionID(java.lang.String sessionID) {
        this.sessionID = sessionID;
    }
    
    public java.lang.String getProductID() {
        return productID;
    }
    
    public void setProductID(java.lang.String productID) {
        this.productID = productID;
    }
    
    public byte[] getContent() {
        return content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    
    public com.emerson.service.vdst.ContentType getContentType() {
        return contentType;
    }
    
    public void setContentType(com.emerson.service.vdst.ContentType contentType) {
        this.contentType = contentType;
    }
}
