<definitions
     name="ETH_DEQJMS_ALICE_ASN_OAGIS_7_2"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_DEQJMS_ALICE_ASN_OAGIS_7_2/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_DEQJMS_ALICE_ASN_OAGIS_7_2/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.emrsn.com/CustomShow_Shipment_005"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/jms/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/" location="jmsAdapterInboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.emrsn.com/CustomShow_Shipment_005" schemaLocation="public_html/Custom_show_shipment_005.xsd" />
      </schema>
    </types>
    <message name="CustomShow_Shipment_005_msg">
        <part name="CustomShow_Shipment_005" element="imp1:CustomShow_Shipment_005"/>
    </message>
    <portType name="Consume_Message_ptt">
        <operation name="Consume_Message">
            <input message="tns:CustomShow_Shipment_005_msg"/>
        </operation>
    </portType>
    <binding name="Consume_Message_binding" type="tns:Consume_Message_ptt">
    <pc:inbound_binding  />
        <operation name="Consume_Message">
      <jca:operation
          DestinationName="jms/ETH_ALICE_ASN_OAGIS_7_2"
          UseMessageListener="false"
          PayloadType="TextMessage"
          ActivationSpec="oracle.tip.adapter.jms.inbound.JmsConsumeActivationSpec"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="ETH_DEQJMS_ALICE_ASN_OAGIS_7_2">
        <port name="Consume_Message_pt" binding="tns:Consume_Message_binding">
      <jca:address location="eis/Jms/ETHTopicConnection" UIConnectionName="LocalAppServer"
          ManagedConnectionFactory="oracle.tip.adapter.jms.JmsManagedConnectionFactory"
          mcf.ConnectionFactoryLocation="jms/TopicConnectionFactory"
          mcf.IsTopic="true"
          mcf.IsTransacted="false"
          mcf.FactoryProperties=""
          mcf.Username="oc4jadmin"
          mcf.Password="F44034A2DD8158AE53D924290C873D4A"
          UIJmsProvider="OC4JJMS" />
        </port>
    </service>
  <plt:partnerLinkType name="Consume_Message_plt" >
    <plt:role name="Consume_Message_role" >
      <plt:portType name="tns:Consume_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
