<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="LBT_UPDATE_Fusn_Table"
    targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/LBT_UPDATE_Fusn_Table/"
    xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/LBT_UPDATE_Fusn_Table/"
    xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
    xmlns:pc="http://xmlns.oracle.com/pcbpel/"
    xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/LBTUPDATEFusnTable"
    xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/LBTUPDATEFusnTable"
                schemaLocation="LBTUPDATEFusnTable_table.xsd"/>
        </schema>
    </types>

    <message name="EmrFusionChangeControlCollection_msg">
        <part name="EmrFusionChangeControlCollection" element="top:EmrFusionChangeControlCollection"/>
    </message>


    <portType name="LBT_UPDATE_Fusn_Table_ptt">
        <operation name="update">
            <input message="tns:EmrFusionChangeControlCollection_msg"/>
        </operation>
    </portType>

    <binding name="LBT_UPDATE_Fusn_Table_binding" type="tns:LBT_UPDATE_Fusn_Table_ptt">
        <jca:binding />
        <operation name="update">
            <jca:operation
                InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"

                DescriptorName="LBTUPDATEFusnTable.EmrFusionChangeControl"
                DmlType="update"
                DetectOmissions="true"
                OptimizeMerge="true"
                MappingsMetaDataURL="LBTUPDATEFusnTable_toplink_mappings.xml" />
            <input>
                <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
            </input>
        </operation>
    </binding>

    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/DB/itemHub is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="LBT_UPDATE_Fusn_Table">
        <port name="LBT_UPDATE_Fusn_Table_pt" binding="tns:LBT_UPDATE_Fusn_Table_binding">
            <jca:address location="eis/DB/itemHub"
                UIConnectionName="itemHub"
                ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
                mcf.DriverClassName="oracle.jdbc.OracleDriver"
                mcf.PlatformClassName="oracle.toplink.platform.database.oracle.Oracle10Platform"
                mcf.ConnectionString="jdbc:oracle:thin:@//enpushntora01.na.enpad.org:1521/enps"
                mcf.UserName="fusion"
                mcf.Password="631F097942148D7DF48C54F2DE1BBC2B"
            />
        </port>
    </service>

    <plt:partnerLinkType name="LBT_UPDATE_Fusn_Table_plt" >
        <plt:role name="LBT_UPDATE_Fusn_Table_role" >
            <plt:portType name="tns:LBT_UPDATE_Fusn_Table_ptt" />
        </plt:role>
    </plt:partnerLinkType>

</definitions>
