<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="LBT_Rtr_OperatingType"
     targetNamespace="http://oracle.com/esb/namespaces/Liebert_OrgsOperating"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://oracle.com/esb/namespaces/Liebert_OrgsOperating"
     xmlns:inp1="http://xmlns.oracle.com/pcbpel/adapter/db/top/LBTSELECTOperatingType"
    >
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/LBTSELECTOperatingType" schemaLocation="LBTSELECTOperatingType_table.xsd" />
      </schema>
    </types>
    <message name="EmrOperatingTypeCollection_request">
        <part name="EmrOperatingTypeCollection" element="inp1:EmrOperatingTypeCollection"/>
    </message>
    <portType name="execute_ppt">
        <operation name="execute">
            <input message="tns:EmrOperatingTypeCollection_request"/>
        </operation>
    </portType>
</definitions>
