<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="Liebert_OrgsOperating_LBT_Rtr_OperatingunitFTP.wsdl"/>
      <rootElement name="SyncPartyMaster" namespace="http://www.openapplications.org/oagis/9"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://essapt020-u006:12001/orabpel/LiebertServices/LIEBERT_VENDAVO_INTEGRATION_ENPOperatingUnit_BPEL/1.0/LIEBERT_VENDAVO_INTEGRATION_ENPOperatingUnit_BPEL?wsdl"/>
      <rootElement name="Root-Element" namespace="http://TargetNamespace.com/FtpOpertngUnit_to_Vendavo"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [THU NOV 20 15:10:53 IST 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns9="http://TargetNamespace.com/FtpOpertngUnit_to_Vendavo"
                xmlns:ns4="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns6="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ns3="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns1="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns2="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="http://oracle.com/esb/namespaces/Liebert_OrgsOperating"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns8="http://xmlns.oracle.com/LIEBERT_VENDAVO_INTEGRATION_ENPOperatingUnit_BPEL"
                xmlns:inp1="http://www.openapplications.org/oagis/9"
                xmlns:ns5="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns7="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                exclude-result-prefixes="xsl ns4 ns6 ns3 ns1 ns0 ns2 tns inp1 ns5 ns7 ns9 plnk wsa soap ns8 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns9:Root-Element>
      <xsl:for-each select="/inp1:SyncPartyMaster/DataArea">
        <ns9:rec>
         <ns9:C1>
                <xsl:value-of select="concat('&quot;',inp1:PartyMaster/inp1:PartyIDs/inp1:ID,'&quot;')"/>
              </ns9:C1>
              <ns9:C2>
                <xsl:value-of select="concat('&quot;',inp1:PartyMaster/inp1:ParentParty/inp1:Name,'&quot;')"/>
              </ns9:C2>
              <ns9:C3>
                <xsl:value-of select="concat('&quot;',inp1:PartyMaster/inp1:ParentParty/inp1:Location/@type,'&quot;')"/>
          </ns9:C3>
            </ns9:rec>
      </xsl:for-each>
    </ns9:Root-Element>
  </xsl:template>
</xsl:stylesheet>
