<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/ForeignChar_1.xsd"/>
      <rootElement name="Root-Element" namespace="http://schema.emerson.com/FL_GET_ForeignCharacter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/OutFile.xsd"/>
      <rootElement name="Outfile" namespace="http://schema.emerson.com/out"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [THU NOV 24 23:08:33 GMT+05:30 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://schema.emerson.com/out"
                xmlns:ethCustomSOA="http://www.oracle.com/XSL/Transform/java/com.emerson.eth3.customSOA.ETHCustomSOAExtension"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ethCustomXSLT="http://www.oracle.com/XSL/Transform/java/com.emerson.eth3.customXSLT.ETHCustomXSLTExtension"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:tns="http://schema.emerson.com/FL_GET_ForeignCharacter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl nxsd xsd tns ns0 aia bpws xp20 ethCustomSOA bpel bpm ora socket mhdr oraext ethCustomXSLT dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:Outfile>
      <xsl:for-each select="/tns:Root-Element/tns:Line">
        <ns0:Line>
          <ns0:Value1>
            <xsl:value-of select="tns:COLUMN1"/>
          </ns0:Value1>
          <ns0:Value2>
            <xsl:value-of select="tns:COLUMN2"/>
          </ns0:Value2>
          <ns0:Value3>
            <xsl:value-of select="tns:COLUMN3"/>
          </ns0:Value3>
        </ns0:Line>
      </xsl:for-each>
    </ns0:Outfile>
  </xsl:template>
</xsl:stylesheet>
