<definitions
     name="TempFileAdpter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/TempFileAdpter/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/TempFileAdpter/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.emrsn.com/CustomProcess_PO_007"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/file/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/file/" location="fileAdapterInboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.emrsn.com/CustomProcess_PO_007" schemaLocation="public_html/CustomProcess_PO_007.xsd" />
      </schema>
    </types>
    <message name="CustomProcess_PO_007_msg">
        <part name="CustomProcess_PO_007" element="imp1:CustomProcess_PO_007"/>
    </message>
    <portType name="Read_ptt">
        <operation name="Read">
            <input message="tns:CustomProcess_PO_007_msg"/>
        </operation>
    </portType>
    <binding name="Read_binding" type="tns:Read_ptt">
    <pc:inbound_binding  />
        <operation name="Read">
      <jca:operation
          PhysicalDirectory="D:\oracle\Files\esbIn"
          ActivationSpec="oracle.tip.adapter.file.inbound.FileActivationSpec"
          PhysicalArchiveDirectory="D:\oracle\Files\archive"
          DeleteFile="true"
          IncludeFiles="EMCXml_OFM_PO.*\.dat"
          PollingFrequency="60"
          MinimumAge="0"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="TempFileAdpter">
        <port name="Read_pt" binding="tns:Read_binding">
      <jca:address location="eis/FileAdapter" UIincludeWildcard="EMCXml_OFM_PO*.dat" />
        </port>
    </service>
  <plt:partnerLinkType name="Read_plt" >
    <plt:role name="Read_role" >
      <plt:portType name="tns:Read_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
