<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETH_DEQJMS_CustomProcessPO.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_B2BInOut_ETH_ProcessPO_CustomEDI_5020_RemoveNamespace_RS.wsdl"/>
      <rootElement name="CustomEDI850" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [THU MAR 05 18:14:56 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"
                xmlns:ns5="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns7="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ns4="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns1="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns9="urn:oracle:integration:b2b:DCC1FCD2811C47748DF43A39F735F4F0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:imp1="http://www.openapplications.org/oagis/9"
                xmlns:ns6="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns8="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                exclude-result-prefixes="xsl imp1 inp1 ns5 ns7 ns4 ns1 ns0 ns2 tns ns3 ns6 ns8 ns9 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <inp1:CustomEDI850>
    <xsl:variable name="SC_SeqNo">  
        <xsl:value-of select="orcl:sequence-next-val('B2B_MSG_SEQ','jdbc/ETH_BusinessDB')"/>
      </xsl:variable>  
      <ns9:Transaction-850>
    <!-- <xsl:variable name="flowID">  
      <xsl:value-of select="ehdr:getInstanceID()"/>
      </xsl:variable>-->
      <xsl:variable name="Current_date">  
        <xsl:value-of select="xp20:current-date()"/>
      </xsl:variable>
      <xsl:attribute name="XDataVersion">
        <xsl:value-of select='string("1.0")'/>
      </xsl:attribute>
      <xsl:attribute name="Standard">
        <xsl:value-of select='string("X12")'/>
      </xsl:attribute>
      <xsl:attribute name="GUID">
        <xsl:value-of select='string("{D4791971-A782-D811-B0F2-080020C8C860}")'/>
      </xsl:attribute>
      <xsl:attribute name="CreatedBy">
        <xsl:value-of select='string("ECXEngine_899")'/>
      </xsl:attribute>
      <xsl:attribute name="CreatedDate"> <!--ADDED AS ON 17 OCT -->
        <xsl:value-of select="xp20:current-dateTime()"/>
      </xsl:attribute>
    <!--  <ns9:Segment-ISA> -->
        <!-- <ns9:Element-I01>
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:AuthorizationID"/>
        </ns9:Element-I01>-->
        <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
        <!-- <ns9:Element-I13>
          <xsl:value-of select="string(0.0)"/>
        </ns9:Element-I13>-->
      <!--  <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO">
          <xsl:if test='@systemEnvironmentCode = "Production"'>
            <ns9:Element-I14>
              <xsl:value-of select='string("P")'/>
            </ns9:Element-I14>
          </xsl:if>
        </xsl:for-each>
        <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO">
          <xsl:if test='@systemEnvironmentCode = "Test"'>
            <ns9:Element-I14>
              <xsl:value-of select='string("T")'/>
            </ns9:Element-I14>
          </xsl:if>
        </xsl:for-each>
      </ns9:Segment-ISA> -->
      <!--   <ns9:Segment-GS> -->
      <!--    <ns9:Element-479>
          <xsl:value-of select='string("PO")'/>
        </ns9:Element-479>
        <ns9:Element-142>
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:LogicalID"/>
        </ns9:Element-142>
        <ns9:Element-373>
          <xsl:value-of select="concat(substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,1.0,4.0),substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,6.0,2.0),substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,9.0,2.0))"/>
        </ns9:Element-373> -->
      <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
      <!-- <ns9:Element-337>
          <xsl:value-of select="concat(substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,12.0,2.0),substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,15.0,2.0),substring(/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:CreationDateTime,18.0,2.0))"/>
        </ns9:Element-337> -->
      <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
      <!--</ns9:Segment-GS>-->
      
      <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:PurchaseOrder">
      
      <ns9:Segment-ST>      
        <ns9:Element-143>
          <xsl:value-of select="string(850.0)"/>
        </ns9:Element-143>
       <!-- <ns9:Element-329>
          <xsl:value-of select="orcl:lookup-table('SC_MASTER_TRANSACTION','FLOW_ID_1',$flowID,'ST_CONTROL','jdbc:polite4:system/any@142.176.225.81:1531:OraESB')"/>
        </ns9:Element-329>-->
        <ns9:Element-329>
          <!--<xsl:value-of select="string('#ControlNumber#')"/>-->
          <xsl:value-of select="$SC_SeqNo"/>
        </ns9:Element-329>
      </ns9:Segment-ST>
      <ns9:Segment-BEG>
       <ns9:Element-353>
          <xsl:value-of select='string("00")'/>
        </ns9:Element-353> <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
        <xsl:choose>
          <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
          <xsl:when test='imp1:PurchaseOrderHeader/imp1:DocumentID/imp1:VariationID = "STANDARD"'>
            <ns9:Element-92>
              <xsl:value-of select='string("SA")'/>
            </ns9:Element-92>
          </xsl:when>
          <xsl:when test='imp1:PurchaseOrderHeader/imp1:DocumentID/imp1:VariationID = "BLANKET"'>
            <ns9:Element-92>
              <xsl:value-of select='string("BK")'/>
            </ns9:Element-92>
          </xsl:when>
        </xsl:choose>
        <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
        <ns9:Element-324>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:DocumentID/imp1:ID"/>
        </ns9:Element-324>
        <ns9:Element-328>
          <!--<xsl:value-of select="imp1:PurchaseOrderHeader/imp1:ContractReference/imp1:ReleaseNumber"/>-->
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:ReleaseNumber"/>
        </ns9:Element-328>
        <ns9:Element-373>           <!-- ADDED AS ON 25 SEP -->        
           <xsl:value-of select="concat(substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,1.0,4.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,6.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,9.0,2.0))"/>
          <!--<xsl:value-of select="concat(substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,1.0,4.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,6.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,9.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,12.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,15.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:DocumentDateTime,18.0,2.0))"/> -->
        </ns9:Element-373>
        <ns9:Element-367>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:ContractReference/imp1:DocumentID/imp1:ID"/>
        </ns9:Element-367>  
        
         <!--<xsl:if test='(imp1:ProcessPurchaseOrder/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "Y") or (imp1:ProcessPurchaseOrder/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "AcknowledgementRequired")'>-->
         <xsl:if test='(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "Y") or (imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "AcknowledgementRequired")'>
            <ns9:Element-587>
              <xsl:value-of select='string("AC")'/>
            </ns9:Element-587>
          </xsl:if>
          <!--<xsl:if test='(imp1:ProcessPurchaseOrder/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "N") or (imp1:ProcessPurchaseOrder/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "DoNotAcknowledge")'>-->
          <xsl:if test='(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "N") or (imp1:PurchaseOrderHeader/imp1:UserArea/imp1:ActionExpression/@actionCode = "DoNotAcknowledge")'>
            <ns9:Element-587>
              <xsl:value-of select='string("NA")'/>
            </ns9:Element-587>
          </xsl:if>
          <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
         <!-- <xsl:if test='/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:Process/@acknowledgeCode = ("Y")'>
            <ns9:Element-587>
              <xsl:value-of select='string("AC")'/>
            </ns9:Element-587>
          </xsl:if>
          <xsl:if test='/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:Process/@acknowledgeCode = ("N")'> 
            <ns9:Element-587>
              <xsl:value-of select='string("NA")'/>
            </ns9:Element-587>
          </xsl:if>--><!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP --><!--Removed as on 3 Nov -->
        <ns9:Element-786>
          <xsl:value-of select='string("03")'/>
        </ns9:Element-786>
        <!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
      </ns9:Segment-BEG>
      <ns9:Segment-CUR>
        <ns9:Element-98>
          <xsl:value-of select='string("BY")'/>
        </ns9:Element-98>
        <ns9:Element-100>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:ExtendedAmount/@currencyID"/>
        </ns9:Element-100> 
        <!-- need to remove the following mapping once the EXTENDEDAMOUNT Issue is resolved in Flatfile --> 
       <!-- <xsl:choose>
        <xsl:when test="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:LogicalID ='LIEBERTNA'"> 
        <ns9:Element-100>
          <xsl:value-of select="string('USD')"/>
        </ns9:Element-100>
        </xsl:when>
        <xsl:otherwise>
        <ns9:Element-100>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:ExtendedAmount/@currencyID"/>
        </ns9:Element-100>
        </xsl:otherwise>
        </xsl:choose>-->
        <!-- ADDED AS ON 23 OCT "RateNumeric CONDITION" -->   
        <xsl:if test='imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:RateNumeric != ""'>  
        <ns9:Element-280>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:RateNumeric"/>
        </ns9:Element-280> 
        </xsl:if>
        <xsl:if test='imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime != ""'> <!-- ADDED AS ON 23 OCT -->   
        <ns9:Element-374>
          <xsl:value-of select='string("AAY")'/>
        </ns9:Element-374>
        <ns9:Element-373_1>
          <xsl:value-of select="concat(substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,1.0,4.0),substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,6.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,9.0,2.0))"/>
        </ns9:Element-373_1>
        <ns9:Element-337_1>
          <xsl:value-of select="concat(substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,12.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,15.0,2.0),substring(imp1:PurchaseOrderHeader/imp1:UserArea/imp1:CurrencyExchangeRate/imp1:SetDateTime,18.0,2.0))"/>
        </ns9:Element-337_1>
        </xsl:if><!-- ADDED AS ON 25 SEP -->   
      </ns9:Segment-CUR>
      
      <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender">
        <ns9:Segment-REF>
          <ns9:Element-128>
            <xsl:value-of select='string("S3")'/>
          </ns9:Element-128>
          <ns9:Element-127>
            <xsl:value-of select='string("EMR850V5.0")'/> <!-- ADDED AS ON 25 SEP -->
          </ns9:Element-127>
        </ns9:Segment-REF>
      </xsl:for-each> 
      
      <!-- ADDED AS ON 23 OCT " IF COMDITION ,FOR-EACH & REF" -->
     
     <xsl:for-each select="imp1:PurchaseOrderHeader"> 
   <!--  <xsl:if test="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:LogicalID ='LIEBERTNA'"> -->
     <xsl:if test='imp1:DocumentID/imp1:RevisionID != ""'> 
          <ns9:Segment-REF>
            <ns9:Element-128>
              <xsl:value-of select='string("PP")'/>
            </ns9:Element-128>
            <ns9:Element-352>
              <xsl:value-of select="imp1:DocumentID/imp1:RevisionID"/>
            </ns9:Element-352>
          </ns9:Segment-REF>
       
     </xsl:if> 
    </xsl:for-each>
    
      <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender">
      <!--<xsl:if test ='imp1:ReferenceID != ""'> --><!-- Removed as on 3 Nov -->
       <xsl:if test='imp1:AuthorizationID !=""'><!-- Changed as on 3 Nov -->
        <ns9:Segment-REF>
          <ns9:Element-128>
            <xsl:value-of select='string("06")'/>
          </ns9:Element-128>
          <ns9:Element-352>
	    <!-- <xsl:value-of select="imp1:ReferenceID"/> --><!-- Removed as on 3 Nov -->
            <xsl:value-of select="imp1:AuthorizationID"/><!-- Changed as on 3 Nov -->
          </ns9:Element-352>
        </ns9:Segment-REF>
        </xsl:if>
      </xsl:for-each>
      
      <xsl:if test='imp1:PurchaseOrderHeader/imp1:Description !=""'> <!-- ADDED AS ON 25 SEP -->   
      <xsl:for-each select="imp1:PurchaseOrderHeader"> 
        <ns9:Segment-REF>
          <ns9:Element-128>
            <xsl:value-of select='string("K6")'/>  <!-- CHANGED ON 24 SEP -->
          </ns9:Element-128>
          <ns9:Element-352>
            <xsl:value-of select="imp1:Description"/> <!-- CHANGED ON 24 SEP -->
          </ns9:Element-352>
        </ns9:Segment-REF>
      </xsl:for-each>
       </xsl:if>      <!-- ADDED AS ON 25 SEP -->
       
   <!-- ADDED AS ON 1 DEC THE FOLLOWING REF SEGMENT-->
  <!-- <xsl:for-each select="imp1:PurchaseOrderLine/imp1:PurchaseOrderSchedule/imp1:Note">-->
 <!--<xsl:if test='((imp1:PurchaseOrderLine/imp1:Note[1] !="") and (imp1:PurchaseOrderLine/imp1:Note[1]/@author = "Emerson Location Identifier"))'>
          <ns9:Segment-REF>
            <ns9:Element-128>
              <xsl:value-of select='string("4C")'/>
            </ns9:Element-128>
            <ns9:Element-127>
              <xsl:value-of select="imp1:PurchaseOrderLine/imp1:Note[1]"/>
            </ns9:Element-127>
          </ns9:Segment-REF>
    </xsl:if>
    <xsl:if test='((imp1:PurchaseOrderLine/imp1:Note[2] !="") and (imp1:PurchaseOrderLine/imp1:Note[2]/@author = "Kanban Card Number"))'>
          <ns9:Segment-REF>
            <ns9:Element-128>
              <xsl:value-of select='string("KE")'/>
            </ns9:Element-128>
            <ns9:Element-127>
              <xsl:value-of select="imp1:PurchaseOrderLine/imp1:Note[2]"/>
            </ns9:Element-127>
          </ns9:Segment-REF>
    </xsl:if>-->
 <!--</xsl:for-each>-->
 <!-- ADDED AS ON 1 DEC THE FOLLLOWING IF CONDITION -->
   <xsl:if test="(imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:FreightTermCode != '') or (imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:PlaceOfOwnershipTransferLocation/imp1:Name !='') "> 
      <ns9:Segment-FOB> 
        <ns9:Element-146>       
          <xsl:value-of select='string("DF")'/>
        </ns9:Element-146>
        <xsl:if test="imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:FreightTermCode != ''">
         <ns9:Element-309>
          <xsl:value-of select='string("ZZ")'/>
        </ns9:Element-309>
        <ns9:Element-352>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:FreightTermCode"/>
        </ns9:Element-352>
        </xsl:if>
        <!--ADDED AS ON 23 OCT "LOGICALID" CONDITION -->
        <xsl:if test="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:LogicalID ='LIEBERTNA'">
        <xsl:if test="imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:PlaceOfOwnershipTransferLocation/imp1:Name !=''">
        <ns9:Element-309_1>
          <xsl:value-of select='string("ZZ")'/>
        </ns9:Element-309_1>
        <ns9:Element-352_1>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:TransportationTerm/imp1:PlaceOfOwnershipTransferLocation/imp1:Name"/>
        </ns9:Element-352_1>
        </xsl:if>
        </xsl:if>
      </ns9:Segment-FOB> 
      </xsl:if>
       <!-- ADDED If as on April-24- 2009 as it was erroring out in B2B at the segment count-->
      <xsl:if test="imp1:PurchaseOrderHeader/imp1:PaymentTerm/imp1:Term/imp1:ID !=''">
      <ns9:Segment-ITD>
        <ns9:Element-352>
          <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:PaymentTerm/imp1:Term/imp1:ID"/>
        </ns9:Element-352>
      </ns9:Segment-ITD>
      </xsl:if>
       <!-- ADDED If as on April-24- 2009-->
       <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note != ''">
        <ns9:Loop-N9><!-- ADDED AS ON 8 OCT "loop-n9" -->
        <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note != ''">
        <ns9:Segment-N9>
          <ns9:Element-128>
            <xsl:value-of select='string("L1")'/>
          </ns9:Element-128>
          <ns9:Element-127>
            <xsl:value-of select='string("PO Header Instructions to Supplier")'/>
          </ns9:Element-127>
        </ns9:Segment-N9>   
        </xsl:if>
       
        <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note != ''">
        <ns9:Segment-MTX>
          <ns9:Element-363>
            <xsl:value-of select='string("OTH")'/>
          </ns9:Element-363>
          <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note[1] != ''">
           <ns9:Element-1551>
            <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:Note[1]"/>
          </ns9:Element-1551>
          </xsl:if>
          <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note[1] = ''">
           <ns9:Element-1551>
            <xsl:value-of select="string('NULL')"/>
          </ns9:Element-1551>
          </xsl:if>
          <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note[2] != ''">
          <ns9:Element-1551_1>
            <xsl:value-of select="imp1:PurchaseOrderHeader/imp1:Note[2]"/>
          </ns9:Element-1551_1> 
          </xsl:if>
          <xsl:if test="imp1:PurchaseOrderHeader/imp1:Note[2] = ''">
          <ns9:Element-1551_1>
            <xsl:value-of select="string('NULL')"/>
          </ns9:Element-1551_1> 
          </xsl:if>
        </ns9:Segment-MTX> 
         </xsl:if>
      </ns9:Loop-N9>
      </xsl:if><!-- ADDED AS ON 8 OCT "loop-n9"-->
   <!--REMOVED ON 8 OCT "LDT" -->
   <!--<ns9:Loop-LDT>
        <xsl:choose>
          <xsl:when test='imp1:PurchaseOrderHeader/imp1:Note[@index = "1"] != ""'>
            <ns9:Segment-MTX>
              <ns9:Element-363>
                <xsl:value-of select='string("OTH")'/>
              </ns9:Element-363>
              <ns9:Element-1551>
                <xsl:value-of select='imp1:PurchaseOrderHeader/imp1:Note[@index = "1"]'/>
              </ns9:Element-1551>
            </ns9:Segment-MTX>
          </xsl:when>
          <xsl:when test='imp1:PurchaseOrderHeader/imp1:Note[@index = "2"] != ""'>
            <ns9:Segment-MTX>
              <ns9:Element-363>
                <xsl:value-of select='string("OTH")'/>
              </ns9:Element-363>
              <ns9:Element-1551_1>
                <xsl:value-of select='imp1:PurchaseOrderHeader/imp1:Note[@index = "2"]'/>
              </ns9:Element-1551_1>
            </ns9:Segment-MTX>
          </xsl:when>
        </xsl:choose>
      </ns9:Loop-LDT> --><!--REMOVED ON 8 OCT --><!-- ADDED AS PER ROBIN'S MAIL ON 23 SEP -->
      <!-- SUPPLIER -->
      <xsl:for-each select="imp1:PurchaseOrderHeader/imp1:SupplierParty">
        <ns9:Loop-N1>
          <ns9:Segment-N1>
            <ns9:Element-98>
              <xsl:value-of select='string("VN")'/>
            </ns9:Element-98>
            <ns9:Element-93>
              <xsl:value-of select="substring(imp1:Name,1.0,60.0)"/>
            </ns9:Element-93>
            <ns9:Element-66>
              <xsl:value-of select='string("93")'/>
            </ns9:Element-66>
            <ns9:Element-67>
              <xsl:value-of select="imp1:PartyIDs/imp1:ID"/>
            </ns9:Element-67>
          </ns9:Segment-N1>
          <xsl:variable name="LENGTH_VN">  
             <xsl:value-of select="string-length(imp1:Name)"/>
          </xsl:variable> 
         <xsl:if test="$LENGTH_VN > 60.0">   <!-- ADDED AS ON 8 OCT-->
          <ns9:Segment-N2>
            <ns9:Element-93_1>
              <xsl:value-of select="substring(imp1:Name,60.0)"/>
            </ns9:Element-93_1>
          </ns9:Segment-N2>
          </xsl:if>
            <!--Changed  AS ON 22 APR  -->  
        <!--Changed  AS ON 19 MAR  -->  
      
          <xsl:if test='(imp1:Location/imp1:Address/imp1:LineOne!="") or (imp1:Location/imp1:Address/imp1:LineTwo != "")'>
            <ns9:Segment-N3>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> 
            </ns9:Element-166>
            </xsl:if>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineOne,1,54),'+')"/>
              <!--<xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> -->
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineTwo"/>
            </ns9:Element-166_1>
               </xsl:if>
                <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo)  &gt; 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineTwo,1,54),'+')"/>
            </ns9:Element-166_1>
               </xsl:if>
          </ns9:Segment-N3> 
       
          </xsl:if>
            <!--Changed  AS ON 22 APR  -->  
 <!--Changed  AS ON 19 MAR  -->  
 <xsl:if test='(imp1:Location/imp1:Address/imp1:LineThree!="") or (imp1:Location/imp1:Address/imp1:LineFour != "")'>
            <ns9:Segment-N3>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineThree"/>
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineThree,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineFour"/>
            </ns9:Element-166_1>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineFour,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
         
            
          </ns9:Segment-N3> 
          </xsl:if>
         
          <!--ADDED AS ON 16 OCT -->
    
          <ns9:Segment-N4>
            <ns9:Element-19>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:CityName"/>
            </ns9:Element-19>
            <!--<xsl:if test='((imp1:Location/imp1:Address/imp1:CountryCode = "US") or (imp1:Location/imp1:Address/imp1:CountryCode ="CA"))'>
              <ns9:Element-156>
                <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/>
              </ns9:Element-156>
            </xsl:if>--><!-- Removed on 18 MAR-->
            <ns9:Element-116>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:PostalCode"/>
            </ns9:Element-116>
            <ns9:Element-26>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountryCode"/>
            </ns9:Element-26>
             <xsl:if test ="imp1:Location/imp1:ID !=''"> <!-- Added as on 3 Nov the "If" condition -->
            <ns9:Element-309>
              <xsl:value-of select="string(93.0)"/>
            </ns9:Element-309>
            <ns9:Element-310>
              <xsl:value-of select="imp1:Location/imp1:ID"/>
            </ns9:Element-310>
            </xsl:if>
           <!-- <xsl:if test='((imp1:Location/imp1:Address/imp1:CountryCode != "US") or (imp1:Location/imp1:Address/imp1:CountryCode ="CA"))'>-->
             <!-- Added choose when condition on April-24 2009 to convert contrydivision name  to  code-->
                 <xsl:if test="(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode !='')">
             <xsl:choose>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &lt;= 3)">
              <ns9:Element-1715>
              <!--Changed on April-22-->
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode)'/>
              <!--  <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/> -->
              </ns9:Element-1715>
              </xsl:when>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &gt; 3)">
              <ns9:Element-1715>
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode","ZZZ")'/> 
             
              </ns9:Element-1715>
          </xsl:when>
          </xsl:choose>
          </xsl:if>
           <!-- </xsl:if>--> 
          </ns9:Segment-N4> 
          <!--ADDED AS ON 23 OCT "NAME CONDITION" -->
          <xsl:if test='((imp1:CustomerServiceContact/imp1:Name != "") or (imp1:CustomerServiceContact/imp1:Communication[3]/imp1:DialNumber != "")or(imp1:CustomerServiceContact/imp1:Communication[2]/imp1:DialNumber != "")or(imp1:CustomerServiceContact/imp1:Communication[1]/imp1:URI != ""))'>
          <!--<xsl:if test='imp1:CustomerServiceContact/imp1:Name != ""'>-->
           <ns9:Segment-PER>
                <ns9:Element-366>
                  <xsl:value-of select='string("SU")'/>
                </ns9:Element-366>
                <xsl:if test='imp1:CustomerServiceContact/imp1:Name != ""'>
              <ns9:Element-93>
                <xsl:value-of select="imp1:CustomerServiceContact/imp1:Name"/>
              </ns9:Element-93>
              </xsl:if>
              <xsl:if test='imp1:CustomerServiceContact/imp1:Communication[3]/imp1:DialNumber != ""'>
                <ns9:Element-365>
                  <xsl:value-of select='string("TE")'/>
                </ns9:Element-365>
              <ns9:Element-364>
                <xsl:value-of select="imp1:CustomerServiceContact/imp1:Communication[3]/imp1:DialNumber"/>
              </ns9:Element-364>
               </xsl:if>
              <xsl:if test='imp1:CustomerServiceContact/imp1:Communication[2]/imp1:DialNumber != ""'>
                <ns9:Element-365_1>
                  <xsl:value-of select='string("FX")'/>
                </ns9:Element-365_1>
              <ns9:Element-364_1>
                <xsl:value-of select="imp1:CustomerServiceContact/imp1:Communication[2]/imp1:DialNumber"/>
              </ns9:Element-364_1>
              </xsl:if>
              <xsl:if test='imp1:CustomerServiceContact/imp1:Communication[1]/imp1:URI != ""'>
              <ns9:Element-365_2>
                <xsl:value-of select='string("EM")'/>
              </ns9:Element-365_2>
              <ns9:Element-364_2>
                <xsl:value-of select="imp1:CustomerServiceContact/imp1:Communication[1]/imp1:URI"/>
              </ns9:Element-364_2>
              </xsl:if>
            </ns9:Segment-PER>  
          </xsl:if>
        </ns9:Loop-N1>
      </xsl:for-each>
      <!-- SOLDTO -->
      <xsl:for-each select="imp1:PurchaseOrderHeader/imp1:BuyerParty">
        <xsl:if test='concat(@category,"BuyerParty")'>
          <ns9:Loop-N1>
            <ns9:Segment-N1>
              <ns9:Element-98>
                <xsl:value-of select='string("SO")'/>
              </ns9:Element-98>
              <ns9:Element-93>
                <xsl:value-of select="substring(imp1:Name,1.0,60.0)"/>
              </ns9:Element-93>
            </ns9:Segment-N1>
            <xsl:variable name="LENGTH_SO">  
                 <xsl:value-of select="string-length(imp1:Name)"/>
            </xsl:variable> 
            <xsl:if test="$LENGTH_SO > 60.0"><!-- ADDED AS ON 8 OCT-->
            <ns9:Segment-N2>
              <ns9:Element-93_1>
                <xsl:value-of select="substring(imp1:Name,60.0)"/>
              </ns9:Element-93_1>
            </ns9:Segment-N2>
            </xsl:if>
            <!--Changed  AS ON 22 APR-->  <!--Changed  AS ON 19 MAR  -->  
           <xsl:if test='(imp1:Location/imp1:Address/imp1:LineOne!="") or (imp1:Location/imp1:Address/imp1:LineTwo != "")'>
            <ns9:Segment-N3>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> 
            </ns9:Element-166>
            </xsl:if>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineOne,1,54),'+')"/>
              <!--<xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> -->
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineTwo"/>
            </ns9:Element-166_1>
               </xsl:if>
                <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo)  &gt; 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineTwo,1,54),'+')"/>
            </ns9:Element-166_1>
               </xsl:if>
          </ns9:Segment-N3> 
       
          </xsl:if>
  <!--Changed  AS ON 22 APR-->  <!--Changed  AS ON 19 MAR  -->  
 <xsl:if test='(imp1:Location/imp1:Address/imp1:LineThree!="") or (imp1:Location/imp1:Address/imp1:LineFour != "")'>
            <ns9:Segment-N3>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineThree"/>
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineThree,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineFour"/>
            </ns9:Element-166_1>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineFour,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
                     
          </ns9:Segment-N3> 
          </xsl:if>
            <ns9:Segment-N4>
              <ns9:Element-19>
                <xsl:value-of select="imp1:Location/imp1:Address/imp1:CityName"/>
              </ns9:Element-19>
              <!--<xsl:if test='(imp1:Location/imp1:Address/imp1:CountryCode = "US") or (imp1:Location/imp1:Address/imp1:CountryCode="CA")'>
                <ns9:Element-156>
                  <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/>
                </ns9:Element-156>
              </xsl:if>--><!-- Removed on 18 MAR-->
              <ns9:Element-116>
                <xsl:value-of select="imp1:Location/imp1:Address/imp1:PostalCode"/>
              </ns9:Element-116>
              <ns9:Element-26>
                <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountryCode"/>
              </ns9:Element-26>
              <xsl:if test ="imp1:Location/imp1:ID !=''"> <!-- Added as on 3 Nov the "If" condition -->
              <ns9:Element-309>
                <xsl:value-of select="string(93.0)"/>
              </ns9:Element-309>
              <ns9:Element-310>
                <xsl:value-of select="imp1:Location/imp1:ID"/>
              </ns9:Element-310>
              </xsl:if>
             <!-- <xsl:if test='(imp1:Location/imp1:Address/imp1:CountryCode != "US") or (imp1:Location/imp1:Address/imp1:CountryCode !="CA")'>-->
                <!-- Changed as on 22-APR-->
                 <!-- Added choose when condition on April-24 2009 to convert contrydivision name  to  code-->
             <xsl:if test="(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode !='')">
             <xsl:choose>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &lt;= 3)">
              <ns9:Element-1715>
              <!--Changed on April-22-->
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode)'/>
              <!--  <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/> -->
              </ns9:Element-1715>
              </xsl:when>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &gt; 3)">
              <ns9:Element-1715>
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode","ZZZ")'/> 
             
              </ns9:Element-1715>
          </xsl:when>
          </xsl:choose>
          </xsl:if>
              <!--</xsl:if>-->
            </ns9:Segment-N4>
          </ns9:Loop-N1>
        </xsl:if>
      </xsl:for-each>
      
     <!-- BILLTO --> 
      <xsl:for-each select="imp1:PurchaseOrderHeader/imp1:BillToParty">
        <ns9:Loop-N1>
          <ns9:Segment-N1>
            <ns9:Element-98>
              <xsl:value-of select='string("BT")'/>
            </ns9:Element-98>
            <ns9:Element-93>
              <xsl:value-of select="substring(imp1:Name,1.0,60.0)"/>
            </ns9:Element-93>
          </ns9:Segment-N1>
          <xsl:variable name="LENGTH_BT">  
                 <xsl:value-of select="string-length(imp1:Name)"/>
            </xsl:variable> 
            <xsl:if test="$LENGTH_BT > 60.0"><!-- ADDED AS ON 8 OCT-->
          <ns9:Segment-N2>
            <ns9:Element-93_1>
              <xsl:value-of select="substring(imp1:Name,60.0)"/>
            </ns9:Element-93_1>
          </ns9:Segment-N2>
          </xsl:if>
           <!--Changed  AS ON 22-APR -->  
          <!--changed as on 19-Mar-->
        <xsl:if test='(imp1:Location/imp1:Address/imp1:LineOne!="") or (imp1:Location/imp1:Address/imp1:LineTwo != "")'>
            <ns9:Segment-N3>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> 
            </ns9:Element-166>
            </xsl:if>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineOne) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineOne,1,54),'+')"/>
              <!--<xsl:value-of select="imp1:Location/imp1:Address/imp1:LineOne"/> -->
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineTwo"/>
            </ns9:Element-166_1>
               </xsl:if>
                <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineTwo)  &gt; 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineTwo,1,54),'+')"/>
            </ns9:Element-166_1>
               </xsl:if>
          </ns9:Segment-N3> 
       
          </xsl:if>
           <!--Changed  AS ON 22-APR -->  
 <!--Changed  AS ON 19 MAR  -->  
 <xsl:if test='(imp1:Location/imp1:Address/imp1:LineThree!="") or (imp1:Location/imp1:Address/imp1:LineFour != "")'>
            <ns9:Segment-N3>
              <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineThree"/>
            </ns9:Element-166>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineThree) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineThree,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
            <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:LineFour"/>
            </ns9:Element-166_1>
            </xsl:if>
             <xsl:if test='(string-length(imp1:Location/imp1:Address/imp1:LineFour) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:Location/imp1:Address/imp1:LineFour,1,54),'+')"/>
             </ns9:Element-166>
            </xsl:if>
         
            
          </ns9:Segment-N3> 
          </xsl:if>
   <!--   <xsl:if test='(imp1:Location/imp1:Address/imp1:CityName!="") or (imp1:Location/imp1:Address/imp1:PostalCode != "")'-->    
          <ns9:Segment-N4>
            <ns9:Element-19>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:CityName"/>
            </ns9:Element-19>
           <!-- <xsl:if test='((imp1:Location/imp1:Address/imp1:CountryCode = "US") or (imp1:Location/imp1:Address/imp1:CountryCode ="CA"))'>
              <ns9:Element-156>
                <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/>
              </ns9:Element-156>
            </xsl:if>--><!-- Removed on 18 MAR-->
            <ns9:Element-116>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:PostalCode"/>
            </ns9:Element-116>
            <ns9:Element-26>
              <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountryCode"/>
            </ns9:Element-26>
            <xsl:if test ="imp1:Location/imp1:ID !=''"> <!-- Added as on 3 Nov the "If" condition -->
            <ns9:Element-309>
              <xsl:value-of select='string("93")'/>
            </ns9:Element-309>
            <ns9:Element-310>
              <xsl:value-of select="imp1:Location/imp1:ID"/>
            </ns9:Element-310>
            </xsl:if>
            <!--<xsl:if test='((imp1:Location/imp1:Address/imp1:CountryCode != "US") and (imp1:Location/imp1:Address/imp1:CountryCode !="CA"))'>-->
               <!-- Changed as on 22-APR-->
              <!-- Added choose when condition on April-24 2009 to convert contrydivision name  to  code-->
               <xsl:if test="(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode !='')">
             <xsl:choose>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &lt;= 3)">
              <ns9:Element-1715>
              <!--Changed on April-22-->
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode)'/>
              <!--  <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/> -->
              </ns9:Element-1715>
              </xsl:when>
              <xsl:when test="(string-length(imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &gt; 3)">
              <ns9:Element-1715>
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode","ZZZ")'/> 
             
              </ns9:Element-1715>
          </xsl:when>
          </xsl:choose>
            </xsl:if>
          </ns9:Segment-N4>    
          <xsl:if test='((imp1:BuyerContact/imp1:Name !="") or (imp1:BuyerContact/imp1:Communication[3]/imp1:DialNumber != "") or (imp1:BuyerContact/imp1:Communication[2]/imp1:DialNumber != "") or (imp1:BuyerContact/imp1:Communication[1]/imp1:URI != ""))'><!-- ADDED AS ON 4 DEC "NAME CONDITION" -->
           <ns9:Segment-PER><!-- ADDED AS ON 25 SEP -->
              
                <ns9:Element-366>
                  <xsl:value-of select='string("BD")'/>
                </ns9:Element-366>
                <xsl:if test='imp1:BuyerContact/imp1:Name !=""'>
              <ns9:Element-93>
                <xsl:value-of select="imp1:BuyerContact/imp1:Name"/>
              </ns9:Element-93>
              </xsl:if>  
              
             <xsl:if test='imp1:BuyerContact/imp1:Communication[3]/imp1:DialNumber != ""'>
                <ns9:Element-365>
                  <xsl:value-of select='string("TE")'/>
                </ns9:Element-365>
              <ns9:Element-364>
                <xsl:value-of select="imp1:BuyerContact/imp1:Communication[3]/imp1:DialNumber"/>
              </ns9:Element-364>
               </xsl:if>   
               
               <xsl:if test='imp1:BuyerContact/imp1:Communication[2]/imp1:DialNumber != ""'>
                <ns9:Element-365_1>
                  <xsl:value-of select='string("FX")'/>
                </ns9:Element-365_1>
              <ns9:Element-364_1>
                <xsl:value-of select="imp1:BuyerContact/imp1:Communication[2]/imp1:DialNumber"/>
              </ns9:Element-364_1>
               </xsl:if>    
               
             <xsl:if test='imp1:BuyerContact/imp1:Communication[1]/imp1:URI != ""'>
                <ns9:Element-365_2>
                  <xsl:value-of select='string("EM")'/>
                </ns9:Element-365_2>
                <ns9:Element-364_2>
                  <xsl:value-of select="imp1:BuyerContact/imp1:Communication[1]/imp1:URI"/>
                </ns9:Element-364_2>
             </xsl:if> <!-- ADDED AS ON 25 SEP -->
             
           </ns9:Segment-PER>
           </xsl:if>
        </ns9:Loop-N1>
      </xsl:for-each>
      
      <!--CARRIERPARTY-->
      <xsl:if test='imp1:PurchaseOrderHeader/imp1:CarrierParty/imp1:Name != ""'>
      <xsl:for-each select="imp1:PurchaseOrderHeader/imp1:CarrierParty">
        <ns9:Loop-N1>
          <ns9:Segment-N1>
            <ns9:Element-98>
              <xsl:value-of select='string("CA")'/>
            </ns9:Element-98>
            <ns9:Element-93>
              <xsl:value-of select="substring(imp1:Name,1.0,60.0)"/>
            </ns9:Element-93>
          </ns9:Segment-N1>
          <xsl:variable name="LENGTH_CA">  
                 <xsl:value-of select="string-length(imp1:Name)"/>
            </xsl:variable> 
            <xsl:if test="$LENGTH_CA > 60.0"><!-- ADDED AS ON 8 OCT-->
          <ns9:Segment-N2>
            <ns9:Element-93_1>
              <xsl:value-of select="substring(imp1:Name,60.0)"/>
            </ns9:Element-93_1>
          </ns9:Segment-N2>
          </xsl:if>
        </ns9:Loop-N1>
      </xsl:for-each>
      </xsl:if>
      
      
      <ns9:Loop-PO1>
        <xsl:for-each select="/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderLine">
          <ns9:Segment-PO1>
            <ns9:Element-350>
              <xsl:value-of select="imp1:LineNumber"/>
            </ns9:Element-350>
            <ns9:Element-380>
              <xsl:value-of select="imp1:Quantity"/>
            </ns9:Element-380>
            <xsl:if test="imp1:Quantity/@unitCode !=''">
            <ns9:Element-355_1>
              <!--<xsl:value-of select="imp1:Quantity/@unitCode"/>-->
              <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","Target",imp1:Quantity/@unitCode,"EDI",imp1:Quantity/@unitCode)'/>
            </ns9:Element-355_1>
            </xsl:if>
            <xsl:if test="imp1:Quantity/@unitCode =''">
            <ns9:Element-355_1>
              <xsl:value-of select="imp1:Quantity/@unitCode"/>
            </ns9:Element-355_1>
            </xsl:if>
            <!-- <ns9:Element-355_1>
              <xsl:value-of select="imp1:Item/imp1:Packaging/imp1:ID"/>
            </ns9:Element-355_1> -->
            <!-- removed as per robin's mail on 23 Sep -->
            <!--<ns9:Element-212>
              <xsl:value-of select="imp1:UnitPrice/imp1:Amount"/>
            </ns9:Element-212>-->
             <xsl:variable name="amount">  
                <xsl:value-of select="string(number(imp1:UnitPrice/imp1:Amount))"/>
            </xsl:variable> 
            <xsl:choose>
              <xsl:when test="starts-with($amount,'0')">
              <ns9:Element-212>
                 <xsl:value-of select="substring-after($amount,'0')"/>
              </ns9:Element-212>
              </xsl:when>
              <xsl:otherwise>
               <ns9:Element-212>
                 <xsl:value-of select="$amount"/>
               </ns9:Element-212>
              </xsl:otherwise>
            </xsl:choose>
            
            
            
            
            
            
            <xsl:if test="imp1:Item/imp1:ItemID/imp1:ID !=''"><!--ADDED AS ON 09 FEB 2009 -->
            <ns9:Element-235_1>
              <xsl:value-of select='string("SW")'/>
            </ns9:Element-235_1>
            <ns9:Element-234_1>
              <xsl:value-of select="imp1:Item/imp1:ItemID/imp1:ID"/>
            </ns9:Element-234_1>
            </xsl:if>
            <xsl:if test='imp1:Item/imp1:SupplierItemID/imp1:ID != ""'> <!--ADDED AS ON 25 SEP -->
            <ns9:Element-235_2>
              <xsl:value-of select='string("VX")'/>
            </ns9:Element-235_2>
            <ns9:Element-234_2>
              <xsl:value-of select="imp1:Item/imp1:SupplierItemID/imp1:ID"/>
            </ns9:Element-234_2>
            </xsl:if>
            <xsl:if test='imp1:Item/imp1:ItemID/imp1:RevisionID != ""'>  <!--ADDED AS ON 25 SEP -->
            <ns9:Element-235_3>
              <xsl:value-of select='string("BE")'/>
            </ns9:Element-235_3>
            <ns9:Element-234_3>
              <xsl:value-of select="imp1:Item/imp1:ItemID/imp1:RevisionID"/>
            </ns9:Element-234_3>
            </xsl:if>
          </ns9:Segment-PO1>       
     <!--   <ns9:Loop-PID>
          <ns9:Segment-PID>
            <ns9:Element-349>
              <xsl:value-of select='string("F")'/>
            </ns9:Element-349>
            <ns9:Element-352>
              <xsl:value-of select="imp1:Item/imp1:Description"/>
            </ns9:Element-352>
          </ns9:Segment-PID>
        </ns9:Loop-PID> -->
        
        <xsl:variable name="Desc_Len_Var">  
                <xsl:value-of select="string-length(imp1:Item/imp1:Description)"/>
              </xsl:variable>
               <xsl:variable name="Desc_Var">  
                <xsl:value-of select="imp1:Item/imp1:Description"/>
              </xsl:variable>
              <xsl:variable name="No_of_loops">  
                <xsl:value-of select="ceiling($Desc_Len_Var div '80')"/>
              </xsl:variable>
              
              <xsl:for-each select="(//node())[position() &lt;= $No_of_loops]">
                  <xsl:variable name="Position">  
                    <xsl:value-of select="position()"/>
                  </xsl:variable>
                   <xsl:variable name="Var3">
                    <xsl:value-of select="substring($Desc_Var,(($Position * 80) - 79),80)"/>
                  </xsl:variable>
                  <ns9:Loop-PID>
                    <ns9:Segment-PID>
                      <ns9:Element-349>
                        <xsl:value-of select='string("F")'/>
                      </ns9:Element-349>
                      <ns9:Element-352>
                        <!--<xsl:value-of select="imp1:Item/imp1:Description"/>-->
                        <xsl:value-of select="$Var3"/>
                      </ns9:Element-352>
                    </ns9:Segment-PID>
                  </ns9:Loop-PID>
              </xsl:for-each>
        
        <!-- ADDED AS ON 23 OCT "MEA SEGEMENT WITH THE IF CONDITION" -->
        <xsl:if test="/inp1:CustomProcessPO/ProcessPO/imp1:ApplicationArea/imp1:Sender/imp1:LogicalID ='LIEBERTNA'">
        <xsl:if test="imp1:Item/imp1:Specification/imp1:Property/imp1:NameValue != ''"> 
        <ns9:Segment-MEA>
          <ns9:Element-737>
            <xsl:value-of select='string("WT")'/>
          </ns9:Element-737>
          <ns9:Element-738>
            <xsl:value-of select='string("U")'/>
          </ns9:Element-738>
          <ns9:Element-739>
            <xsl:value-of select="imp1:Item/imp1:Specification/imp1:Property/imp1:NameValue"/>
          </ns9:Element-739>
          <ns9:Composite-C001>
            <ns9:Element-355>
              <xsl:value-of select="imp1:Item/imp1:Specification/imp1:Property/imp1:NameValue/@unitCode"/>
             <!--<xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","Target",imp1:Item/imp1:Specification/imp1:Property/imp1:NameValue/@unitCode,"EDI",concat(imp1:Item/imp1:Specification/imp1:Property/imp1:NameValue/@unitCode,&quot;Default&quot;))'/>-->
            </ns9:Element-355>
          </ns9:Composite-C001>
        </ns9:Segment-MEA> 
        </xsl:if>
        </xsl:if> 
        
     <!--   <xsl:if test='(imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[1] != "") and (imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[2] != "")'>
        <ns9:Segment-TC2>    
        <xsl:if test='imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[1]'>
            <ns9:Element-23>
              <xsl:value-of select='string("A")'/>
            </ns9:Element-23>
         </xsl:if>
          <xsl:if test='imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[2]'>
            <ns9:Element-22>
              <xsl:value-of select='string("Z")'/>
            </ns9:Element-22>
            </xsl:if>
        </ns9:Segment-TC2>
        </xsl:if> -->
        
        <xsl:if test='(imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[1] != "") and (imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[1]/@name = "HTS Code")'>
        <ns9:Segment-TC2>    
            <ns9:Element-23>
              <xsl:value-of select='string("A")'/>
            </ns9:Element-23>
            <ns9:Element-22>
              <xsl:value-of select='imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[1]'/>
            </ns9:Element-22>
         </ns9:Segment-TC2>
         </xsl:if>
         
        <xsl:if test='(imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[2] != "") and (imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[2]/@name = "Emerson Commodity Code")'>
        <ns9:Segment-TC2>    
            <ns9:Element-23>
              <xsl:value-of select='string("Z")'/>
            </ns9:Element-23>
            <ns9:Element-22>
              <xsl:value-of select='imp1:Item/imp1:Classification/imp1:Codes/imp1:Code[2]'/>
            </ns9:Element-22>
        </ns9:Segment-TC2>
        </xsl:if> 
        
        
        <xsl:if test='imp1:Item/imp1:HazardousMaterial/imp1:ID != ""'>
        <ns9:Segment-TD4>
            <ns9:Element-152>
              <xsl:value-of select='string("HAZ")'/>
            </ns9:Element-152>
            <ns9:Element-352>
              <xsl:value-of select="imp1:Item/imp1:HazardousMaterial/imp1:ID"/>
            </ns9:Element-352>
           </ns9:Segment-TD4>
            </xsl:if>
            
          <!--  <ns9:Loop-LDT>
                 <xsl:choose>     
                    <xsl:when test='imp1:PurchaseOrderLine/imp1:Note[1] != ""'> 
                     <ns9:Segment-MTX>
                        <ns9:Element-363>
                            <xsl:value-of select='string("ORI")'/>
                        </ns9:Element-363>
                        <ns9:Element-1551>
                             <xsl:value-of select='imp1:Note[1]'/>
                        </ns9:Element-1551>
                        </ns9:Segment-MTX>
                    </xsl:when>
                    <xsl:when test='imp1:PurchaseOrderLine/imp1:Note[2] != ""'>
                     <ns9:Segment-MTX>
                        <ns9:Element-363>
                            <xsl:value-of select='string("ORI")'/>
                        </ns9:Element-363>
                        <ns9:Element-1551_1>
                            <xsl:value-of select='imp1:Note[2]'/>
                        </ns9:Element-1551_1>
                    </ns9:Segment-MTX>
                    </xsl:when>
                </xsl:choose>
        </ns9:Loop-LDT>-->  
         <!-- ADDED If as on April-24- 2009-->
        <xsl:if test='imp1:Note != ""'> 
        <ns9:Loop-LDT>     
                    <xsl:if test='imp1:Note != ""'> 
                     <ns9:Segment-MTX>
                        <ns9:Element-363>
                            <xsl:value-of select='string("ORI")'/>
                        </ns9:Element-363>
                        <xsl:if test='imp1:Note[1] != ""'>
                        <ns9:Element-1551>
                             <xsl:value-of select='imp1:Note[1]'/>
                        </ns9:Element-1551>
                        </xsl:if>
                        <xsl:if test='imp1:Note[2] != ""'>
                        <ns9:Element-1551_1>
                            <xsl:value-of select='imp1:Note[2]'/>
                        </ns9:Element-1551_1>
                        </xsl:if>
                    </ns9:Segment-MTX>
                    </xsl:if>
        </ns9:Loop-LDT>
        </xsl:if>
         <!--SHIPTO--><!-- ADDED AS ON 16 OCT -->
        <xsl:for-each select="imp1:PurchaseOrderSchedule">
       <ns9:Loop-N1_2>
        <ns9:Segment-N1>
          <ns9:Element-98>
              <xsl:value-of select='string("ST")'/>
            </ns9:Element-98>
            <ns9:Element-93>
              <xsl:value-of select="substring(imp1:UserArea/imp1:ShipToParty/imp1:Name,1.0,60.0)"/>
            </ns9:Element-93>
            <ns9:Element-66>
              <xsl:value-of select='string("93")'/>
            </ns9:Element-66>
            <ns9:Element-67>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:PartyIDs/imp1:ID"/>
            </ns9:Element-67>
          </ns9:Segment-N1>
      <xsl:variable name="LENGTH_ST">  
                 <xsl:value-of select="string-length(imp1:UserArea/imp1:ShipToParty/imp1:Name)"/>
          </xsl:variable> 
            <xsl:if test="$LENGTH_ST > 60.0">
             <ns9:Segment-N2>
              <ns9:Element-93_1>
                 <xsl:value-of select="substring(imp1:UserArea/imp1:ShipToParty/imp1:Name,60.0)"/>
              </ns9:Element-93_1>
             </ns9:Segment-N2>
            </xsl:if>
             <!--Changed  AS ON 19 MAR  -->  
             <xsl:if test='(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineOne!="") or (imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineTwo != "")'>
            <ns9:Segment-N3>
             <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineOne) &lt;= 55)'>
            <ns9:Element-166>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineOne"/>
            </ns9:Element-166>
            </xsl:if>
            <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineOne) &gt; 55)'>
            <ns9:Element-166>
               <xsl:value-of select="concat(substring(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineOne,1,54),'+')"/>
            </ns9:Element-166>
            </xsl:if>
            <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineTwo) &lt;= 55)'>
            <ns9:Element-166_1>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineTwo"/>
            </ns9:Element-166_1>
            </xsl:if>
             <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineTwo) &gt; 55)'>
            <ns9:Element-166>
              <xsl:value-of select="concat(substring(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineTwo,1,54),'+')"/>
            </ns9:Element-166>
            </xsl:if>
          </ns9:Segment-N3> 
          </xsl:if>
          <!--Changed  AS ON 22-APR -->  
          <!--ADDED AS ON 16 OCT -->
                   <!--Changed  AS ON 19 MAR  -->  
            <xsl:if test='(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineThree!="") or (imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineFour != "")'>
              <ns9:Segment-N3>
              <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineThree) &lt;= 55)'>
                <ns9:Element-166>
                  <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineThree"/>
                </ns9:Element-166>
                </xsl:if>
                <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineThree) &gt; 55)'>
                <ns9:Element-166>
                 <xsl:value-of select="concat(substring(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineThree,1,54),'+')"/>
                </ns9:Element-166>
                </xsl:if>
                 <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineFour) &lt;= 55)'>
                <ns9:Element-166_1>
                  <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineFour"/>
                </ns9:Element-166_1>
                </xsl:if>
                <xsl:if test='(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineFour) &gt; 55)'>
                <ns9:Element-166_1>
                  <xsl:value-of select="concat(substring(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:LineFour,1,54),'+')"/>
                </ns9:Element-166_1>
                </xsl:if>
              </ns9:Segment-N3>
            </xsl:if>
           <!--Changed  AS ON 22-APR -->  
           <ns9:Segment-N4><!-- ADDED AS ON 23 OCT -->
            <ns9:Element-19>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CityName"/>
            </ns9:Element-19>
           <!-- <xsl:if test='((imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountryCode = "US") or (imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountryCode ="CA"))'>
              <ns9:Element-156>
                <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/>
              </ns9:Element-156>
            </xsl:if>--><!-- Removed on 18 MAR-->
            <ns9:Element-116>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:PostalCode"/>
            </ns9:Element-116>
            <ns9:Element-26>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountryCode"/>
            </ns9:Element-26>
            <xsl:if test ="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:ID !=''"> <!-- Added as on 3 Nov the "If" condition -->
            <ns9:Element-309>
              <xsl:value-of select="string(93.0)"/>
            </ns9:Element-309>
            <ns9:Element-310>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:ID"/>
            </ns9:Element-310>
            </xsl:if>
           <!-- <xsl:if test='((imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountryCode != "US") and (imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountryCode !="CA"))'>-->
              <!-- Changed as on 22-APR-->
                          
               <!-- Added choose when condition on April-24 2009 to convert contrydivision name  to  code-->
                <xsl:if test="(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode !='')">
             <xsl:choose>
              <xsl:when test="(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &lt;= 3)">
              <ns9:Element-1715>
              <!--Changed on April-22-->
               <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode",imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode)'/>
              <!--  <xsl:value-of select="imp1:Location/imp1:Address/imp1:CountrySubDivisionCode"/> -->
              </ns9:Element-1715>
              </xsl:when>
              <xsl:when test="(string-length(imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode) &gt; 3)">
              <ns9:Element-1715>
              <xsl:value-of select='orcl:lookup-dvm("Country Subdivisions","Target",imp1:UserArea/imp1:ShipToParty/imp1:Location/imp1:Address/imp1:CountrySubDivisionCode,"EDICode","ZZZ")'/> 
              
              </ns9:Element-1715>
          </xsl:when>
          </xsl:choose>
            </xsl:if>
          </ns9:Segment-N4>  
          <!--Added as on 2 DEC-->
          <xsl:if test='((imp1:Note[1] !="") and (imp1:Note[1]/@author = "Emerson Location Identifier"))'>
          <ns9:Segment-REF>
            <ns9:Element-128>
              <xsl:value-of select='string("4C")'/>
            </ns9:Element-128>
            <ns9:Element-127>
              <xsl:value-of select="imp1:Note[1]"/>
            </ns9:Element-127>
          </ns9:Segment-REF>
        </xsl:if>
        <xsl:if test='((imp1:Note[2] !="") and (imp1:Note[2]/@author = "Kanban Card Number"))'>
          <ns9:Segment-REF>
            <ns9:Element-128>
              <xsl:value-of select='string("KE")'/>
            </ns9:Element-128>
            <ns9:Element-127>
              <xsl:value-of select="imp1:Note[2]"/>
            </ns9:Element-127>
          </ns9:Segment-REF>
    </xsl:if>   
    
   <!-- <xsl:for-each select="imp1:UserArea/imp1:ShipToParty/imp1:Contact">-->
        <xsl:if test='((imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Name !="") or (imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[3]/imp1:DialNumber != "") or (imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[2]/imp1:DialNumber !="") or (imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[1]/imp1:URI != ""))'> 
        <ns9:Segment-PER>
            <ns9:Element-366>
              <xsl:value-of select='string("BD")'/>
            </ns9:Element-366>
            <xsl:if test='imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Name !=""'>
            <ns9:Element-93>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Name"/>
            </ns9:Element-93>
            </xsl:if>
            
            <xsl:if test="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[3]/imp1:DialNumber != ''"> 
            <ns9:Element-365>
              <xsl:value-of select='string("TE")'/>
            </ns9:Element-365>
            <ns9:Element-364>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[3]/imp1:DialNumber"/>
            </ns9:Element-364>
           </xsl:if> 
           
            <xsl:if test="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[2]/imp1:DialNumber !='' ">
            <ns9:Element-365_1>
              <xsl:value-of select='string("FX")'/>
            </ns9:Element-365_1>
            <ns9:Element-364_1>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[2]/imp1:DialNumber"/> 
            </ns9:Element-364_1>
           </xsl:if>
           
            <xsl:if test='imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[1]/imp1:URI != ""'>
            <ns9:Element-365_2>
              <xsl:value-of select='string("EM")'/>
            </ns9:Element-365_2>
            <ns9:Element-364_2>
              <xsl:value-of select="imp1:UserArea/imp1:ShipToParty/imp1:Contact[1]/imp1:Communication[1]/imp1:URI"/>
            </ns9:Element-364_2>
            </xsl:if>
          </ns9:Segment-PER>
        </xsl:if>
         
           <xsl:if test='imp1:UserArea/imp1:BuyerContact/imp1:Name !=""'>
            <ns9:Segment-PER>
             <ns9:Element-366>
              <xsl:value-of select='string("RQ")'/>
            </ns9:Element-366>
            <ns9:Element-93>
              <xsl:value-of select="imp1:UserArea/imp1:BuyerContact/imp1:Name"/>
            </ns9:Element-93>
            </ns9:Segment-PER>
           </xsl:if> 

        <ns9:Loop-SCH>
          <ns9:Segment-SCH>
            <ns9:Element-380_2>
              <xsl:value-of select="imp1:Quantity"/>
            </ns9:Element-380_2>
            <xsl:if test="imp1:Quantity/@unitCode !=''">
            <ns9:Element-355>
            
             <!-- <xsl:value-of select="imp1:Quantity/@unitCode"/>-->
             <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","Target",imp1:Quantity/@unitCode,"EDI",imp1:Quantity/@unitCode)'/>
            </ns9:Element-355>
            </xsl:if>
            <xsl:if test="imp1:Quantity/@unitCode =''">
            <ns9:Element-355>
               <xsl:value-of select="imp1:Quantity/@unitCode"/>
            </ns9:Element-355>
            </xsl:if>
            
            
            <!--<xsl:if test="imp1:RequiredDeliveryDateTime !=''">
            <ns9:Element-374_5>
              <xsl:value-of select="string('112')"/>
            </ns9:Element-374_5>
            <ns9:Element-373>
             <xsl:value-of select="concat(substring(imp1:RequiredDeliveryDateTime,1.0,4.0),substring(imp1:RequiredDeliveryDateTime,6.0,2.0),substring(imp1:RequiredDeliveryDateTime,9.0,2.0))"/> 
            </ns9:Element-373>
            </xsl:if>
            <xsl:if test="imp1:UserArea/imp1:RequestedShipDateTime !=''">
            <ns9:Element-374>
              <xsl:value-of select="string('010')"/>
            </ns9:Element-374>
            <ns9:Element-373_1>
             <xsl:value-of select="concat(substring(imp1:UserArea/imp1:RequestedShipDateTime,1.0,4.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,6.0,2.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,9.0,2.0))"/> 
            </ns9:Element-373_1>
            </xsl:if>-->
            
           <xsl:choose>
            <xsl:when test="imp1:RequiredDeliveryDateTime !=''">
            <ns9:Element-374_5>
              <xsl:value-of select="string('112')"/>
            </ns9:Element-374_5>
            <ns9:Element-373>
             <xsl:value-of select="concat(substring(imp1:RequiredDeliveryDateTime,1.0,4.0),substring(imp1:RequiredDeliveryDateTime,6.0,2.0),substring(imp1:RequiredDeliveryDateTime,9.0,2.0))"/> <!-- ADDED AS ON 29SEP -->
            </ns9:Element-373>
            </xsl:when>
            
            <xsl:when test="((imp1:RequiredDeliveryDateTime ='') and (imp1:UserArea/imp1:RequestedShipDateTime !=''))">
            <ns9:Element-374_5>
              <xsl:value-of select="string('112')"/>
            </ns9:Element-374_5>
            <ns9:Element-373>
             <xsl:value-of select="concat(substring(imp1:UserArea/imp1:RequestedShipDateTime,1.0,4.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,6.0,2.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,9.0,2.0))"/> <!-- ADDED AS ON 22 OCT -->
            </ns9:Element-373>
            </xsl:when>
            
            <xsl:when test="((imp1:RequiredDeliveryDateTime ='') and (imp1:UserArea/imp1:RequestedShipDateTime =''))">
            <ns9:Element-374_5>
              <xsl:value-of select="string('112')"/>
            </ns9:Element-374_5>
            <ns9:Element-373>
             <xsl:value-of select="concat(substring($Current_date,1.0,4.0),substring($Current_date,6.0,2.0),substring($Current_date,9.0,2.0))"/><!-- ADDED AS ON 22 OCT -->
            </ns9:Element-373>
            </xsl:when>
            <xsl:otherwise>
            <ns9:Element-374_5>
              <xsl:value-of select="string('112')"/>
            </ns9:Element-374_5>
            <ns9:Element-373>
             <xsl:value-of select="concat(substring($Current_date,1.0,4.0),substring($Current_date,6.0,2.0),substring($Current_date,9.0,2.0))"/><!-- ADDED AS ON 22 OCT -->
            </ns9:Element-373>
            </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="imp1:UserArea/imp1:RequestedShipDateTime !=''">
            <ns9:Element-374>
              <xsl:value-of select="string('010')"/>
            </ns9:Element-374>
            <ns9:Element-373_1>
             <xsl:value-of select="concat(substring(imp1:UserArea/imp1:RequestedShipDateTime,1.0,4.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,6.0,2.0),substring(imp1:UserArea/imp1:RequestedShipDateTime,9.0,2.0))"/> <!-- ADDED AS ON 22 OCT -->
            </ns9:Element-373_1>
            </xsl:if>
            
            <ns9:Element-350>
              <xsl:value-of select="imp1:LineNumber"/>
            </ns9:Element-350>
          </ns9:Segment-SCH>
        </ns9:Loop-SCH>
            </ns9:Loop-N1_2> 
          </xsl:for-each> <!-- ADDED AS ON 16 OCT -->     
         </xsl:for-each>
      </ns9:Loop-PO1> 
        <ns9:Loop-CTT> 
          <ns9:Segment-CTT>
            <ns9:Element-354>
              <xsl:value-of select="count(/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:PurchaseOrder/imp1:PurchaseOrderLine)"/>
            </ns9:Element-354>
          </ns9:Segment-CTT>
        </ns9:Loop-CTT>      
        <ns9:Segment-SE>
            <ns9:Element-96>
                <xsl:value-of select='string("#SegmentCount#")'/>
            </ns9:Element-96>
            <!--<ns9:Element-329>
                <xsl:value-of select="orcl:lookup-table('SC_MASTER_TRANSACTION','FLOW_ID_1',$flowID,'ST_CONTROL','jdbc:polite4:system/any@142.176.225.81:1531:OraESB')"/>
            </ns9:Element-329> -->
            <ns9:Element-329>
              <!--<xsl:value-of select="string('#ControlNumber#')"/>-->
              <xsl:value-of select="$SC_SeqNo"/>
            </ns9:Element-329>
        </ns9:Segment-SE>
      </xsl:for-each>  
       <!--<ns9:Segment-GE>
        <ns9:Element-97>
          <xsl:value-of select="count(/inp1:CustomProcessPO/ProcessPO/DataArea/imp1:PurchaseOrder)"/>
        </ns9:Element-97>
      </ns9:Segment-GE>-->
    </ns9:Transaction-850>
      <Message_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_id"/>
      </Message_id>
      <Message_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_type"/>
      </Message_type>
      <Message_standard>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_standard"/>
      </Message_standard>
      <Message_direction>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_direction"/>
      </Message_direction>
      <Transaction_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Transaction_type"/>
      </Transaction_type>
      <Transaction_subtype>
        <xsl:value-of select="/inp1:CustomProcessPO/Transaction_subtype"/>
      </Transaction_subtype>
      <Document_number>
        <xsl:value-of select="/inp1:CustomProcessPO/Document_number"/>
      </Document_number>
      <Flow_id_1>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_1"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_2"/>
      </Flow_id_2>
      <Sender_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_id"/>
      </Sender_id>
      <Sender_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_name"/>
      </Sender_name>
      <Sender_system_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_system_type"/>
      </Sender_system_type>
      <Party_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Party_name"/>
      </Party_name>
      <Party_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Party_id"/>
      </Party_id>
      <Party_site_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Party_site_id"/>
      </Party_site_id>
      <Party_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Party_type"/>
      </Party_type>
      <Protocol_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Protocol_type"/>
      </Protocol_type>
      <Protocol_address>
        <xsl:value-of select="/inp1:CustomProcessPO/Protocol_address"/>
      </Protocol_address>
      <Username>
        <xsl:value-of select="/inp1:CustomProcessPO/Username"/>
      </Username>
      <Password>
        <xsl:value-of select="/inp1:CustomProcessPO/Password"/>
      </Password>
      <File_name>
        <xsl:value-of select="/inp1:CustomProcessPO/File_name"/>
      </File_name>
      <Record_total>
        <xsl:value-of select="/inp1:CustomProcessPO/Record_total"/>
      </Record_total>
      <Send_on_fail>
        <xsl:value-of select="/inp1:CustomProcessPO/Send_on_fail"/>
      </Send_on_fail>
      <Division_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_name"/>
      </Division_name>
      <Division_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_format"/>
      </Division_format>
      <Trading_partner_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_name"/>
      </Trading_partner_1_name>
      <Trading_partner_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_format"/>
      </Trading_partner_1_format>
      <Trading_partner_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_from"/>
      </Trading_partner_1_date_from>
      <Trading_partner_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_to"/>
      </Trading_partner_1_date_to>
      <Trading_partner_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_name"/>
      </Trading_partner_2_name>
      <Trading_partner_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_format"/>
      </Trading_partner_2_format>
      <Trading_partner_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_from"/>
      </Trading_partner_2_date_from>
      <Trading_partner_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_to"/>
      </Trading_partner_2_date_to>
      <Trading_partner_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_name"/>
      </Trading_partner_3_name>
      <Trading_partner_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_format"/>
      </Trading_partner_3_format>
      <Trading_partner_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_from"/>
      </Trading_partner_3_date_from>
      <Trading_partner_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_to"/>
      </Trading_partner_3_date_to>
      <Logistics_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_name"/>
      </Logistics_1_name>
      <Logistics_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_format"/>
      </Logistics_1_format>
      <Logistics_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_from"/>
      </Logistics_1_date_from>
      <Logistics_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_to"/>
      </Logistics_1_date_to>
      <Logistics_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_name"/>
      </Logistics_2_name>
      <Logistics_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_format"/>
      </Logistics_2_format>
      <Logistics_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_from"/>
      </Logistics_2_date_from>
      <Logistics_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_to"/>
      </Logistics_2_date_to>
      <Logistics_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_name"/>
      </Logistics_3_name>
      <Logistics_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_format"/>
      </Logistics_3_format>
      <Logistics_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_from"/>
      </Logistics_3_date_from>
      <Logistics_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_to"/>
      </Logistics_3_date_to>
      <Compliance_result>
        <xsl:value-of select="/inp1:CustomProcessPO/Compliance_result"/>
      </Compliance_result>
      <Attribute1>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute1"/>
      </Attribute1>
      <Attribute2>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute2"/> 
         
      </Attribute2>
      <Attribute3>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute3"/>
      </Attribute3>
      <Attribute4>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute4"/>
      </Attribute4>
      <Attribute5>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute5"/>
      </Attribute5>
      <Attribute6>
      <xsl:value-of select="$SC_SeqNo"/>
        <!--<xsl:value-of select="/inp1:CustomProcessPO/Attribute6"/>-->
      </Attribute6>
      <Attribute7>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute7"/>
      </Attribute7>
      <Attribute8>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute8"/>
      </Attribute8>
      <Attribute9>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute9"/>
      </Attribute9>
      <Attribute10>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute10"/>
      </Attribute10>
    </inp1:CustomEDI850>
  </xsl:template>
</xsl:stylesheet>
