<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomOAGIS_7_2_RS.wsdl"/>
      <rootElement name="CustomProcess_PO_007" namespace="http://xmlns.emrsn.com/CustomProcess_PO_007"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETH_ENQJMS_ArchiveTransaction.wsdl"/>
      <rootElement name="RootElement" namespace="http://xmlns.emrsn.com/SC_Archive"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED MAR 18 14:42:27 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcess_PO_007"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_ENQJMS_ArchiveTransaction/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:imp1="http://xmlns.emrsn.com/SC_Archive"
                xmlns:ns2="http://xmlns.emrsn.com/CommonProcessPO_007"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                exclude-result-prefixes="xsl inp1 ns0 ns2 tns plt jca ns1 imp1 hdr bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <imp1:RootElement>
      <ScMasterTransaction>
        <Message_ID>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Message_id"/>
        </Message_ID>
        <flowId1>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Flow_id_1"/>
        </flowId1>
        <flowId2>
          <xsl:value-of select="ehdr:getInstanceID()"/>
        </flowId2>
        <messageDirection>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Message_direction"/>
        </messageDirection>
        <stage>
          <xsl:value-of select='string("Initial")'/>
        </stage>
        <businessDocumentNumber>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Document_number"/>
        </businessDocumentNumber>
        <senderGroup>
          <xsl:value-of select='orcl:lookup-dvm("GroupID","SenderID",/inp1:CustomProcess_PO_007/Party_site_id,"Group","ETH")'/>
        </senderGroup>
        <senderId>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Sender_id"/>
        </senderId>
        <senderName>
          <xsl:value-of select='orcl:lookup-dvm("GroupID","SenderID",/inp1:CustomProcess_PO_007/Party_site_id,"SenderName","ETH")'/>
        </senderName>
        <senderMessageStandard>
          <xsl:value-of select='concat(/inp1:CustomProcess_PO_007/Message_type,"_",/inp1:CustomProcess_PO_007/Message_standard,"_7_2")'/>
        </senderMessageStandard>
        <senderTransactionType>
            <xsl:value-of select='orcl:lookup-dvm("TransactionType","XMLType",/inp1:CustomProcess_PO_007/Transaction_subtype,"TransactionName","INVALID")'/>
        </senderTransactionType>
        <senderFeedType>
          <xsl:value-of select='string("XML")'/>
        </senderFeedType>
        <senderSystemType>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Sender_system_type"/>
        </senderSystemType>
        <senderFileDate>
          <xsl:value-of select='concat(/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:YEAR,"-",/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:MONTH,"-",/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:DAY)'/>
        </senderFileDate>
        <senderFileTime>
          <xsl:value-of select='concat(/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:HOUR,":",/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:MINUTE,":",/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:SECOND,".",/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:DATETIME/ns2:SUBSECOND)'/>
        </senderFileTime>
        <senderXmlEventKey>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:CNTROLAREA/ns2:SENDER/ns2:REFERENCEID"/>
        </senderXmlEventKey>
        <ethReceiveDate>
          <xsl:value-of select="xp20:current-date()"/>
        </ethReceiveDate>
        <ethReceiveTime>
          <xsl:value-of select="xp20:current-time()"/>
        </ethReceiveTime>
        <!--
        <attribute2>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Attribute5"/>
        </attribute2>
        -->
        <attribute3>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Attribute3"/>
        </attribute3>
      </ScMasterTransaction>
      <scDetailedTransaction>
        <transactionDate>
          <xsl:value-of select="xp20:current-date()"/>
        </transactionDate>
        <transactionType>
          <xsl:value-of select="string('ProcessPO_7_2')"/>
        </transactionType>
        <payload>
          <xsl:value-of select="orcl:get-content-as-string(/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007)"/>
        </payload>
        <businessDocumentID>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/ns2:PROCESS_PO_007/ns2:DATAAREA/ns2:PROCESS_PO/ns2:POORDERHDR/ns2:POID"/>
        </businessDocumentID>
        <source>
          <xsl:value-of select="/inp1:CustomProcess_PO_007/Attribute2"/>
        </source>
      </scDetailedTransaction>
    </imp1:RootElement>
  </xsl:template>
</xsl:stylesheet>
