<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomLiebertPO_RS.wsdl"/>
      <rootElement name="CustomLiebertPO" namespace="http://xmlns.emrsn.com/CustomLiebertPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomOAGIS_9_0_RS.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED FEB 25 13:29:06 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns5="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns7="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:ns1="http://xmlns.emrsn.com/LiebertPurchaseOrder"
                xmlns:inp1="http://xmlns.emrsn.com/CustomLiebertPurchaseOrder"
                xmlns:ns6="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ns9="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns3="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:exsl="http://exslt.org/common"
                xmlns:ns4="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:ns2="http://www.openapplications.org/oagis/9"
                xmlns:ns8="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns10="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                exclude-result-prefixes="xsl ns1 inp1 ns0 tns ns5 ns7 ns6 ns9 ns3 ns4 ns2 ns8 ns10 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns5:CustomProcessPO>
      <ProcessPO>
        <!-- For PROCESS PO => 00, For CHANGE PO => 05 -->
        <xsl:variable name="PO_TYPE" select="00"/>
                
        <xsl:attribute name="releaseID">
           <xsl:value-of select='string("0")'/>
        </xsl:attribute>

      <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA15">
        <xsl:if test='. = "P"'>
          <xsl:attribute name="systemEnvironmentCode">
            <xsl:value-of select='string("Production")'/>
          </xsl:attribute>
        </xsl:if>
      </xsl:for-each>
      <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA15">
        <xsl:if test='. = "T"'>
          <xsl:attribute name="systemEnvironmentCode">
            <xsl:value-of select='string("Test")'/>
          </xsl:attribute>
        </xsl:if>
      </xsl:for-each>
      <xsl:attribute name="languageCode">
        <xsl:value-of select='string("en-US")'/>
      </xsl:attribute>
      <ns2:ApplicationArea>
        <ns2:Sender>
          <ns2:LogicalID>
            <xsl:value-of select="normalize-space(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS02)"/>
          </ns2:LogicalID>
          <ns2:ComponentID>
            <xsl:value-of select='string("PURCHASING")'/>
          </ns2:ComponentID>
          <ns2:TaskID>
            <xsl:value-of select='string("POISSUE")'/>
          </ns2:TaskID>
          <!-- added as on 19 NOV -->
          <!--<xsl:if test="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA13 !='         '">-->
          <xsl:if test="normalize-space(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA13)!=''">
          <ns2:ReferenceID> 
            <xsl:value-of select="normalize-space(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA13)"/>
          </ns2:ReferenceID>
          </xsl:if>
          <!-- Added on 15 Apr 2009 -->
          <!--
          <ns2:ConfirmationCode>
            <xsl:value-of select="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA14"/>
          </ns2:ConfirmationCode>
          -->          
          <xsl:choose>
              <xsl:when test="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA14 ='0'">
                  <ns2:ConfirmationCode>
                    <xsl:value-of select="string('Never')"/>
                  </ns2:ConfirmationCode>
              </xsl:when>
              <xsl:when test="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA14 ='1'">
                  <ns2:ConfirmationCode>
                    <xsl:value-of select="string('OnError')"/>
                  </ns2:ConfirmationCode>
              </xsl:when>
              <xsl:when test="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA14 ='2'">
                  <ns2:ConfirmationCode>
                    <xsl:value-of select="string('Always')"/>
                  </ns2:ConfirmationCode>
              </xsl:when>
              <xsl:otherwise>
                  <ns2:ConfirmationCode>
                    <xsl:value-of select="/inp1:CustomLiebertPO/ns1:Root-Element/record/HDISA14"/>
                  </ns2:ConfirmationCode>
              </xsl:otherwise>
        </xsl:choose>
        <!-- Added on 15 Apr 2009 -->
        
        <ns2:AuthorizationID>
            <xsl:value-of select="normalize-space(/inp1:CustomLiebertPO/ns1:Root-Element/record/HD5REF03)"/> 
          </ns2:AuthorizationID>
        </ns2:Sender>

        <!--<xsl:if test='((/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS04 != "        ") and (/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS05 != "        "))'>-->
        <xsl:if test='((/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS04)!= "" and (/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS05)!= "")'>
            <ns2:CreationDateTime>
              <xsl:value-of select='concat(substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),1.0,4.0),"-",substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),5.0,2.0),"-",substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),7.0,2.0),"T",substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),9.0,2.0),":",substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),11.0,2.0),":",substring(concat(/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS04,/inp1:CustomLiebertPO/ns1:Root-Element/record/HDGS05),13.0,2.0))'/>
            </ns2:CreationDateTime>
        </xsl:if>
          
        <!--<xsl:if test='((/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS04 = "        ") and (/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS05 = "        "))'>-->
        <xsl:if test='((/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS04)= "" and (/inp1:CustomLiebertPO/ns1:Root-Element/record[1]/HDGS05)= "")'>
            <ns2:CreationDateTime>
          <xsl:value-of select="substring(xp20:current-dateTime(),1.0,19)"/>
        </ns2:CreationDateTime>
        </xsl:if>
        
      </ns2:ApplicationArea>
      <DataArea>
        <ns2:Process/>
       <!-- <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record">
          <xsl:variable name="var" select="HDBEG03"/>
          <xsl:variable name="nextNode"
                        select="following-sibling::record[1]"/>
          <xsl:if test="(string-length($nextNode/HDBEG03) = 0.0) or ($var != $nextNode/HDBEG03)">-->
          
          <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record">
          <xsl:variable name="type" select="HDBEG01"/>
          <xsl:variable name="var" select="HDBEG03"/>
          <xsl:variable name="nextNode"
                        select="following-sibling::record[1]"/>
          <xsl:if test="($type=$PO_TYPE)">
           <xsl:if test="(string-length($nextNode/HDBEG03) = 0.0) or ($var != $nextNode/HDBEG03)">
            <ns2:PurchaseOrder>
              <ns2:PurchaseOrderHeader>
                <ns2:DocumentID>
                  <ns2:ID>
                    <xsl:value-of select="normalize-space(HDBEG03)"/>
                  </ns2:ID>
                  <ns2:RevisionID>
                            <xsl:value-of select="normalize-space(HD1REF03)"/>
                  </ns2:RevisionID>
                  <!--
                  <xsl:choose>
                      <xsl:when test='normalize-space(HD1REF03) != ""'>
                        <ns2:RevisionID>
                            <xsl:value-of select="normalize-space(HD1REF03)"/>
                        </ns2:RevisionID>
                      </xsl:when>
                      <xsl:otherwise>
                        <ns2:RevisionID>
                            <xsl:value-of select='string("0")'/>
                        </ns2:RevisionID>
                      </xsl:otherwise>
                  </xsl:choose>
                  -->
                  <xsl:for-each select=".">
                    <xsl:if test='HDBEG02 = "SA"'>
                      <ns2:VariationID>
                        <xsl:value-of select='string("STANDARD")'/>
                      </ns2:VariationID>
                    </xsl:if>
                  </xsl:for-each>
                  <xsl:for-each select=".">
                    <xsl:if test='HDBEG02 = "BK"'>
                      <ns2:VariationID>
                        <xsl:value-of select='string("BLANKET")'/>
                      </ns2:VariationID>
                    </xsl:if>
                  </xsl:for-each>
                </ns2:DocumentID>
                
                <!--<xsl:if test='HDBEG05 != "        "'>-->
                <xsl:if test='normalize-space(HDBEG05) != ""'>
                  <ns2:DocumentDateTime>
                    <xsl:value-of select='concat(substring(HDBEG05,1.0,4.0),"-",substring(HDBEG05,5.0,2.0),"-",substring(HDBEG05,7.0,2.0))'/>
                  </ns2:DocumentDateTime>
                </xsl:if>
                
                <xsl:if test='normalize-space(HDBEG05) = ""'>
                  <ns2:DocumentDateTime>
                  <xsl:value-of select="substring(xp20:current-dateTime(),1.0,10)"/>
                </ns2:DocumentDateTime>
                </xsl:if>
                
                <ns2:Description>
                  <xsl:value-of select="normalize-space(HD6REF03)"/>
                </ns2:Description>
                <xsl:for-each select=".">
                  <ns2:Note>
                    <xsl:value-of select="normalize-space(HD1MTX02)"/>
                  </ns2:Note>
                </xsl:for-each>
                <xsl:for-each select=".">
                  <ns2:Note>
                    <xsl:value-of select="normalize-space(HD1MTX03)"/>
                  </ns2:Note>
                </xsl:for-each>
                <ns2:SupplierParty>
                  <ns2:PartyIDs>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD1N104)"/>
                    </ns2:ID>
                  </ns2:PartyIDs>
                  <ns2:Name>
                    <xsl:value-of select="normalize-space(concat(HD1N102,HD1N201))"/>
                  </ns2:Name>
                  <ns2:Location>
                  <xsl:choose>     <!--ADDED AS ON 2 FEB 2009-->
                  <xsl:when test="normalize-space(HD1N406) !=''">
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD1N406)"/>
                    </ns2:ID>
                    </xsl:when>
                    <xsl:otherwise>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD1N104)"/>
                    </ns2:ID>
                    </xsl:otherwise>
                    </xsl:choose>
                    <ns2:Address>
                      <ns2:LineOne>
                        <xsl:value-of select="normalize-space(HD1N301)"/>
                      </ns2:LineOne>
                      <ns2:LineTwo>
                        <xsl:value-of select="normalize-space(HD1N302)"/>
                      </ns2:LineTwo>
                      <ns2:LineThree>
                        <xsl:value-of select="normalize-space(HD1N303)"/>
                      </ns2:LineThree>
                      <ns2:LineFour>
                       <xsl:value-of select="normalize-space(HD1N304)"/>
                      </ns2:LineFour>
                      <ns2:CityName>
                        <xsl:value-of select="normalize-space(HD1N401)"/>
                      </ns2:CityName>
                      <xsl:for-each select=".">
                        <!--<xsl:if test='HD1N402 != ""'>-->
                          <xsl:if test='normalize-space(HD1N402) != ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD1N402)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <xsl:for-each select=".">
                       <!-- <xsl:if test='HD1N402 = ""'>-->
                        <xsl:if test='normalize-space(HD1N402) = ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD1N407)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <ns2:CountryCode>
                        <xsl:value-of select="normalize-space(HD1N404)"/>
                      </ns2:CountryCode>
                      <ns2:PostalCode>
                        <xsl:value-of select="normalize-space(HD1N403)"/>
                      </ns2:PostalCode>
                    </ns2:Address>
                  </ns2:Location>
                  <ns2:CustomerServiceContact>
                    <ns2:Name>
                      <xsl:value-of select="normalize-space(HD4PER02)"/>
                    </ns2:Name>
                    
                    <ns2:Communication>
                      <ns2:ChannelCode>
                        <xsl:value-of select='string("EMAIL")'/>
                      </ns2:ChannelCode>
                      <ns2:URI>
                        <xsl:value-of select="normalize-space(HD4PER08)"/>
                      </ns2:URI>
                    </ns2:Communication>
                    
                    <ns2:Communication>
                      <ns2:ChannelCode>
                        <xsl:value-of select='string("FAX")'/>
                      </ns2:ChannelCode>
                      <xsl:for-each select=".">
                        <ns2:DialNumber>
                          <xsl:value-of select="normalize-space(HD4PER06)"/>
                        </ns2:DialNumber>
                      </xsl:for-each>
                      </ns2:Communication>
                    
                    <ns2:Communication>
                      <ns2:ChannelCode>
                        <xsl:value-of select='string("TELEPHONE")'/>
                      </ns2:ChannelCode>
                      <xsl:for-each select=".">
                        <ns2:DialNumber>
                          <xsl:value-of select="normalize-space(HD4PER04)"/>
                        </ns2:DialNumber>
                      </xsl:for-each>
                      </ns2:Communication>
                      
                      
                    
                  </ns2:CustomerServiceContact>
                </ns2:SupplierParty>
                <ns2:ContractReference>
                  <ns2:DocumentID>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HDBEG06)"/>
                    </ns2:ID>
                  </ns2:DocumentID>
             <!--     <ns2:ReleaseNumber>
                    <xsl:value-of select="normalize-space(HDBEG04)"/>
                  </ns2:ReleaseNumber>-->
                </ns2:ContractReference>
                <ns2:ExtendedAmount>
                    <xsl:attribute name="currencyID">
                      <xsl:value-of select="HDCUR02"/>
                    </xsl:attribute>
                    <xsl:variable name="ExtAmnt">
                      <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record">
                        <xsl:if test="($var = HDBEG03)">
                          <QtyPrice>
                            <xsl:value-of select="normalize-space(LN1PO102) * normalize-space(LN1PO104)"/>
                          </QtyPrice>
                        </xsl:if>
                      </xsl:for-each>
                    </xsl:variable>
                    <xsl:value-of select="sum(exsl:node-set($ExtAmnt)/QtyPrice)"/>
                  </ns2:ExtendedAmount>                
        <!--        <xsl:for-each select=".">
                  <xsl:variable name="var" select="HDBEG03"/>
                  <xsl:variable name="nextNode"
                                select="following-sibling::record[1]"/>
                  <xsl:if test="(string-length($nextNode/HDBEG03) = 0.0) or ($var != $nextNode/HDBEG03)">
                    <xsl:for-each select="LN1PO102">
                      <ns2:ExtendedAmount>
                        <xsl:value-of select="sum(preceding-sibling::extamount1/@value)"/>
                         <xsl:value-of select="sum((LN1PO102 * LN1PO104)+$extamount)"/>
                        <xsl:variable name="extamount1">
                          <xsl:value-of select="(LN1PO102 * LN1PO104)"/>
                        </xsl:variable>
                      </ns2:ExtendedAmount>
                      <p><xsl:value-of select="sum(preceding-sibling::sibling/@value)" /></p>
                    </xsl:for-each>
                  </xsl:if>
                </xsl:for-each>-->
                
                <ns2:BillToParty>
                  <ns2:Name>
                    <xsl:value-of select="normalize-space(concat(HD4N102,HD4N201))"/>
                  </ns2:Name>
                  <ns2:Location>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD4N406)"/>
                    </ns2:ID>
                    <ns2:Address>
                      <ns2:LineOne>
                        <xsl:value-of select="normalize-space(HD4N301)"/>
                      </ns2:LineOne>
                      <ns2:LineTwo>
                        <xsl:value-of select="normalize-space(HD4N302)"/>
                      </ns2:LineTwo>
                      <ns2:LineThree>
                        <xsl:value-of select="normalize-space(HD4N303)"/>
                      </ns2:LineThree>
                      <ns2:LineFour>
                        <xsl:value-of select="normalize-space(HD4N304)"/>
                      </ns2:LineFour>
                      <ns2:CityName>
                        <xsl:value-of select="normalize-space(HD4N401)"/>
                      </ns2:CityName>
                      <xsl:for-each select=".">
                        <xsl:if test='HD4N402 != ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD4N402)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <xsl:for-each select=".">
                        <xsl:if test='HD4N402 = ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD4N407)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <ns2:CountryCode>
                        <xsl:value-of select="normalize-space(HD4N404)"/>
                      </ns2:CountryCode>
                      <ns2:PostalCode>
                        <xsl:value-of select="normalize-space(HD4N403)"/>
                      </ns2:PostalCode>
                    </ns2:Address>
                  </ns2:Location>
                  <ns2:BuyerContact>
                    <ns2:Name>
                      <xsl:value-of select="normalize-space(HD1PER02)"/>
                    </ns2:Name>
                    
                     <ns2:Communication>
                     <ns2:ChannelCode>
                        <xsl:value-of select='string("EMAIL")'/>
                      </ns2:ChannelCode>
                      <ns2:URI>
                        <xsl:value-of select="normalize-space(HD1PER08)"/>
                      </ns2:URI>
                    </ns2:Communication>
                    
                   <ns2:Communication>
                      <ns2:ChannelCode>
                        <xsl:value-of select='string("FAX")'/>
                      </ns2:ChannelCode>
                      <xsl:for-each select=".">
                        <ns2:DialNumber>
                          <xsl:value-of select="normalize-space(HD1PER06)"/>
                        </ns2:DialNumber>
                      </xsl:for-each>
                      </ns2:Communication>
                    
                    <ns2:Communication>
                      <ns2:ChannelCode>
                        <xsl:value-of select='string("TELEPHONE")'/>
                      </ns2:ChannelCode>
                      <xsl:for-each select=".">
                        <ns2:DialNumber>
                          <xsl:value-of select="normalize-space(HD1PER04)"/>
                        </ns2:DialNumber>
                      </xsl:for-each>
                    </ns2:Communication>
                  </ns2:BuyerContact>
                </ns2:BillToParty>
                <ns2:CarrierParty>
                  <ns2:Name>
                    <xsl:value-of select="normalize-space(concat(HD6N102,HD6N201))"/>
                  </ns2:Name>
                </ns2:CarrierParty>
                <ns2:TransportationTerm>
                  <ns2:PlaceOfOwnershipTransferLocation>
                    <ns2:Name>
                      <xsl:value-of select="normalize-space(HD1FOB07)"/>
                    </ns2:Name>
                  </ns2:PlaceOfOwnershipTransferLocation>
                  <ns2:FreightTermCode>
                    <xsl:value-of select="normalize-space(HD1FOB03)"/>
                  </ns2:FreightTermCode>
                </ns2:TransportationTerm>
                <ns2:PaymentTerm>
                  <ns2:Term>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD1ITD12)"/>
                    </ns2:ID>
                  </ns2:Term>
                </ns2:PaymentTerm>
                <ns2:BuyerParty>
                  <ns2:Name>
                    <xsl:value-of select="normalize-space(concat(HD5N102,HD5N201))"/>
                  </ns2:Name>
                  <ns2:Location>
                    <ns2:ID>
                      <xsl:value-of select="normalize-space(HD5N406)"/>
                    </ns2:ID>
                    <ns2:Address>
                      <ns2:LineOne>
                        <xsl:value-of select="normalize-space(HD5N301)"/>
                      </ns2:LineOne>
                      <ns2:LineTwo>
                        <xsl:value-of select="normalize-space(HD5N302)"/>
                      </ns2:LineTwo>
                      <ns2:LineThree>
                        <xsl:value-of select="normalize-space(HD5N303)"/>
                      </ns2:LineThree>
                      <ns2:LineFour>
                        <xsl:value-of select="normalize-space(HD5N304)"/>
                      </ns2:LineFour>
                      <ns2:CityName>
                        <xsl:value-of select="normalize-space(HD5N401)"/>
                      </ns2:CityName>
                      <xsl:for-each select=".">
                        <xsl:if test='HD5N402 != ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD5N402)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <xsl:for-each select=".">
                        <xsl:if test='HD5N402 = ""'>
                          <ns2:CountrySubDivisionCode>
                            <xsl:value-of select="normalize-space(HD5N407)"/>
                          </ns2:CountrySubDivisionCode>
                        </xsl:if>
                      </xsl:for-each>
                      <ns2:CountryCode>
                        <xsl:value-of select="normalize-space(HD5N404)"/>
                      </ns2:CountryCode>
                      <ns2:PostalCode>
                        <xsl:value-of select="normalize-space(HD5N403)"/>
                      </ns2:PostalCode>
                    </ns2:Address>
                  </ns2:Location>
                </ns2:BuyerParty>
                
                
                <ns2:ReleaseNumber>
                            <xsl:value-of select="normalize-space(HDBEG04)"/>
                </ns2:ReleaseNumber>
                
                <ns2:UserArea>
                  <!--<xsl:if test='HDCUR03 != "          "'>-->
                  <xsl:if test='normalize-space(HDCUR03) != ""'>
                  <ns2:CurrencyExchangeRate>
                    <ns2:RateNumeric>
                      <xsl:value-of select="normalize-space(HDCUR03)"/>
                    </ns2:RateNumeric>                    
                  
                      <!--<xsl:if test='(HDCUR08 != "        ") and (HDCUR09 != "        ")'>-->
                        <xsl:if test='normalize-space(HDCUR08) != "" and normalize-space(HDCUR09) != ""'>
                        <ns2:SetDateTime>
                          <xsl:value-of select='concat(substring(concat(HDCUR08,HDCUR09),1.0,4.0),"-",substring(concat(HDCUR08,HDCUR09),5.0,2.0),"-",substring(concat(HDCUR08,HDCUR09),7.0,2.0),"T",substring(concat(HDCUR08,HDCUR09),9.0,2.0),":",substring(concat(HDCUR08,HDCUR09),11.0,2.0),":",substring(concat(HDCUR08,HDCUR09),13.0,2.0))'/>
                        </ns2:SetDateTime>
                      </xsl:if>                
                   
                      <!--<xsl:if test='(HDCUR08 = "        ") and (HDCUR09 = "        ")'>-->
                      <xsl:if test='normalize-space(HDCUR08) = "" and normalize-space(HDCUR09) = ""'>
                        <ns2:SetDateTime>
                         <xsl:value-of select="substring(xp20:current-dateTime(),1.0,19)"/>
                        </ns2:SetDateTime>
                      </xsl:if>
                  </ns2:CurrencyExchangeRate>
                  </xsl:if>
                  
                  <ns2:ActionExpression>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = "Y"'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("AcknowledgementRequired")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = "AC"'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("AcknowledgementRequired")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = "N"'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("DoNotAcknowledge")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = "NA"'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("DoNotAcknowledge")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = "  "'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("DoNotAcknowledge")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <xsl:if test='HDBEG07 = ""'>
                        <xsl:attribute name="actionCode">
                          <xsl:value-of select='string("DoNotAcknowledge")'/>
                        </xsl:attribute>
                      </xsl:if>
                    </xsl:for-each>
                  </ns2:ActionExpression>
                </ns2:UserArea>
              </ns2:PurchaseOrderHeader>
              <xsl:for-each select="/inp1:CustomLiebertPO/ns1:Root-Element/record">
              <xsl:sort select="normalize-space(LN1PO101)" data-type="number"/>
              <xsl:if test="($var = HDBEG03) and ($type=HDBEG01)">                
                  <ns2:PurchaseOrderLine>
                    <ns2:LineNumber>
                      <xsl:value-of select="normalize-space(LN1PO101)"/>
                    </ns2:LineNumber>
                    <xsl:for-each select=".">
                      <ns2:Note>
                        <xsl:value-of select="normalize-space(LN1MTX02)"/>
                      </ns2:Note>
                    </xsl:for-each>
                    <xsl:for-each select=".">
                      <ns2:Note>
                        <xsl:value-of select="normalize-space(LN1MTX03)"/>
                      </ns2:Note>
                    </xsl:for-each>
                    <ns2:Item>
                      <ns2:ItemID>
                        <ns2:ID>
                          <xsl:value-of select="normalize-space(LN1PO107)"/>
                        </ns2:ID>
                        <ns2:RevisionID>
                          <xsl:value-of select="normalize-space(LN1PO111)"/>
                        </ns2:RevisionID>
                      </ns2:ItemID>
                      <ns2:SupplierItemID>
                        <ns2:ID>
                          <xsl:value-of select="normalize-space(LN1PO109)"/>
                        </ns2:ID>
                      </ns2:SupplierItemID>
                      <ns2:Description>
                        <xsl:value-of select="normalize-space(LN1PID05)"/>
                      </ns2:Description>
                      
                     <!-- <ns2:Classification>
                        <xsl:for-each select=".">
		         <xsl:attribute name="type">
		          <xsl:value-of select='string("HTS Code")'/>
		         </xsl:attribute>
                        </xsl:for-each>
                          <xsl:value-of select='string("Emerson Commodity Code")'/>
                        <xsl:for-each select=".">
                         <ns2:Codes>
                            <ns2:Code>
                             <xsl:attribute name="sequence">
                               <xsl:value-of select='string("1")'/>
                             </xsl:attribute>
                            <xsl:value-of select="normalize-space(LN1TC202)"/>
                            </ns2:Code>
                         </ns2:Codes>
                         </xsl:for-each>
                          <xsl:for-each select=".">
                           <ns2:Codes>
                             <ns2:Code>
                               <xsl:attribute name="sequence">
                                 <xsl:value-of select='string("1")'/>
                               </xsl:attribute>
                               <xsl:value-of select="normalize-space(LN1TC206)"/>
                             </ns2:Code>
                           </ns2:Codes>
                         </xsl:for-each>
                      </ns2:Classification>-->
                      <ns2:Classification>
                        <ns2:Codes>
                         <ns2:Code>
		           <xsl:attribute name="name">
		            <xsl:value-of select='string("HTS Code")'/>
		           </xsl:attribute>
                           <xsl:attribute name="sequence">
                            <xsl:value-of select='string("1")'/>
                           </xsl:attribute>
                           <xsl:value-of select="normalize-space(LN1TC202)"/>
                           </ns2:Code>
                           <ns2:Code>
                          <xsl:attribute name="name">
		            <xsl:value-of select='string("Emerson Commodity Code")'/>
		           </xsl:attribute>
                           <xsl:attribute name="sequence">
                            <xsl:value-of select='string("2")'/>
                           </xsl:attribute>
                           <xsl:value-of select="normalize-space(LN1TC206)"/>
                          </ns2:Code>
                          </ns2:Codes>
                          </ns2:Classification>
                      <ns2:Specification>
		                              <ns2:Property>
		                                <ns2:NameValue>
		                                  <xsl:attribute name="name">
		                                    <xsl:value-of select='string("Weight")'/>
		                                  </xsl:attribute>
		                                  <xsl:attribute name="unitCode">
		                                    <xsl:value-of select="normalize-space(LN1MEA04)"/>
		                                  </xsl:attribute>
		                                  <xsl:value-of select="normalize-space(LN1MEA03)"/>
		                                </ns2:NameValue>
		                              </ns2:Property>
                      </ns2:Specification>
                      
                      
                      <ns2:HazardousMaterial>
                        <ns2:ID>
                          <xsl:value-of select="normalize-space(LN1TD402)"/>
                        </ns2:ID>
                      </ns2:HazardousMaterial>
                    </ns2:Item>
                     <ns2:Quantity>
                      <xsl:attribute name="unitCode">
                        <xsl:value-of select="normalize-space(LN1PO103)"/>
                      </xsl:attribute>
                      <xsl:value-of select="string(number(normalize-space(LN1PO102)))"/>
                    </ns2:Quantity>
                    <ns2:UnitPrice>
                      <ns2:Amount>
                        <xsl:attribute name="currencyID">
                          <xsl:value-of select="normalize-space(HDCUR02)"/>
                        </xsl:attribute>
                       <!-- <xsl:value-of select="string(number(normalize-space(LN1PO104)))"/>-->
                       <!--Changed as on 3 DEC-->
                       <xsl:variable name="amount">  
                           <xsl:value-of select="string(number(normalize-space(LN1PO104)))"/>
                       </xsl:variable> 
                       <xsl:choose>
                       <xsl:when test="starts-with($amount,'0')">
                         <xsl:value-of select="substring-after($amount,'0')"/>
                       </xsl:when>
                       <xsl:otherwise>
                         <xsl:value-of select="$amount"/>
                       </xsl:otherwise>
                       </xsl:choose>
            
                      </ns2:Amount>
                      <ns2:PerQuantity>
                        <xsl:attribute name="unitCode">
                         <xsl:value-of select="normalize-space(LN1PO103)"/>
                        </xsl:attribute>
                        <xsl:value-of select="string('1')"/>
                      </ns2:PerQuantity>
                    </ns2:UnitPrice>
                    <ns2:PurchaseOrderSchedule>
                      <ns2:LineNumber>
                        <xsl:value-of select="normalize-space(LN1SCH12)"/>
                      </ns2:LineNumber>
                      <!--Added on 2 DEC-->
                      <xsl:for-each select="LN3REF02">
                      <ns2:Note>
                      <xsl:attribute name="author">
                        <xsl:value-of select='string("Emerson Location Identifier")'/>
                      </xsl:attribute>
                       <xsl:value-of select="normalize-space(.)"/>          
                    </ns2:Note>
                    </xsl:for-each>
                    <xsl:for-each select="LN3REF04">
                      <ns2:Note>
                      <xsl:attribute name="author">
                        <xsl:value-of select='string("Kanban Card Number")'/>
                      </xsl:attribute>
                        <xsl:value-of select="normalize-space(.)"/>
                      </ns2:Note>
                     </xsl:for-each>
                     <ns2:Quantity>
                      <xsl:attribute name="unitCode">
		            <xsl:value-of select="normalize-space(LN1SCH02)"/>
                      </xsl:attribute>
                        <xsl:value-of select="string(number(normalize-space(LN1SCH01)))"/>
                      </ns2:Quantity>
                      
                      <!--<xsl:if test='LN1SCH06 != "        "'>-->
                      <xsl:if test='normalize-space(LN1SCH06) != ""'>
                        <ns2:RequiredDeliveryDateTime>
                          <xsl:value-of select='normalize-space(concat(substring(LN1SCH06,1.0,4.0),"-",substring(LN1SCH06,5.0,2.0),"-",substring(LN1SCH06,7.0,2.0)))'/>
                        </ns2:RequiredDeliveryDateTime>
                      </xsl:if>
                      
                      <!--<xsl:if test='LN1SCH06 = "        "'>-->
                       <xsl:if test='normalize-space(LN1SCH06) = ""'>
                        <ns2:RequiredDeliveryDateTime>
                          <xsl:value-of select="substring(xp20:current-dateTime(),1.0,19)"/>
                        </ns2:RequiredDeliveryDateTime>
                      </xsl:if>
                      
            <!--  <xsl:for-each select="LN3REF02">
                      <ns2:Note>
                      <xsl:attribute name="author">
                        <xsl:value-of select='string("Emerson Location Identifier")'/>
                      </xsl:attribute>
                       <xsl:value-of select="normalize-space(.)"/>          
                    </ns2:Note>
                    </xsl:for-each>
                    
              <xsl:for-each select="LN3REF04">
                      <ns2:Note>
                      <xsl:attribute name="author">
                        <xsl:value-of select='string("Kanban Card Number")'/>
                      </xsl:attribute>
                        <xsl:value-of select="normalize-space(.)"/>
                      </ns2:Note>
                     </xsl:for-each>-->


                      <ns2:UserArea>
                        <!--     <ns2:RequestedShipDateTime>
                          <xsl:value-of select="LN1SCH09"/>
                        </ns2:RequestedShipDateTime>-->
                        
                        <!--<xsl:if test='LN1SCH09 != "        "'>-->
                        <xsl:if test='normalize-space(LN1SCH09) != ""'>
                          <ns2:RequestedShipDateTime>
                            <xsl:value-of select='normalize-space(concat(substring(LN1SCH09,1.0,4.0),"-",substring(LN1SCH09,5.0,2.0),"-",substring(LN1SCH09,7.0,2.0)))'/>
                          </ns2:RequestedShipDateTime>                                               
                        </xsl:if>
                        
                         <!--<xsl:if test='LN1SCH09 = "        "'> 
                          <ns2:RequestedShipDateTime>
                            <xsl:value-of select="''"/>
                          </ns2:RequestedShipDateTime>
                        </xsl:if>-->
                        <ns2:BuyerContact> <!--Added on 18 MAR-->
                          <ns2:Name>
                            <xsl:value-of select="LN5PER02"/>
                          </ns2:Name>
                          <ns2:JobTitle> 
                           <xsl:value-of select='string("Buyer (or Requestor) Name")'/>
                          </ns2:JobTitle>
                        </ns2:BuyerContact>                        
                        
                        <ns2:ShipToParty>
                          <ns2:PartyIDs>
                            <ns2:ID>
                              <xsl:value-of select="normalize-space(LN3N104)"/>
                            </ns2:ID>
                          </ns2:PartyIDs>
                          <ns2:Name>
                            <xsl:value-of select="normalize-space(concat(LN3N102,LN3N201))"/>
                          </ns2:Name>
                          <ns2:Location>
                            <ns2:ID>
                              <xsl:value-of select="normalize-space(LN3N406)"/>
                            </ns2:ID>
                            <ns2:Address>
                              <ns2:LineOne>
                                <xsl:value-of select="normalize-space(LN3N301)"/>
                              </ns2:LineOne>
                              <ns2:LineTwo>
                                <xsl:value-of select="normalize-space(LN3N302)"/>
                              </ns2:LineTwo>
                              <ns2:LineThree>
                                <xsl:value-of select="normalize-space(LN3N303)"/>
                              </ns2:LineThree>
                              <ns2:LineFour>
                                <xsl:value-of select="normalize-space(LN3N304)"/>
                              </ns2:LineFour>
                              <ns2:CityName>
                                <xsl:value-of select="normalize-space(LN3N401)"/>
                              </ns2:CityName>
                              <xsl:for-each select=".">
                                <xsl:if test='LN3N402 != ""'>
                                  <ns2:CountrySubDivisionCode>
                                    <xsl:value-of select="normalize-space(LN3N402)"/>
                                  </ns2:CountrySubDivisionCode>
                                </xsl:if>
                              </xsl:for-each>
                              <xsl:for-each select=".">
                                <xsl:if test='LN3N402 = ""'>
                                  <ns2:CountrySubDivisionCode>
                                    <xsl:value-of select="normalize-space(LN3N407)"/>
                                  </ns2:CountrySubDivisionCode>
                                </xsl:if>
                              </xsl:for-each>
                              <ns2:CountryCode>
                                <xsl:value-of select="normalize-space(LN3N404)"/>
                              </ns2:CountryCode>
                              <ns2:PostalCode>
                                <xsl:value-of select="normalize-space(LN3N403)"/>
                              </ns2:PostalCode>
                            </ns2:Address>
                          </ns2:Location>
                          <ns2:Contact>
                            <xsl:attribute name="type">                  
                              <xsl:value-of select='string("Contact1")'/>
                            </xsl:attribute>   
                            <ns2:Name>
                              <xsl:value-of select="normalize-space(LN4PER02)"/>
                            </ns2:Name>
                             <ns2:Communication>
                             <ns2:ChannelCode>
                                <xsl:value-of select='string("EMAIL")'/>
                              </ns2:ChannelCode>
                              <ns2:URI>
                                <xsl:value-of select="normalize-space(LN4PER08)"/>
                              </ns2:URI>
                            </ns2:Communication>
                            
                            <ns2:Communication>
                              <ns2:ChannelCode>
                                <xsl:value-of select='string("FAX")'/>
                              </ns2:ChannelCode>
                              <xsl:for-each select=".">
                                <ns2:DialNumber>
                                  <xsl:value-of select="normalize-space(LN4PER06)"/>
                                </ns2:DialNumber>
                              </xsl:for-each>
                            </ns2:Communication>
                            
                            <ns2:Communication>
                              <ns2:ChannelCode>
                                <xsl:value-of select='string("TELEPHONE")'/>
                              </ns2:ChannelCode>
                              <xsl:for-each select=".">
                                <ns2:DialNumber>
                                  <xsl:value-of select="normalize-space(LN4PER04)"/>
                                </ns2:DialNumber>
                              </xsl:for-each>
                              </ns2:Communication>
                            
                          </ns2:Contact>
                        </ns2:ShipToParty>
                      </ns2:UserArea>
                    </ns2:PurchaseOrderSchedule>
                  </ns2:PurchaseOrderLine>
                </xsl:if>
              </xsl:for-each>
            </ns2:PurchaseOrder>
          </xsl:if>
          </xsl:if>
        </xsl:for-each>
      </DataArea>
      </ProcessPO>
      <Message_id>
        <xsl:value-of select="/inp1:CustomLiebertPO/Message_id"/>
      </Message_id>
      <Message_direction>
        <xsl:value-of select="/inp1:CustomLiebertPO/Message_direction"/>
      </Message_direction>
      <Sender_Document_number>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Document_number"/>
      </Sender_Document_number>
      <Sender_Message_type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Message_type"/>
      </Sender_Message_type>
      <Sender_Message_standard>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Message_standard"/>
      </Sender_Message_standard>
      <Sender_Transaction_type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Transaction_type"/>
      </Sender_Transaction_type>
      <Sender_Transaction_subtype>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Transaction_subtype"/>
      </Sender_Transaction_subtype>
      <Sender_System_type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_System_type"/>
      </Sender_System_type>
      <Sender_Id>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Id"/>
      </Sender_Id>
      <Sender_Site_Id>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Site_Id"/>
      </Sender_Site_Id>
      <Sender_Name>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Name"/>
      </Sender_Name>
      <Sender_Type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Sender_Type"/>
      </Sender_Type>
      <Receiver_System_type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Receiver_System_type"/>
      </Receiver_System_type>
      <Receiver_Id>
        <xsl:value-of select="/inp1:CustomLiebertPO/Receiver_Id"/>
      </Receiver_Id>
      <Receiver_Site_id>
        <xsl:value-of select="/inp1:CustomLiebertPO/Receiver_Site_id"/>
      </Receiver_Site_id>
      <Receiver_Name>
        <xsl:value-of select="/inp1:CustomLiebertPO/Receiver_Name"/>
      </Receiver_Name>
      <Receiver_type>
        <xsl:value-of select="/inp1:CustomLiebertPO/Receiver_type"/>
      </Receiver_type>
      <File_name>
        <xsl:value-of select="/inp1:CustomLiebertPO/File_name"/>
      </File_name>
      <Record_total>
        <xsl:value-of select="/inp1:CustomLiebertPO/Record_total"/>
      </Record_total>
      <Record_number>
        <xsl:value-of select="/inp1:CustomLiebertPO/Record_number"/>
      </Record_number>
      <Flow_id_1>
        <xsl:value-of select="/inp1:CustomLiebertPO/Flow_id_1"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="ehdr:getInstanceID()"/>
      </Flow_id_2>
      <Flow_id_3>
        <xsl:value-of select="/inp1:CustomLiebertPO/Flow_id_3"/>
      </Flow_id_3>
      <Attribute1>
        <xsl:value-of select="/inp1:CustomLiebertPO/Attribute1"/>
      </Attribute1>
      <Attribute2>
        <xsl:value-of select="/inp1:CustomLiebertPO/Attribute2"/>
      </Attribute2>
      <Attribute3>
        <xsl:value-of select="/inp1:CustomLiebertPO/Attribute3"/>
      </Attribute3>
      <Attribute4>
        <xsl:value-of select="/inp1:CustomLiebertPO/Attribute4"/>
      </Attribute4>
      <Attribute5>
        <xsl:value-of select="/inp1:CustomLiebertPO/Attribute5"/>
      </Attribute5>
    </ns5:CustomProcessPO>
  </xsl:template>
</xsl:stylesheet>
