<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomEDI_5020_850_RS.wsdl"/>
      <rootElement name="CustomEDI850" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomOAGIS_9_0_RS.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED MAR 04 12:54:35 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"
                xmlns:ns5="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns7="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ns4="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns1="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns9="urn:oracle:integration:b2b:DCC1FCD2811C47748DF43A39F735F4F0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:imp1="http://www.openapplications.org/oagis/9"
                xmlns:ns6="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns8="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                exclude-result-prefixes="xsl imp1 inp1 ns0 ns9 tns ns5 ns7 ns4 ns1 ns2 ns3 ns6 ns8 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <inp1:CustomProcessPO>
      <ProcessPO>
        <xsl:attribute name="versionID">
        <xsl:value-of select='string("9.0")'/>
      </xsl:attribute>
      <xsl:attribute name="releaseID">
        <xsl:value-of select='string("007")'/>
      </xsl:attribute>
         <xsl:attribute name="languageCode">
           <xsl:value-of select='string("en-US")'/>
         </xsl:attribute>
         <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[15.0] = "T")'>
            <xsl:attribute name="systemEnvironmentCode">
             <xsl:value-of select='string("Test")'/>
           </xsl:attribute>
         </xsl:if>
         <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[15.0] = "P")'>
           <xsl:attribute name="systemEnvironmentCode">
               <xsl:value-of select='string("Production")'/>
           </xsl:attribute>
         </xsl:if>
      <imp1:ApplicationArea>
        <imp1:Sender>
        <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/@Name = "Group")'>
          <imp1:LogicalID>
            <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[2.0]"/>
          </imp1:LogicalID>
          </xsl:if><!--Added on 05 FEB-->
          <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[1.0] = "PO")'>
          <imp1:ComponentID>
            <xsl:value-of select='string("PURCHASING")'/>
          </imp1:ComponentID>
           </xsl:if><!--Added on 05 FEB-->
           <xsl:if test="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-ST/ns9:Element-143 = 850">
          <imp1:TaskID>
            <xsl:value-of select='string("POISSUE")'/>
          </imp1:TaskID>
          </xsl:if>
          <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/@Name = "Interchange"'>
            <imp1:ReferenceID>
              <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[13.0]"/>
            </imp1:ReferenceID>
          </xsl:if><!--Added on 05 FEB-->
          <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/@Name = "Interchange") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[14.0]=0)'>
          <imp1:ConfirmationCode>
            <xsl:value-of select="string('Never')"/>
          </imp1:ConfirmationCode>
          </xsl:if><!--Added on 05 FEB-->
          <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/@Name = "Interchange") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[14.0]=1)'>
          <imp1:ConfirmationCode>
            <xsl:value-of select="string('OnError')"/>
          </imp1:ConfirmationCode>
          </xsl:if><!--Added on 05 FEB-->
          <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/@Name = "Interchange") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Property[14.0]=2)'>
          <imp1:ConfirmationCode>
            <xsl:value-of select="string('Always')"/>
          </imp1:ConfirmationCode>
          </xsl:if><!--Added on 05 FEB-->
           <xsl:if test="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[1]/ns9:Element-128 = 06">
            <imp1:AuthorizationID>
              <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[1]/ns9:Element-352"/>
            </imp1:AuthorizationID>
          </xsl:if>
           </imp1:Sender>
          <xsl:if test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/@Name = "Group")'>
          <imp1:CreationDateTime>
            <xsl:value-of select="concat(substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[4.0],1.0,4.0),'-',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[4.0],5.0,2.0),'-',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[4.0],7.0,2.0),'T',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[5.0],1.0,2.0),':',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[5.0],3.0,2.0),':',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Internal-Properties/ns9:Data-Structure/ns9:Data-Structure/ns9:Property[5.0],5.0,2.0),string('+00:00'))"/>                                                   
          </imp1:CreationDateTime>
          </xsl:if><!--Added on 05 FEB-->  
      </imp1:ApplicationArea>
      <DataArea>
	<imp1:Process/>
        <imp1:PurchaseOrder>
          <imp1:PurchaseOrderHeader>
            <imp1:DocumentID>
              <imp1:ID>
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-324"/>
              </imp1:ID>
              <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[2]/ns9:Element-128 = "PP"'>
                <imp1:RevisionID>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[2]/ns9:Element-352"/>
                </imp1:RevisionID>
              </xsl:if>
              <xsl:choose>
                <xsl:when test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-92 = "SA"'>
                  <imp1:VariationID>
                    <xsl:value-of select='string("STANDARD")'/>
                  </imp1:VariationID>
                </xsl:when>
                <xsl:when test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-92 = "BK"'>
                  <imp1:VariationID>
                    <xsl:value-of select='string("BLANKET")'/>
                  </imp1:VariationID>
                </xsl:when>
              </xsl:choose>
            </imp1:DocumentID>
            <imp1:DocumentDateTime>
              <xsl:value-of select='concat(substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-373,1.0,4.0),"-",substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-373,5.0,2.0),"-",substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-373,7.0,2.0),"T",string("00"),":",string("00"),":",string("00"),"+",string("00:00"))'/>
            </imp1:DocumentDateTime>
            <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[3]/ns9:Element-128 = "K6"'>
              <imp1:Description>
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-REF[3]/ns9:Element-352"/>
              </imp1:Description>
            </xsl:if>
           <!-- <xsl:choose>
              <xsl:when test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-LDT/ns9:Segment-MTX/ns9:Element-363 = "OTH"'>
                <imp1:Note>
                  <xsl:attribute name="author">
                    <xsl:value-of select='string("1")'/>
                  </xsl:attribute>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-LDT/ns9:Segment-MTX/ns9:Element-1551"/>
                </imp1:Note>
              </xsl:when>
              <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-LDT/ns9:Segment-MTX/ns9:Element-1551 = "OTH") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-LDT/ns9:Segment-MTX/ns9:Element-1551_1 != "")'>
                <imp1:Note>
                  <xsl:attribute name="author">
                    <xsl:value-of select='string("2")'/>
                  </xsl:attribute>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-LDT/ns9:Segment-MTX/ns9:Element-1551_1"/>
                </imp1:Note>
              </xsl:when>
            </xsl:choose>-->
            
            
             <xsl:choose>
              <xsl:when test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N9/ns9:Segment-MTX/ns9:Element-363 = "OTH"'>
                <imp1:Note>
                  <xsl:attribute name="author">
                    <xsl:value-of select='string("1")'/>
                  </xsl:attribute>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N9/ns9:Segment-MTX/ns9:Element-1551"/>
                </imp1:Note>
              </xsl:when>
              </xsl:choose>
              <xsl:choose>
              <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N9/ns9:Segment-MTX/ns9:Element-363 = "OTH") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N9/ns9:Segment-MTX/ns9:Element-1551_1 != "")'>
                <imp1:Note>
                  <xsl:attribute name="author">
                    <xsl:value-of select='string("2")'/>
                  </xsl:attribute>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N9/ns9:Segment-MTX/ns9:Element-1551_1"/>
                </imp1:Note>
              </xsl:when>
            </xsl:choose>
         
            <imp1:SupplierParty>
              <imp1:PartyIDs>
                <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN"'>
                  <imp1:ID>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-67"/>
                  </imp1:ID>
                </xsl:if>
              </imp1:PartyIDs>
              <xsl:if test="ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = 'VN'">
              <xsl:choose>
                <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N2/ns9:Element-93_1 != "")'>
                  <imp1:Name>
                    <xsl:value-of select="concat(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-93,' ',/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N2/ns9:Element-93_1)"/>
                  </imp1:Name>
                </xsl:when>
                 <xsl:otherwise>
                  <imp1:Name>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-93"/>
                  </imp1:Name>
                </xsl:otherwise>
              </xsl:choose>
              </xsl:if>
              <imp1:Location>
                <xsl:choose>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-310 != "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-310"/>
                    </imp1:ID>
                  </xsl:when>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-310 = "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-67"/>
                    </imp1:ID>
                  </xsl:when>
                </xsl:choose>
                <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN"'>
                  <imp1:Address>
                    <imp1:LineOne>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N3[1.0]/ns9:Element-166"/>
                    </imp1:LineOne>
                    <imp1:LineTwo>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N3[1.0]/ns9:Element-166_1"/>
                    </imp1:LineTwo>
                    <imp1:LineThree>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N3[2.0]/ns9:Element-166"/>
                    </imp1:LineThree>
                    <imp1:LineFour>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N3[2.0]/ns9:Element-166_1"/>
                    </imp1:LineFour>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN"'>
                      <imp1:CityName>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-19"/>
                      </imp1:CityName>
                    </xsl:if>
                    <xsl:choose>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-26 = "US") or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-26 = "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-156"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-26 != "US") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-26 != "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-1715"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                    </xsl:choose>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN"'>
                      <imp1:CountryCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-26"/>
                      </imp1:CountryCode>
                    </xsl:if>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN"'>
                      <imp1:PostalCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N4/ns9:Element-116"/>
                      </imp1:PostalCode>
                    </xsl:if>
                  </imp1:Address>
                </xsl:if>
              </imp1:Location>
              <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-N1/ns9:Element-98 = "VN" and /inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-PER !=""'>
                <imp1:CustomerServiceContact>
                  <imp1:Name>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-PER/ns9:Element-93"/>
                  </imp1:Name>
                  <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("EMAIL")'/>
                    </imp1:ChannelCode>
                    <imp1:URI>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-PER/ns9:Element-364_2"/>
                    </imp1:URI>
                  </imp1:Communication>
                  <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("FAX")'/>
                    </imp1:ChannelCode>
                    <imp1:DialNumber>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-PER/ns9:Element-364_1"/>
                    </imp1:DialNumber>
                  </imp1:Communication>
                  <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("TELEPHONE")'/>
                    </imp1:ChannelCode>
                    <imp1:DialNumber>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[1.0]/ns9:Segment-PER/ns9:Element-364"/>
                    </imp1:DialNumber>
                  </imp1:Communication>
                </imp1:CustomerServiceContact>
              </xsl:if>
            </imp1:SupplierParty>
   
            <imp1:ContractReference>
              <imp1:DocumentID>
                <imp1:ID>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-367"/>
                </imp1:ID>
              </imp1:DocumentID>
            </imp1:ContractReference>
            
            
            
            <imp1:ExtendedAmount>
              <xsl:attribute name="currencyID">
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-100"/>
              </xsl:attribute>
              <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-PO1/ns9:Segment-PO1/ns9:Element-380 * /inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-PO1/ns9:Segment-PO1/ns9:Element-212"/>
            </imp1:ExtendedAmount>
            
          <!-- <imp1:ExtendedAmount>
              <xsl:attribute name="currencyID">
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-100"/>
              </xsl:attribute>
              <xsl:for-each select="(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-PO1)[position()] &lt;= count(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-PO1)">
                <xsl:value-of select="position()"/>
              <xsl:value-of select="sum(ns9:Segment-PO1/ns9:Element-380 * ns9:Segment-PO1/ns9:Element-212)"/>
              </xsl:for-each>
            </imp1:ExtendedAmount>-->
            
            
            
            
            <!--<imp1:TransportationTerm>
              <imp1:PlaceOfOwnershipTransferLocation>
                <imp1:Name>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-FOB/ns9:Element-352_1"/>
                </imp1:Name>
              </imp1:PlaceOfOwnershipTransferLocation>
              <imp1:FreightTermCode>
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-FOB/ns9:Element-352"/>
              </imp1:FreightTermCode>
            </imp1:TransportationTerm>-->
            
            <imp1:BillToParty>
            <xsl:if test="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = &quot;BT&quot;">
              <xsl:choose>
                <xsl:when test="(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = &quot;BT&quot;) and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N2/ns9:Element-93_1 != '')">
                  <imp1:Name>
                    <xsl:value-of select="concat(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-93,' ',/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N2/ns9:Element-93_1)"/>
                  </imp1:Name>
                </xsl:when>
                 <xsl:otherwise>
                  <imp1:Name>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-93"/>
                  </imp1:Name>
                </xsl:otherwise>
              </xsl:choose>
              </xsl:if>
              <imp1:Location>
                <xsl:choose>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-310 != "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-310"/>
                    </imp1:ID>
                  </xsl:when>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-310 = "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-67"/>
                    </imp1:ID>
                  </xsl:when>
                </xsl:choose>
                <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT"'>
                  <imp1:Address>
                    <imp1:LineOne>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N3[1.0]/ns9:Element-166[1.0]"/>
                    </imp1:LineOne>
                    <imp1:LineTwo>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N3[1.0]/ns9:Element-166_1[1.0]"/>
                    </imp1:LineTwo>
                    <imp1:LineThree>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N3[2.0]/ns9:Element-166"/>
                    </imp1:LineThree>
                    <imp1:LineFour>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N3[2.0]/ns9:Element-166_1"/>
                    </imp1:LineFour>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT"'>
                      <imp1:CityName>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-19"/>
                      </imp1:CityName>
                    </xsl:if>
                    <xsl:choose>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-26 = "US") or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-26 = "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-156"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-26 != "US") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-26 != "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-1715"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                    </xsl:choose>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT"'>
                      <imp1:CountryCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-26"/>
                      </imp1:CountryCode>
                    </xsl:if>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT"'>
                      <imp1:PostalCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N4/ns9:Element-116"/>
                      </imp1:PostalCode>
                    </xsl:if>
                  </imp1:Address>
                </xsl:if>
              </imp1:Location>
                <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-N1/ns9:Element-98 = "BT"'>
                <imp1:BuyerContact>
                  <imp1:Name>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-PER/ns9:Element-93"/>
                  </imp1:Name>
                  <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("EMAIL")'/>
                    </imp1:ChannelCode>
                    <imp1:URI>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-PER/ns9:Element-364_2"/>
                    </imp1:URI>
                  </imp1:Communication>
                   <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("FAX")'/>
                    </imp1:ChannelCode>
                    <imp1:DialNumber>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-PER/ns9:Element-364_1"/>
                    </imp1:DialNumber>
                  </imp1:Communication>
                   <imp1:Communication>
                    <imp1:ChannelCode>
                      <xsl:value-of select='string("TELEPHONE")'/>
                    </imp1:ChannelCode>
                    <imp1:DialNumber>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[3.0]/ns9:Segment-PER/ns9:Element-364"/>
                    </imp1:DialNumber>
                  </imp1:Communication>
                </imp1:BuyerContact>
              </xsl:if>
            </imp1:BillToParty>

              <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N1/ns9:Element-98 = "CA"'>
              <imp1:CarrierParty>
                <xsl:choose>
                  <xsl:when test="(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N1/ns9:Element-98 = &quot;CA&quot;) and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N2/ns9:Element-93_1 != '')">
                    <imp1:Name>
                      <xsl:value-of select="concat(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N1/ns9:Element-93,' ',/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N2/ns9:Element-93_1)"/>
                    </imp1:Name>
                  </xsl:when>
                     <xsl:otherwise>
                    <imp1:Name>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[4.0]/ns9:Segment-N1/ns9:Element-93"/>
                    </imp1:Name>
                  </xsl:otherwise>
                </xsl:choose>
              </imp1:CarrierParty>
            </xsl:if>
            <imp1:TransportationTerm>
              <imp1:PlaceOfOwnershipTransferLocation>
                <imp1:Name>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-FOB/ns9:Element-352_1"/>
                </imp1:Name>
              </imp1:PlaceOfOwnershipTransferLocation>
              <imp1:FreightTermCode>
                <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-FOB/ns9:Element-352"/>
              </imp1:FreightTermCode>
            </imp1:TransportationTerm>
            
            <imp1:PaymentTerm>
              <imp1:Term>
                <imp1:ID>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-ITD/ns9:Element-352"/>
                </imp1:ID>
              </imp1:Term>
            </imp1:PaymentTerm>
            
            <xsl:if test="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = &quot;SO&quot;">
            <imp1:BuyerParty>
              <xsl:choose>
                <xsl:when test="(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = &quot;SO&quot;) and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N2/ns9:Element-93_1 != '')">
                  <imp1:Name>
                    <xsl:value-of select="concat(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-93,' ',/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N2/ns9:Element-93_1)"/>
                  </imp1:Name>
                </xsl:when>
                 <xsl:otherwise>
                  <imp1:Name>
                    <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-93"/>
                  </imp1:Name>
                </xsl:otherwise>
              </xsl:choose>
                <imp1:Location>
                <xsl:choose>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-310 != "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-310"/>
                    </imp1:ID>
                  </xsl:when>
                  <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-310 = "")'>
                    <imp1:ID>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-67"/>
                    </imp1:ID>
                  </xsl:when>
                </xsl:choose>
                <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO"'>
                  <imp1:Address>
                    <imp1:LineOne>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N3[1.0]/ns9:Element-166[1.0]"/>
                    </imp1:LineOne>
                    <imp1:LineTwo>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N3[1.0]/ns9:Element-166_1[1.0]"/>
                    </imp1:LineTwo>
                    <imp1:LineThree>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N3[2.0]/ns9:Element-166"/>
                    </imp1:LineThree>
                    <imp1:LineFour>
                      <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N3[2.0]/ns9:Element-166_1"/>
                    </imp1:LineFour>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO"'>
                      <imp1:CityName>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-19"/>
                      </imp1:CityName>
                    </xsl:if>
                    <xsl:choose>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-26 = "US") or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-26 = "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-156"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                      <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-26 != "US") and (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-26 != "CA")'>
                        <imp1:CountrySubDivisionCode>
                          <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-1715"/>
                        </imp1:CountrySubDivisionCode>
                      </xsl:when>
                    </xsl:choose>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO"'>
                      <imp1:CountryCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-26"/>
                      </imp1:CountryCode>
                    </xsl:if>
                    <xsl:if test='/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N1/ns9:Element-98 = "SO"'>
                      <imp1:PostalCode>
                        <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-N1[2.0]/ns9:Segment-N4/ns9:Element-116"/>
                      </imp1:PostalCode>
                    </xsl:if>
                  </imp1:Address>
                </xsl:if>
              </imp1:Location>
            </imp1:BuyerParty>
            </xsl:if>
  
            <imp1:ReleaseNumber>
              <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-328"/>
            </imp1:ReleaseNumber>
            
            
            <imp1:UserArea>
              <imp1:CurrencyExchangeRate>
                <imp1:RateNumeric>
                  <xsl:value-of select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-280"/>
                </imp1:RateNumeric>
                <imp1:SetDateTime>
                      <xsl:value-of select="concat(substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-373_1,1.0,4.0),'-',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-373_1,5.0,2.0),'-',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-373_1,7.0,2.0),'T',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-337,1.0,2.0),':',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-337,3.0,2.0),':',substring(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-CUR/ns9:Element-337,5.0,4.0),string('+00:00'))"/>
                </imp1:SetDateTime>
              </imp1:CurrencyExchangeRate>
               <xsl:choose>
                <xsl:when test='(/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-587 = "Y") or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-587 = "AC")'>
                  <imp1:ActionExpression>
                    <xsl:attribute name="actionCode">
                      <xsl:value-of select='string("AcknowledgementRequired")'/>
                    </xsl:attribute>
                  </imp1:ActionExpression>
                </xsl:when>
                <xsl:when test='((/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-587 = "N") or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-587 = "NA")) or (/inp1:CustomEDI850/ns9:Transaction-850/ns9:Segment-BEG/ns9:Element-587 = "")'>
                  <imp1:ActionExpression>
                    <xsl:attribute name="actionCode">
                      <xsl:value-of select='string("DoNotAcknowledge")'/>
                    </xsl:attribute>
                  </imp1:ActionExpression>
                </xsl:when>
              </xsl:choose>
            </imp1:UserArea>
          </imp1:PurchaseOrderHeader>
          
          
          <!--POLINE-->
          
        <xsl:for-each select="/inp1:CustomEDI850/ns9:Transaction-850/ns9:Loop-PO1">
        <xsl:sort select="ns9:Segment-PO1/ns9:Element-350" data-type="number"/>
             <imp1:PurchaseOrderLine>
              <imp1:LineNumber>
                <xsl:value-of select="ns9:Segment-PO1/ns9:Element-350"/>
              </imp1:LineNumber>
              <xsl:choose>
                <xsl:when test="(ns9:Segment-MTX/ns9:Element-363 = 'ORI') and (ns9:Segment-MTX/ns9:Element-1551 != '')">
                  <imp1:Note>
                    <xsl:value-of select="ns9:Segment-MTX/ns9:Element-1551"/>
                  </imp1:Note>
                </xsl:when>
                </xsl:choose>
                <xsl:choose>
                <xsl:when test="(ns9:Segment-MTX/ns9:Element-363 = 'ORI') and (ns9:Segment-MTX/ns9:Element-1551_1 != '')">
                  <imp1:Note>
                    <xsl:value-of select="ns9:Segment-MTX/ns9:Element-1551_1"/>
                  </imp1:Note>
                </xsl:when>
              </xsl:choose>
              <imp1:Item>
                <imp1:ItemID>
                  <imp1:ID>
                    <xsl:value-of select="ns9:Segment-PO1/ns9:Element-234_1"/>
                  </imp1:ID>
                  <imp1:RevisionID>
                    <xsl:value-of select="ns9:Segment-PO1/ns9:Element-234_3"/>
                  </imp1:RevisionID>
                </imp1:ItemID>
                <imp1:SupplierItemID>
                  <imp1:ID>
                    <xsl:value-of select="ns9:Segment-PO1/ns9:Element-234_2"/>
                  </imp1:ID>
                </imp1:SupplierItemID>
                <imp1:Description>
                <xsl:for-each select="ns9:Loop-PID"><!--ADDED ON 6 MAR-->
                  <xsl:value-of select="ns9:Segment-PID/ns9:Element-352"/>
                  </xsl:for-each>
                </imp1:Description>

                    <imp1:Classification>
                      <imp1:Codes>
                        <xsl:if test='ns9:Segment-TC2[2]/ns9:Element-23 = "A"'>
                        <imp1:Code>
                          <xsl:attribute name="sequence">
                            <xsl:value-of select='string("1")'/>
                          </xsl:attribute>
                          <xsl:attribute name="name">
                            <xsl:value-of select='string("HTS Code")'/>
                          </xsl:attribute>
                          <xsl:value-of select="ns9:Segment-TC2[2]/ns9:Element-22"/>
                        </imp1:Code>
                        </xsl:if>
                         <xsl:if test='ns9:Segment-TC2[1]/ns9:Element-23 = "Z"'>
                        <imp1:Code>
                          <xsl:attribute name="sequence">
                            <xsl:value-of select='string("2")'/>
                          </xsl:attribute>
                          <xsl:attribute name="name">
                            <xsl:value-of select='string("Emerson Commodity Code")'/>
                          </xsl:attribute>
                          <xsl:value-of select="ns9:Segment-TC2[1]/ns9:Element-22"/>
                        </imp1:Code>
                        </xsl:if>
                      </imp1:Codes>
                    </imp1:Classification>  
             
                  
                  
                  
              <!--  <imp1:Specification>
                  <imp1:Property>
                    <imp1:NameValue>
                    <xsl:attribute name="name">
                        <xsl:value-of select='string("Weight")'/>
                      </xsl:attribute>
                    <xsl:attribute name="unitCode">
                          <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","EDI",ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355,"UOM",concat(ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355,&quot;COMPLIANCE_ERROR&quot;))'/>
                    </xsl:attribute>
                    <xsl:value-of select="ns9:Loop-PID/ns9:Segment-MEA/ns9:Element-739"/>
                  </imp1:NameValue>
                  </imp1:Property>
                </imp1:Specification>-->
                
               <xsl:if test="ns9:Loop-PID/ns9:Segment-MEA/ns9:Element-73 !=''">  <!--ADDED ON 6 MAR-->
                <Specification>
                  <Property>
                    <NameValue>
                    <xsl:attribute name="name">
                        <xsl:value-of select='string("Weight")'/>
                      </xsl:attribute>
                      <xsl:if test="ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355 !=''">
                    <xsl:attribute name="unitCode">
                          <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","EDI",ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355,"UOM",concat(ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355,&quot;COMPLIANCE_ERROR&quot;))'/>
                    </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355 =''">
                    <xsl:attribute name="unitCode">
                          <xsl:value-of select='ns9:Loop-PID/ns9:Segment-MEA/ns9:Composite-C001/ns9:Element-355'/>
                    </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns9:Loop-PID/ns9:Segment-MEA/ns9:Element-739"/>
                  </NameValue>
                  </Property>
                </Specification>
                </xsl:if>

                
                
                
                
                <imp1:HazardousMaterial>
                  <imp1:ID>
                    <xsl:value-of select="ns9:Segment-TD4/ns9:Element-352"/>
                  </imp1:ID>
                </imp1:HazardousMaterial>
              </imp1:Item>
              <imp1:Quantity>
                <xsl:attribute name="unitCode">
                  <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","EDI",ns9:Segment-PO1/ns9:Element-355_1,"UOM",concat(ns9:Segment-PO1/ns9:Element-355_1,&quot;COMPLIANCE_ERROR&quot;))'/>
                </xsl:attribute>
                <xsl:value-of select="ns9:Segment-PO1/ns9:Element-380"/>
              </imp1:Quantity>
              <imp1:UnitPrice>
                <imp1:Amount>
                  <xsl:attribute name="currencyID">
                    <xsl:value-of select="../ns9:Segment-CUR/ns9:Element-100"/>
                  </xsl:attribute>
                  <xsl:value-of select="ns9:Segment-PO1/ns9:Element-212"/>
                </imp1:Amount>
                <imp1:PerQuantity>
                  <xsl:attribute name="unitCode">
                    <!--<xsl:value-of select="ns9:Segment-PO1/ns9:Element-355_1"/>-->
                    <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","EDI",ns9:Segment-PO1/ns9:Element-355_1,"UOM",concat(ns9:Segment-PO1/ns9:Element-355_1,&quot;COMPLIANCE_ERROR&quot;))'/>
                  </xsl:attribute>
                  <xsl:value-of select='string("1")'/>
                </imp1:PerQuantity>
              </imp1:UnitPrice>
                <xsl:for-each select="ns9:Loop-N1_2">   
                <imp1:PurchaseOrderSchedule>
                  <imp1:LineNumber>
                    <xsl:value-of select="ns9:Segment-SCH/ns9:Element-350"/>
                  </imp1:LineNumber>
                  
                  <xsl:choose>
                    <xsl:when test='ns9:Segment-REF[1]/ns9:Element-128 = "4C"'>
                      <imp1:Note>
                        <xsl:attribute name="author">
                          <xsl:value-of select='string("Emerson Location Identifier")'/>
                        </xsl:attribute>
                        <xsl:value-of select="ns9:Segment-REF[1]/ns9:Element-127"/>
                      </imp1:Note>
                    </xsl:when>
                    </xsl:choose>
                    <xsl:choose>
                   <xsl:when test='ns9:Segment-REF[2]/ns9:Element-128 = "KE"'>
                      <imp1:Note>
                        <xsl:attribute name="author">
                          <xsl:value-of select='string("Kanban Card Number")'/>
                        </xsl:attribute>
                        <xsl:value-of select="ns9:Segment-REF[2]/ns9:Element-127"/>
                      </imp1:Note>
                    </xsl:when>
                    </xsl:choose>
                   
                    
                  <imp1:Quantity>
                    <xsl:attribute name="unitCode">
                      <!--<xsl:value-of select="ns9:Segment-SCH/ns9:Element-355"/>-->
                      <xsl:value-of select='orcl:lookup-dvm("UnitOfMeasure","EDI",ns9:Segment-SCH/ns9:Element-355,"UOM",concat(ns9:Segment-SCH/ns9:Element-355,&quot;COMPLIANCE_ERROR&quot;))'/>
                    </xsl:attribute>
                    <xsl:value-of select="ns9:Segment-SCH/ns9:Element-380_2"/>
                  </imp1:Quantity>
                  <imp1:RequiredDeliveryDateTime>
                    <!--<xsl:value-of select="ns9:Segment-SCH/ns9:Element-373"/>-->
                    <xsl:value-of select="concat(substring(ns9:Segment-SCH/ns9:Element-373,1,4),'-',substring(ns9:Segment-SCH/ns9:Element-373,5,2),'-',substring(ns9:Segment-SCH/ns9:Element-373,7,2))"/>
                  </imp1:RequiredDeliveryDateTime>
                  <imp1:UserArea>
                    <imp1:RequestedShipDateTime>
                      <xsl:value-of select="concat(substring(ns9:Segment-SCH/ns9:Element-373_1,1,4),'-',substring(ns9:Segment-SCH/ns9:Element-373_1,5,2),'-',substring(ns9:Segment-SCH/ns9:Element-373_1,7,2))"/>
                    </imp1:RequestedShipDateTime>
                    <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                      <imp1:ShipToParty>
                        <imp1:PartyIDs>
                        <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                         <imp1:ID>
                            <xsl:value-of select="ns9:Segment-N1/ns9:Element-67"/>
                        </imp1:ID>
                       </xsl:if>
                      </imp1:PartyIDs>
                       <xsl:choose>
                          <xsl:when test="(ns9:Segment-N1/ns9:Element-98 = &quot;ST&quot;) and (ns9:Segment-N2/ns9:Element-93_1 != '')">
                            <imp1:Name>
                              <xsl:value-of select="concat(ns9:Segment-N1/ns9:Element-93,' ',ns9:Segment-N2/ns9:Element-93_1)"/>
                            </imp1:Name>
                          </xsl:when>
                             <xsl:otherwise>
                            <imp1:Name>
                              <xsl:value-of select="ns9:Segment-N1/ns9:Element-93"/>
                            </imp1:Name>
                          </xsl:otherwise>
                          </xsl:choose>
                          <imp1:Location>
                            <xsl:choose>
                              <xsl:when test='(ns9:Segment-N1/ns9:Element-98 = "ST") and (ns9:Segment-N4/ns9:Element-310 != "")'>
                              <imp1:ID>
                                 <xsl:value-of select="ns9:Segment-N4/ns9:Element-310"/>
                              </imp1:ID>
                              </xsl:when>
                              <xsl:when test='(ns9:Segment-N1/ns9:Element-98 = "ST") and (ns9:Segment-N4/ns9:Element-310 = "")'>
                              <imp1:ID>
                                 <xsl:value-of select="ns9:Segment-N1/ns9:Element-67"/>
                              </imp1:ID>
                              </xsl:when>
                            </xsl:choose>
                            <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                            <imp1:Address>
                              <imp1:LineOne>
                                 <xsl:value-of select="ns9:Segment-N3[1]/ns9:Element-166"/>
                              </imp1:LineOne>
                              <imp1:LineTwo>
                                 <xsl:value-of select="ns9:Segment-N3[1]/ns9:Element-166_1"/>
                              </imp1:LineTwo>
                              <imp1:LineThree>
                                 <xsl:value-of select="ns9:Segment-N3[2]/ns9:Element-166"/>
                              </imp1:LineThree>
                              <imp1:LineFour>
                                 <xsl:value-of select="ns9:Segment-N3[2]/ns9:Element-166_1"/>
                              </imp1:LineFour>
                            <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                              <imp1:CityName>
                                 <xsl:value-of select="ns9:Segment-N4/ns9:Element-19"/>
                              </imp1:CityName>
                            </xsl:if>
                            <xsl:choose>
                             <xsl:when test='(ns9:Segment-N4/ns9:Element-26 = "US") or (ns9:Segment-N4/ns9:Element-26 = "CA")'>
                              <imp1:CountrySubDivisionCode>
                                <xsl:value-of select="ns9:Segment-N4/ns9:Element-156"/>
                              </imp1:CountrySubDivisionCode>
                             </xsl:when>
                             <xsl:when test='(ns9:Segment-N4/ns9:Element-26 != "US") and (ns9:Segment-N4/ns9:Element-26 != "CA")'>
                              <imp1:CountrySubDivisionCode>
                                <xsl:value-of select="ns9:Segment-N4/ns9:Element-1715"/>
                              </imp1:CountrySubDivisionCode>
                             </xsl:when>
                            </xsl:choose>
                            <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                              <imp1:CountryCode>
                                <xsl:value-of select="ns9:Segment-N4/ns9:Element-26"/>
                              </imp1:CountryCode>
                            </xsl:if>
                            <xsl:if test='ns9:Segment-N1/ns9:Element-98 = "ST"'>
                              <imp1:PostalCode>
                                <xsl:value-of select="ns9:Segment-N4/ns9:Element-116"/>
                              </imp1:PostalCode>
                            </xsl:if>
                             </imp1:Address>
                            </xsl:if>
                          </imp1:Location>
                            <xsl:if test='(ns9:Segment-N1/ns9:Element-98 = "ST") and ((ns9:Segment-PER/ns9:Element-93 !="") or (ns9:Segment-PER/ns9:Element-364_2 !="") or (ns9:Segment-PER/ns9:Element-364_1 !="") or (ns9:Segment-PER/ns9:Element-364 !=""))'>
                            <imp1:Contact>
                              <imp1:Name>
                                   <xsl:value-of select="ns9:Segment-PER/ns9:Element-93"/>
                              </imp1:Name>
                               <imp1:Communication>
                                 <imp1:ChannelCode>
                                   <xsl:value-of select='string("EMAIL")'/>
                                 </imp1:ChannelCode>
                                 <imp1:URI>
                                   <xsl:value-of select="ns9:Segment-PER/ns9:Element-364_2"/>
                                 </imp1:URI>
                               </imp1:Communication>
                               <imp1:Communication>
                                 <imp1:ChannelCode>
                                   <xsl:value-of select='string("FAX")'/>
                                 </imp1:ChannelCode>
                                 <imp1:DialNumber>
                                   <xsl:value-of select="ns9:Segment-PER/ns9:Element-364_1"/>
                                 </imp1:DialNumber>
                               </imp1:Communication>
                               <imp1:Communication>
                                 <imp1:ChannelCode>
                                   <xsl:value-of select='string("TELEPHONE")'/>
                                 </imp1:ChannelCode>
                                 <imp1:DialNumber>
                                   <xsl:value-of select="ns9:Segment-PER/ns9:Element-364"/>
                                 </imp1:DialNumber>
                               </imp1:Communication>
                            </imp1:Contact>
                            </xsl:if>
                        </imp1:ShipToParty>
                    </xsl:if> 
                  </imp1:UserArea>
                </imp1:PurchaseOrderSchedule>
              </xsl:for-each>
            </imp1:PurchaseOrderLine>
          </xsl:for-each>
        </imp1:PurchaseOrder>
      </DataArea>
      </ProcessPO>
      <Message_id>
        <xsl:value-of select="/inp1:CustomEDI850/Message_id"/>
      </Message_id>
      <Message_direction>
        <xsl:value-of select="/inp1:CustomEDI850/Message_direction"/>
      </Message_direction>
      <Sender_Document_number>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Document_number"/>
      </Sender_Document_number>
      <Sender_Message_type>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Message_type"/>
      </Sender_Message_type>
      <Sender_Message_standard>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Message_standard"/>
      </Sender_Message_standard>
      <Sender_Transaction_type>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Transaction_type"/>
      </Sender_Transaction_type>
      <Sender_Transaction_subtype>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Transaction_subtype"/>
      </Sender_Transaction_subtype>
      <Sender_System_type>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_System_type"/>
      </Sender_System_type>
      <Sender_Id>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Id"/>
      </Sender_Id>
      <Sender_Site_Id>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Site_Id"/>
      </Sender_Site_Id>
      <Sender_Name>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Name"/>
      </Sender_Name>
      <Sender_Type>
        <xsl:value-of select="/inp1:CustomEDI850/Sender_Type"/>
      </Sender_Type>
      <Receiver_System_type>
        <xsl:value-of select="/inp1:CustomEDI850/Receiver_System_type"/>
      </Receiver_System_type>
      <Receiver_Id>
        <xsl:value-of select="/inp1:CustomEDI850/Receiver_Id"/>
      </Receiver_Id>
      <Receiver_Site_id>
        <xsl:value-of select="/inp1:CustomEDI850/Receiver_Site_id"/>
      </Receiver_Site_id>
      <Receiver_Name>
        <xsl:value-of select="/inp1:CustomEDI850/Receiver_Name"/>
      </Receiver_Name>
      <Receiver_type>
        <xsl:value-of select="/inp1:CustomEDI850/Receiver_type"/>
      </Receiver_type>
      <File_name>
        <xsl:value-of select="/inp1:CustomEDI850/File_name"/>
      </File_name>
      <Record_total>
        <xsl:value-of select="/inp1:CustomEDI850/Record_total"/>
      </Record_total>
      <Record_number>
        <xsl:value-of select="/inp1:CustomEDI850/Record_number"/>
      </Record_number>
      <Flow_id_1>
        <xsl:value-of select="/inp1:CustomEDI850/Flow_id_1"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="ehdr:getInstanceID()"/>
      </Flow_id_2>
      <Flow_id_3>
        <xsl:value-of select="/inp1:CustomEDI850/Flow_id_3"/>
      </Flow_id_3>
      <Send_on_fail>
        <xsl:value-of select="/inp1:CustomEDI850/Send_on_fail"/>
      </Send_on_fail>
      <Division_name>
        <xsl:value-of select="/inp1:CustomEDI850/Division_name"/>
      </Division_name>
      <Division_format>
        <xsl:value-of select="/inp1:CustomEDI850/Division_format"/>
      </Division_format>
      <Trading_partner_1_name>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_1_name"/>
      </Trading_partner_1_name>
      <Trading_partner_1_format>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_1_format"/>
      </Trading_partner_1_format>
      <Trading_partner_1_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_1_date_from"/>
      </Trading_partner_1_date_from>
      <Trading_partner_1_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_1_date_to"/>
      </Trading_partner_1_date_to>
      <Trading_partner_2_name>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_2_name"/>
      </Trading_partner_2_name>
      <Trading_partner_2_format>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_2_format"/>
      </Trading_partner_2_format>
      <Trading_partner_2_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_2_date_from"/>
      </Trading_partner_2_date_from>
      <Trading_partner_2_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_2_date_to"/>
      </Trading_partner_2_date_to>
      <Trading_partner_3_name>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_3_name"/>
      </Trading_partner_3_name>
      <Trading_partner_3_format>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_3_format"/>
      </Trading_partner_3_format>
      <Trading_partner_3_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_3_date_from"/>
      </Trading_partner_3_date_from>
      <Trading_partner_3_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Trading_partner_3_date_to"/>
      </Trading_partner_3_date_to>
      <Logistics_1_name>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_1_name"/>
      </Logistics_1_name>
      <Logistics_1_format>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_1_format"/>
      </Logistics_1_format>
      <Logistics_1_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_1_date_from"/>
      </Logistics_1_date_from>
      <Logistics_1_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_1_date_to"/>
      </Logistics_1_date_to>
      <Logistics_2_name>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_2_name"/>
      </Logistics_2_name>
      <Logistics_2_format>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_2_format"/>
      </Logistics_2_format>
      <Logistics_2_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_2_date_from"/>
      </Logistics_2_date_from>
      <Logistics_2_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_2_date_to"/>
      </Logistics_2_date_to>
      <Logistics_3_name>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_3_name"/>
      </Logistics_3_name>
      <Logistics_3_format>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_3_format"/>
      </Logistics_3_format>
      <Logistics_3_date_from>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_3_date_from"/>
      </Logistics_3_date_from>
      <Logistics_3_date_to>
        <xsl:value-of select="/inp1:CustomEDI850/Logistics_3_date_to"/>
      </Logistics_3_date_to>
      <Compliance_result>
        <xsl:value-of select="/inp1:CustomEDI850/Compliance_result"/>
      </Compliance_result>
      <Attribute1>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute1"/>
      </Attribute1>
      <Attribute2>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute2"/>
      </Attribute2>
      <Attribute3>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute3"/>
      </Attribute3>
      <Attribute4>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute4"/>
      </Attribute4>
      <Attribute5>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute5"/>
      </Attribute5>
      <Attribute6>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute6"/>
      </Attribute6>
      <Attribute7>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute7"/>
      </Attribute7>
      <Attribute8>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute8"/>
      </Attribute8>
      <Attribute9>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute9"/>
      </Attribute9>
      <Attribute10>
        <xsl:value-of select="/inp1:CustomEDI850/Attribute10"/>
      </Attribute10>
    </inp1:CustomProcessPO>
  </xsl:template>
</xsl:stylesheet>
