<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="ETH_Transform_Edi_856_5020"
     targetNamespace="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_B2BInOut"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_B2BInOut"
     xmlns:inp1="http://xmlns.emrsn.com/CustomTransaction-856"
    >
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.emrsn.com/CustomTransaction-856" schemaLocation="public_html/Custom_EMR856V10.xsd" />
      </schema>
    </types>
    <message name="Custom_Transaction-856_request">
        <part name="Custom_Transaction-856" element="inp1:Custom_Transaction-856"/>
    </message>
    <portType name="execute_ppt">
        <operation name="execute">
            <input message="tns:Custom_Transaction-856_request"/>
        </operation>
    </portType>
</definitions>
