<?binding.jca DB_Execute_PpWoPublishPkg_CloseProjectDetails_db.jca?>
<wsdl:definitions name="DB_Execute_PpWoPublishPkg_CloseProjectDetails" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPO/ALESup_PP_ProjectDetails_Pub/DB_Execute_PpWoPublishPkg_CloseProjectDetails" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ALE_ESB_CONNECT/ALLETE_PP_WO_PUBLISH_PKG/CLOSE_PROJECT_DETAILS/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPO/ALESup_PP_ProjectDetails_Pub/DB_Execute_PpWoPublishPkg_CloseProjectDetails" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DB_Execute_PpWoPublishPkg_CloseProjectDetails_plt">
        <plt:role name="DB_Execute_PpWoPublishPkg_CloseProjectDetails_role">
            <plt:portType name="tns:DB_Execute_PpWoPublishPkg_CloseProjectDetails_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ALE_ESB_CONNECT/ALLETE_PP_WO_PUBLISH_PKG/CLOSE_PROJECT_DETAILS/" schemaLocation="xsd/ALE_ESB_CONNECT_ALLETE_PP_WO_PUBLISH_PKG_CLOSE_PROJECT_DETAILS.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="DB_Execute_PpWoPublishPkg_CloseProjectDetails_ptt">
        <wsdl:operation name="DB_Execute_PpWoPublishPkg_CloseProjectDetails">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
