<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="jmsAdapterInboundHeader.wsdl"/>
      <rootElement name="JMSInboundHeadersAndProperties" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="jmsAdapterInboundHeader.wsdl"/>
      <rootElement name="JMS_IN_Header" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI JUL 17 15:33:36 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:jms="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                exclude-result-prefixes="xsl ns0 jms xref xp20 bpws ora ehdr orcl ids hwf">
  <xsl:template match="/">
    <jms:JMS_IN_Header>
      <jms:JMSInboundHeadersAndProperties>
        <jms:JMSInboundHeaders>
          <jms:JMSCorrelationID>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSCorrelationID"/>
          </jms:JMSCorrelationID>
          <jms:JMSDeliveryMode>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSDeliveryMode"/>
          </jms:JMSDeliveryMode>
          <jms:JMSExpiration>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSExpiration"/>
          </jms:JMSExpiration>
          <jms:JMSMessageID>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSMessageID"/>
          </jms:JMSMessageID>
          <jms:JMSPriority>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSPriority"/>
          </jms:JMSPriority>
          <jms:JMSRedelivered>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSRedelivered"/>
          </jms:JMSRedelivered>
          <jms:JMSType>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSType"/>
          </jms:JMSType>
          <jms:JMSTimestamp>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSTimestamp"/>
          </jms:JMSTimestamp>
          <jms:JMSReplyTo>
            <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundHeaders/jms:JMSReplyTo"/>
          </jms:JMSReplyTo>
        </jms:JMSInboundHeaders>
        <jms:JMSInboundProperties>
          <xsl:for-each select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundProperties/jms:Property[@name!='ESB_ERROR_MESSAGE' and @name!='ESB_ERROR_STACK' and @name!='ESB_REQUEST_HEADER']">
            <jms:Property>
              <xsl:attribute name="name">
                <xsl:value-of select="@name"/>
              </xsl:attribute>
              <xsl:attribute name="type">
                <xsl:value-of select="@type"/>
              </xsl:attribute>
              <xsl:attribute name="value">
                <xsl:value-of select="@value"/>
              </xsl:attribute>
              <xsl:value-of select="."/>
            </jms:Property>
          </xsl:for-each>
        </jms:JMSInboundProperties>
      </jms:JMSInboundHeadersAndProperties>
    </jms:JMS_IN_Header>
  </xsl:template>
</xsl:stylesheet>
