<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="jmsAdapterInboundHeader.wsdl"/>
      <rootElement name="JMSInboundHeadersAndProperties" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETH_JMST_DEQ_ESBError.wsdl"/>
      <rootElement name="stringElement" namespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE JUL 21 12:09:23 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_JMST_DEQ_ESBError/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:jms="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                exclude-result-prefixes="xsl ns0 hdr plt pc jca tns opaque bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <opaque:stringElement>
      <xsl:choose>
        <xsl:when test="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundProperties/jms:Property[@name='ESB_ERROR_STACK']/@value">
          <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundProperties/jms:Property[@name='ESB_ERROR_STACK']/@value"/>
        </xsl:when>
        <xsl:when test="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundProperties/jms:Property[@name='ESB_ERROR_MESSAGE']/@value">
          <xsl:value-of select="/jms:JMSInboundHeadersAndProperties/jms:JMSInboundProperties/jms:Property[@name='ESB_ERROR_MESSAGE']/@value"/>
        </xsl:when>
        <xsl:otherwise>Unknown Error</xsl:otherwise>
      </xsl:choose>
    </opaque:stringElement>
  </xsl:template>
</xsl:stylesheet>
