<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="MDMService.xsd"/>
      <rootElement name="CreateRecordsRequest" namespace="http://www.gssamerica.com/mdm/services"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="WorkflowService.xsd"/>
      <rootElement name="WorkflowRequest" namespace="http://www.gssamerica.com/mdm/workflowservice"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU JUN 12 12:59:23 IST 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns0="http://www.gssamerica.com/mdm/workflowservice"
                xmlns:sample="http://www.oracle.com/XSL/Transform/java/esbext.func.ESBExtensionFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:tns="http://www.gssamerica.com/mdm/services"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl xs tns ns0 sample bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:param name="operation"/>
  <xsl:param name="entitystatus"/>
   <xsl:param name="srcID"/>
  <xsl:param name="entity"/>
  <xsl:template match="/"> 
  
    <ns0:WorkflowRequest>
      <header>        
        <operation>
          <xsl:value-of select="$operation"/>
        </operation>
        <entitystatus>
            <xsl:value-of select="$entitystatus"/>  
        </entitystatus>
         <srcID>
           <xsl:value-of select="$srcID"/>  
         </srcID>
        <entity>
           <xsl:value-of select="$entity"/>  
        </entity>
        <xsl:for-each select="/tns:UpdateRecordRequest/tns:configData/tns:element">       
        <configData>          
            <name>
              <xsl:value-of select="tns:name"/>
            </name>
            <value>
              <xsl:value-of select="tns:value"/>
            </value>          
        </configData>
       </xsl:for-each>      
      </header>
     <body>
        <xsl:copy-of select="."/>
      </body>
    </ns0:WorkflowRequest>
  </xsl:template>
</xsl:stylesheet>
