<?binding.jca RND_JMS_ENQ_Message_jms.jca?>
<wsdl:definitions name="RND_JMS_ENQ_Message" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Dhami-SOA/RND_JMSPublisher/RND_JMS_ENQ_Message" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Dhami-SOA/RND_JMSPublisher/RND_JMS_ENQ_Message" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="Produce_ETHMessage_plt">
        <plt:role name="Produce_ETHMessage_role">
            <plt:portType name="tns:Produce_ETHMessage_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="opaqueElement" type="base64Binary"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="Produce_ETHMessage_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="Produce_ETHMessage_ptt">
        <wsdl:operation name="Produce_ETHMessage">
            <wsdl:input message="tns:Produce_ETHMessage_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
