// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.gssamerica.mdm.services.create;

public interface MDMCreateRecords_PortType extends java.rmi.Remote {
    public com.gssamerica.mdm.services.ServiceReturnType createRecords(com.gssamerica.mdm.services.CreateRecordRequestType createRecordsRequest) throws 
         java.rmi.RemoteException;
}
