<?binding.jca RND_DB_INS_ICoE_db.jca?>
<wsdl:definitions name="RND_DB_INS_ICoE" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Dhami-SOA/RND_BPEL_ErrorFaultPolicy/RND_DB_INS_ICoE" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Dhami-SOA/RND_BPEL_ErrorFaultPolicy/RND_DB_INS_ICoE" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/RND_DB_INS_ICoE">
    <plt:partnerLinkType name="RND_DB_INS_ICoE_plt">
        <plt:role name="RND_DB_INS_ICoE_role">
            <plt:portType name="tns:RND_DB_INS_ICoE_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/RND_DB_INS_ICoE" schemaLocation="xsd/RND_DB_INS_ICoE_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ErrorTableCollection_msg">
        <wsdl:part name="ErrorTableCollection" element="top:ErrorTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="RND_DB_INS_ICoE_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ErrorTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
