<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_OutputServices_ETHSysGrp_POAck_FlatFile_Output_ETH_Transform_CustomFlatFile_RS.wsdl"/>
      <rootElement name="CustomLiebertPOAck" namespace="http://xmlns.emrsn.com/CustomPOAckFlatFile"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETH_PUTFL_POAck_FixedWidth_FlatFile.wsdl"/>
      <rootElement name="Root-Element" namespace="http://xmlns.emrsn.com/POAckFlatFile"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE APR 27 19:29:12 IST 2010]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns1="http://oracle.com/esb/namespaces/ETHSys_OutputServices_ETHSysGrp_POAck_FlatFile_Output"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:inp1="http://xmlns.emrsn.com/CustomPOAckFlatFile"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:eth="http://www.oracle.com/XSL/Transform/java/ETHComplianceCheck.functions.ETHComplianceCheck"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/ETH_PUTFL_POAck_FixedWidth_FlatFile/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:imp1="http://xmlns.emrsn.com/POAckFlatFile"
                exclude-result-prefixes="xsl ns1 inp1 ns0 imp1 plt jca tns hdr bpws ehdr eth hwf xp20 xref ora ids orcl">
  <xsl:preserve-space elements="*"/>
  <xsl:template name="formatText">
    <xsl:param name="inputString"/>
    <xsl:param name="length"/>
    <xsl:variable name="spaces">
    <xsl:text>                                                                                                                                                                                                        </xsl:text>
    </xsl:variable>
    <xsl:value-of select="substring(concat($inputString,$spaces),1,$length)"/>
  </xsl:template>

  <xsl:template name="formatNumber">
    <xsl:param name="inputString"/>
    <xsl:param name="length"/>
    <xsl:param name="precision"/>
    <xsl:variable name="padChar">
    <xsl:text>000000000000000000000000000000</xsl:text>
    </xsl:variable>
    <xsl:variable name="v_number">
        <xsl:choose>
            <xsl:when test="string-length($inputString) = 0">
                <xsl:value-of select="string('')"/>
            </xsl:when>
            <xsl:when test="string-length(substring-before($inputString,'.')) != 0">
                <xsl:value-of select="substring-before(abs($inputString),'.')"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="abs($inputString)"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:variable>
    <xsl:variable name="v_paddedNumber">
        <xsl:value-of select="concat(substring($padChar,1,($length - 6 - string-length($v_number))),$v_number)"/>
    </xsl:variable>
    <xsl:variable name="v_decimal">
        <xsl:value-of select="substring(concat(substring-after($inputString,'.'),$padChar),1,$precision)"/>
    </xsl:variable>
    <xsl:choose>
        <xsl:when test="substring($inputString,1,1) = '-'">
            <xsl:value-of select="concat('-',$v_paddedNumber,$v_decimal)"/>
        </xsl:when>
        <xsl:otherwise>
            <xsl:value-of select="concat(' ',$v_paddedNumber,$v_decimal)"/>
        </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  
  <xsl:template match="/">  
    <imp1:Root-Element>
      <xsl:for-each select="/inp1:CustomLiebertPOAck/imp1:Root-Element/imp1:record">
        <record>
         <HDGS02>
            <xsl:value-of select="imp1:HDGS02"/>
          </HDGS02>
          <HDGS03>
            <xsl:value-of select="imp1:HDGS03"/>
          </HDGS03>
          <HDGS04>
            <xsl:value-of select="imp1:HDGS04"/>
          </HDGS04>
          <HDGS05>
            <xsl:value-of select="imp1:HDGS05"/>
          </HDGS05>
          <HDBAK01>
            <xsl:value-of select="imp1:HDBAK01"/>
          </HDBAK01>
          <HDBAK02>
            <xsl:value-of select="imp1:HDBAK02"/>
          </HDBAK02>
          <HDBAK03>
            <xsl:value-of select="imp1:HDBAK03"/>
          </HDBAK03>
          <HDBAK04>
            <xsl:value-of select="imp1:HDBAK04"/>
          </HDBAK04>
          <HDBAK05>
            <xsl:value-of select="imp1:HDBAK05"/>
          </HDBAK05>
          <HDBAK08>
            <xsl:value-of select="imp1:HDBAK08"/>
          </HDBAK08>
          <HDBAK09>
            <xsl:value-of select="imp1:HDBAK09"/>
          </HDBAK09>
          <HD1REF03>
            <xsl:value-of select="imp1:HD1REF03"/>
          </HD1REF03>
          <HD4REF02>
            <xsl:value-of select="imp1:HD4REF02"/>
          </HD4REF02>
          <HD5REF03>
            <xsl:value-of select="imp1:HD5REF03"/>
          </HD5REF03>
          <HD1N102>
            <xsl:value-of select="imp1:HD1N102"/>
          </HD1N102>
          <HD1N104>
            <xsl:value-of select="imp1:HD1N104"/>
          </HD1N104>
          <HD1N301>
            <xsl:value-of select="imp1:HD1N301"/>
          </HD1N301>
          <HD1N302>
            <xsl:value-of select="imp1:HD1N302"/>
          </HD1N302>
          <HD1N303>
            <xsl:value-of select="imp1:HD1N303"/>
          </HD1N303>
          <HD1N304>
            <xsl:value-of select="imp1:HD1N304"/>
          </HD1N304>
          <HD1N401>
            <xsl:value-of select="imp1:HD1N401"/>
          </HD1N401>
          <HD1N402>
            <xsl:value-of select="imp1:HD1N402"/>
          </HD1N402>
          <HD1N403>
            <xsl:value-of select="imp1:HD1N403"/>
          </HD1N403>
          <HD1N404>
            <xsl:value-of select="imp1:HD1N404"/>
          </HD1N404>
          <HD1N406>
            <xsl:value-of select="imp1:HD1N406"/>
          </HD1N406>
          <HD1PER02>
            <xsl:value-of select="imp1:HD1PER02"/>
          </HD1PER02>
          <HD1PER04>
            <xsl:value-of select="imp1:HD1PER04"/>
          </HD1PER04>
          <HD1PER06>
            <xsl:value-of select="imp1:HD1PER06"/>
          </HD1PER06>
          <HD1PER08>
            <xsl:value-of select="imp1:HD1PER08"/>
          </HD1PER08>
          <LN1PO101>
            <xsl:value-of select="imp1:LN1PO101"/>
          </LN1PO101>
          <LN1PO102>
            <xsl:call-template name="formatNumber">
		<xsl:with-param name="inputString" select="imp1:LN1PO102"/>
		<xsl:with-param name="length" select="15"/>
                <xsl:with-param name="precision" select="5"/>
            </xsl:call-template>
            <!-- <xsl:value-of select="imp1:LN1PO102"/>-->
          </LN1PO102>
          <LN1PO103>
            <xsl:value-of select="imp1:LN1PO103"/>
          </LN1PO103>
          <LN1PO104>
            <xsl:call-template name="formatNumber">
		<xsl:with-param name="inputString" select="imp1:LN1PO104"/>
		<xsl:with-param name="length" select="17"/>
                <xsl:with-param name="precision" select="5"/>
            </xsl:call-template>
            <!--<xsl:value-of select="imp1:LN1PO104"/>-->
          </LN1PO104>
          <LN1PO107>
            <xsl:value-of select="imp1:LN1PO107"/>
          </LN1PO107>
          <LN1PO109>
            <xsl:value-of select="imp1:LN1PO109"/>
          </LN1PO109>
          <LN1PO111>
            <xsl:value-of select="imp1:LN1PO111"/>
          </LN1PO111>
          <LN1CUR02>
            <xsl:value-of select="imp1:LN1CUR02"/>
          </LN1CUR02>
          <LN1PID05>
            <xsl:value-of select="imp1:LN1PID05"/>
          </LN1PID05>
          <LN1ACK01>
            <xsl:value-of select="imp1:LN1ACK01"/>
          </LN1ACK01>
          <LN1N102>
            <xsl:value-of select="imp1:LN1N102"/>
          </LN1N102>
          <LN1N104>
            <xsl:value-of select="imp1:LN1N104"/>
          </LN1N104>
          <LN1N301>
            <xsl:value-of select="imp1:LN1N301"/>
          </LN1N301>
          <LN1N302>
            <xsl:value-of select="imp1:LN1N302"/>
          </LN1N302>
          <LN1N303>
            <xsl:value-of select="imp1:LN1N303"/>
          </LN1N303>
          <LN1N304>
            <xsl:value-of select="imp1:LN1N304"/>
          </LN1N304>
          <LN1N401>
            <xsl:value-of select="imp1:LN1N401"/>
          </LN1N401>
          <LN1N402>
            <xsl:value-of select="imp1:LN1N402"/>
          </LN1N402>
          <LN1N403>
            <xsl:value-of select="imp1:LN1N403"/>
          </LN1N403>
          <LN1N404>
            <xsl:value-of select="imp1:LN1N404"/>
          </LN1N404>
          <LN1N406>
            <xsl:value-of select="imp1:LN1N406"/>
          </LN1N406>
          <LN1PER02>
            <xsl:value-of select="imp1:LN1PER02"/>
          </LN1PER02>
          <LN1PER04>
            <xsl:value-of select="imp1:LN1PER04"/>
          </LN1PER04>
          <LN1PER06>
            <xsl:value-of select="imp1:LN1PER06"/>
          </LN1PER06>
          <LN1PER08>
            <xsl:value-of select="imp1:LN1PER08"/>
          </LN1PER08>
          <LN1SCH01>
            <xsl:call-template name="formatNumber">
		<xsl:with-param name="inputString" select="imp1:LN1SCH01"/>
		<xsl:with-param name="length" select="15"/>
                <xsl:with-param name="precision" select="5"/>
            </xsl:call-template>
            <!--<xsl:value-of select="imp1:LN1SCH01"/>-->
          </LN1SCH01>
          <LN1SCH02>
            <xsl:value-of select="imp1:LN1SCH02"/>
          </LN1SCH02>
          <LN1SCH06>
            <xsl:value-of select="imp1:LN1SCH06"/>
          </LN1SCH06>
          <LN1SCH07>
            <xsl:value-of select="imp1:LN1SCH07"/>
          </LN1SCH07>
          <LN1SCH09>
            <xsl:value-of select="imp1:LN1SCH09"/>
          </LN1SCH09>
          <LN1SCH10>
            <xsl:value-of select="imp1:LN1SCH10"/>
          </LN1SCH10>
          <LN1SCH12>
            <xsl:value-of select="imp1:LN1SCH12"/>
          </LN1SCH12>
          <LN2N102>
            <xsl:value-of select="imp1:LN2N102"/>
          </LN2N102>
          <LN2N104>
            <xsl:value-of select="imp1:LN2N104"/>
          </LN2N104>
          <LN2N301>
            <xsl:value-of select="imp1:LN2N301"/>
          </LN2N301>
          <LN2N302>
            <xsl:value-of select="imp1:LN2N302"/>
          </LN2N302>
          <LN2N303>
            <xsl:value-of select="imp1:LN2N303"/>
          </LN2N303>
          <LN2N304>
            <xsl:value-of select="imp1:LN2N304"/>
          </LN2N304>
          <LN2N401>
            <xsl:value-of select="imp1:LN2N401"/>
          </LN2N401>
          <LN2N402>
            <xsl:value-of select="imp1:LN2N402"/>
          </LN2N402>
          <LN2N403>
            <xsl:value-of select="imp1:LN2N403"/>
          </LN2N403>
          <LN2N404>
            <xsl:value-of select="imp1:LN2N404"/>
          </LN2N404>
          <LN2N406>
            <xsl:value-of select="imp1:LN2N406"/>
          </LN2N406>
          <LN2PER02>
            <xsl:value-of select="imp1:LN2PER02"/>
          </LN2PER02>
          <LN2PER04>
            <xsl:value-of select="imp1:LN2PER04"/>
          </LN2PER04>
          <LN2PER06>
            <xsl:value-of select="imp1:LN2PER06"/>
          </LN2PER06>
          <LN2PER08>
            <xsl:call-template name="formatText">
		<xsl:with-param name="inputString" select="imp1:LN2PER08"/>
		<xsl:with-param name="length" select="50"/>
            </xsl:call-template>
            <!--<xsl:value-of select="imp1:LN2PER08"/>-->
          </LN2PER08>
        </record>
      </xsl:for-each>
    </imp1:Root-Element>
  </xsl:template>
</xsl:stylesheet>
