-- Declare the SQL type for the PL/SQL type BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC
CREATE OR REPLACE TYPE BPEL_COM_SRVC_LOX183882X1X10 AS OBJECT (
      COMMON_SERVICE_NAME VARCHAR2(150),
      COMMON_SERVICE_URL VARCHAR2(500),
      PAYLOAD_REQUIRED VARCHAR2(5),
      STOPONFAILURE1 VARCHAR2(10),
      STOPONFAILURE2 VARCHAR2(10),
      STOPONFAILURE3 VARCHAR2(10),
      STOPONFAILURE4 VARCHAR2(10),
      STOPONFAILURE5 VARCHAR2(10)
);
/
show errors
-- uncomment to overwrite existing types
-- CREATE OR REPLACE TYPE BPEL_COM_SRVC_LOOX183882X1X9 AS TABLE OF ETH_CUSTOM_SCHEMA.BPEL_COM_SRVC_LOX183882X1X10; 
-- /
-- show errors
-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_COM_SRVC_LOOKUP_WRAP AS
	-- Declare the conversion functions the PL/SQL type BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC
	FUNCTION PL_TO_SQL1(aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC)
 	RETURN BPEL_COM_SRVC_LOX183882X1X10;
	FUNCTION SQL_TO_PL1(aSqlItem BPEL_COM_SRVC_LOX183882X1X10)
	RETURN BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC;
	-- Declare the conversion functions the PL/SQL type BPEL_COM_SRVC_LOOKUP_PKG.B_LIST
	FUNCTION PL_TO_SQL0(aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_LIST)
 	RETURN BPEL_COM_SRVC_LOOX183882X1X9;
	FUNCTION SQL_TO_PL0(aSqlItem BPEL_COM_SRVC_LOOX183882X1X9)
	RETURN BPEL_COM_SRVC_LOOKUP_PKG.B_LIST;
   PROCEDURE bpel_com_srvc_lookup_pkg$bpel (P_CALLER_NAME VARCHAR2,
	P_SENDER_ID VARCHAR2,
	P_TRXN_TYPE VARCHAR2,
	P_TRXN_SUBTYPE VARCHAR2,
	P_SOA_INSTANCE_ID VARCHAR2,
	P_TXN_RECORD_ID NUMBER,
	P_TEMP_ID NUMBER,
	P_SERVER_NAME OUT VARCHAR2,
	P_OUT OUT ETH_CUSTOM_SCHEMA.BPEL_COM_SRVC_LOOX183882X1X9,
	P_RESPONSECODE OUT NUMBER,
	P_ERRORCODENUMBER OUT VARCHAR2,
	P_ERRORDESCRIPTION OUT VARCHAR2
	);
END BPEL_COM_SRVC_LOOKUP_WRAP;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_COM_SRVC_LOOKUP_WRAP IS
	FUNCTION PL_TO_SQL1(aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC)
 	RETURN BPEL_COM_SRVC_LOX183882X1X10 IS 
	aSqlItem BPEL_COM_SRVC_LOX183882X1X10; 
	BEGIN 
		-- initialize the object
		aSqlItem := BPEL_COM_SRVC_LOX183882X1X10(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.COMMON_SERVICE_NAME := aPlsqlItem.COMMON_SERVICE_NAME;
		aSqlItem.COMMON_SERVICE_URL := aPlsqlItem.COMMON_SERVICE_URL;
		aSqlItem.PAYLOAD_REQUIRED := aPlsqlItem.PAYLOAD_REQUIRED;
		aSqlItem.STOPONFAILURE1 := aPlsqlItem.STOPONFAILURE1;
		aSqlItem.STOPONFAILURE2 := aPlsqlItem.STOPONFAILURE2;
		aSqlItem.STOPONFAILURE3 := aPlsqlItem.STOPONFAILURE3;
		aSqlItem.STOPONFAILURE4 := aPlsqlItem.STOPONFAILURE4;
		aSqlItem.STOPONFAILURE5 := aPlsqlItem.STOPONFAILURE5;
		RETURN aSqlItem;
	END PL_TO_SQL1;
	FUNCTION SQL_TO_PL1(aSqlItem BPEL_COM_SRVC_LOX183882X1X10) 
	RETURN BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC IS 
	aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_BASE_REC; 
	BEGIN 
		aPlsqlItem.COMMON_SERVICE_NAME := aSqlItem.COMMON_SERVICE_NAME;
		aPlsqlItem.COMMON_SERVICE_URL := aSqlItem.COMMON_SERVICE_URL;
		aPlsqlItem.PAYLOAD_REQUIRED := aSqlItem.PAYLOAD_REQUIRED;
		aPlsqlItem.STOPONFAILURE1 := aSqlItem.STOPONFAILURE1;
		aPlsqlItem.STOPONFAILURE2 := aSqlItem.STOPONFAILURE2;
		aPlsqlItem.STOPONFAILURE3 := aSqlItem.STOPONFAILURE3;
		aPlsqlItem.STOPONFAILURE4 := aSqlItem.STOPONFAILURE4;
		aPlsqlItem.STOPONFAILURE5 := aSqlItem.STOPONFAILURE5;
		RETURN aPlsqlItem;
	END SQL_TO_PL1;
	FUNCTION PL_TO_SQL0(aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_LIST)
 	RETURN BPEL_COM_SRVC_LOOX183882X1X9 IS 
	aSqlItem BPEL_COM_SRVC_LOOX183882X1X9; 
	BEGIN 
		-- initialize the table 
		aSqlItem := BPEL_COM_SRVC_LOOX183882X1X9();
		IF aPlsqlItem IS NOT NULL THEN
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		IF aPlsqlItem.COUNT>0 THEN
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL1(aPlsqlItem(I));
		END LOOP; 
		END IF; 
		END IF; 
		RETURN aSqlItem;
	END PL_TO_SQL0;
	FUNCTION SQL_TO_PL0(aSqlItem BPEL_COM_SRVC_LOOX183882X1X9) 
	RETURN BPEL_COM_SRVC_LOOKUP_PKG.B_LIST IS 
	aPlsqlItem BPEL_COM_SRVC_LOOKUP_PKG.B_LIST; 
	BEGIN 
		aPlsqlItem := BPEL_COM_SRVC_LOOKUP_PKG.B_LIST();
		aPlsqlItem.EXTEND(aSqlItem.COUNT);
		IF aSqlItem.COUNT>0 THEN
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL1(aSqlItem(I));
		END LOOP; 
		END IF;
		RETURN aPlsqlItem;
	END SQL_TO_PL0;

   PROCEDURE bpel_com_srvc_lookup_pkg$bpel (P_CALLER_NAME VARCHAR2,
	P_SENDER_ID VARCHAR2,
	P_TRXN_TYPE VARCHAR2,
	P_TRXN_SUBTYPE VARCHAR2,
	P_SOA_INSTANCE_ID VARCHAR2,
	P_TXN_RECORD_ID NUMBER,
	P_TEMP_ID NUMBER,
	P_SERVER_NAME OUT VARCHAR2,
	P_OUT OUT ETH_CUSTOM_SCHEMA.BPEL_COM_SRVC_LOOX183882X1X9,
	P_RESPONSECODE OUT NUMBER,
	P_ERRORCODENUMBER OUT VARCHAR2,
	P_ERRORDESCRIPTION OUT VARCHAR2
	) IS
 P_OUT_ ETH_CUSTOM_SCHEMA.BPEL_COM_SRVC_LOOKUP_PKG.B_LIST;
   BEGIN
      ETH_CUSTOM_SCHEMA.BPEL_COM_SRVC_LOOKUP_PKG.BPEL_COMM_SRVC_LOOKUP_PRC(P_CALLER_NAME,
	P_SENDER_ID,
	P_TRXN_TYPE,
	P_TRXN_SUBTYPE,
	P_SOA_INSTANCE_ID,
	P_TXN_RECORD_ID,
	P_TEMP_ID,
	P_SERVER_NAME,
	P_OUT_,
	P_RESPONSECODE,
	P_ERRORCODENUMBER,
	P_ERRORDESCRIPTION
	);
 P_OUT := BPEL_COM_SRVC_LOOKUP_WRAP.PL_TO_SQL0(P_OUT_);
   END bpel_com_srvc_lookup_pkg$bpel;

END BPEL_COM_SRVC_LOOKUP_WRAP;
/
show errors
exit
