<definitions
     name="ETH_PUTFL_ChangePO"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/ETH_PUTFL_ChangePO/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/ETH_PUTFL_ChangePO/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:imp1="http://xmlns.emrsn.com/CustomChange_PO_006"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/file/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/file/" location="fileAdapterOutboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.emrsn.com/CustomChange_PO_006" schemaLocation="public_html/CustomChange_PO_006.xsd" />
      </schema>
    </types>
    <message name="CustomChange_PO_006_msg">
        <part name="CustomChange_PO_006" element="imp1:CustomChange_PO_006"/>
    </message>
    <portType name="Write_ptt">
        <operation name="Write">
            <input message="tns:CustomChange_PO_006_msg"/>
        </operation>
    </portType>
    <binding name="Write_binding" type="tns:Write_ptt">
    <jca:binding  />
        <operation name="Write">
      <jca:operation
          LogicalDirectory="ChangePO"
          InteractionSpec="oracle.tip.adapter.file.outbound.FileInteractionSpec"
          FileNamingConvention="CustomChangePO_%yyMMddHHmmssSS%.xml"
          NumberMessages="1"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="ETH_PUTFL_ChangePO">
        <port name="Write_pt" binding="tns:Write_binding">
      <jca:address location="eis/FileAdapter" />
        </port>
    </service>
  <plt:partnerLinkType name="Write_plt" >
    <plt:role name="Write_role" >
      <plt:portType name="tns:Write_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
