<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETH_GETFTP_ALICE_SBYN_OAGIS_7_2.wsdl"/>
      <rootElement name="PROCESS_PO_007" namespace="http://xmlns.emrsn.com/CommonProcessPO_007"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://142.176.225.230:8888/esb/wsil/ETHSys_IntegrationServices/ETHSysGrp_ProcessPurchaseOrder/ETH_Transform_CustomOAGIS_7_2_RS?wsdl"/>
      <rootElement name="CustomProcess_PO_007" namespace="http://xmlns.emrsn.com/CustomProcess_PO_007"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [THU MAR 12 21:58:30 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcess_PO_007"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ETH_GETFTP_ALICE_SBYN_OAGIS_7_2/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:imp1="http://xmlns.emrsn.com/CommonProcessPO_007"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
                exclude-result-prefixes="xsl plt pc ns0 tns jca imp1 hdr inp1 ns1 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <inp1:CustomProcess_PO_007>
      <imp1:PROCESS_PO_007>
        <xsl:copy-of select="/imp1:PROCESS_PO_007/*"/>
      </imp1:PROCESS_PO_007>
      <Message_id>
        <xsl:value-of select='orcl:sequence-next-val("SC_MessageID_Seq","jdbc:oracle:thin:SC_Report/welcome1@elshat1db.emrsn.com:20003:elshat3")'/>
      </Message_id>      
      <Message_direction>
        <xsl:value-of select="string('Out')"/>
      </Message_direction>
      <Message_type>
        <xsl:value-of select="string('XML')"/>
      </Message_type>
      <Message_standard>
         <xsl:value-of select="string('OAG')"/>
      </Message_standard>
      <Transaction_type>
        <xsl:value-of select='string("PO")'/>
      </Transaction_type>
      <Transaction_subtype>
        <xsl:value-of select='string("PRO")'/>
      </Transaction_subtype>
      <Document_number>
        <xsl:value-of select="/imp1:PROCESS_PO_007/imp1:DATAAREA/imp1:PROCESS_PO/imp1:POORDERHDR/imp1:POID"/>
      </Document_number>      
      <Sender_id>
        <xsl:value-of select="/imp1:PROCESS_PO_007/imp1:CNTROLAREA/imp1:SENDER/imp1:LOGICALID"/>        
      </Sender_id>
      <Sender_name>
        <xsl:value-of select="/imp1:PROCESS_PO_007/imp1:CNTROLAREA/imp1:SENDER/imp1:LOGICALID"/>
      </Sender_name>
      <Sender_system_type>
        <xsl:value-of select='string("Oracle")'/>
      </Sender_system_type>   
       <Party_id>
        <xsl:value-of select="/imp1:PROCESS_PO_007/imp1:CNTROLAREA/imp1:SENDER/imp1:LOGICALID"/>
      </Party_id>
      <Party_site_id>
        <xsl:value-of select='string("16000B0600001")'/>
      </Party_site_id>      
      <Party_name>
        <xsl:value-of select="/imp1:PROCESS_PO_007/imp1:CNTROLAREA/imp1:SENDER/imp1:LOGICALID"/>
      </Party_name>      
      <Party_type>
        <xsl:value-of select="string('S')"/>
      </Party_type>
      <Protocol_address>
        <xsl:value-of select="string('XmlEventKey')"/>
      </Protocol_address>
      <Flow_id_1>
        <xsl:value-of select="ehdr:getInstanceID()"/>
      </Flow_id_1>
      <Attribute1>
        <xsl:value-of select="string('EMC')"/>
      </Attribute1>
      <Attribute3>
        <xsl:value-of select="string('160004159')"/>
      </Attribute3>
      <xsl:for-each select="/imp1:PROCESS_PO_007/imp1:DATAAREA/imp1:PROCESS_PO/imp1:POORDERHDR/imp1:PARTNER">
        <xsl:if test="imp1:PARTNRTYPE = 'Supplier'">
          <Attribute4>
            <xsl:value-of select="imp1:PARTNRID"/>
          </Attribute4>
        </xsl:if>
      </xsl:for-each>
      <xsl:for-each select="/imp1:PROCESS_PO_007/imp1:DATAAREA/imp1:PROCESS_PO/imp1:POORDERHDR/imp1:PARTNER">
        <xsl:if test="imp1:PARTNRTYPE = 'Supplier'">
          <Attribute5>
            <xsl:value-of select="imp1:PARTNRIDX"/>
          </Attribute5>
        </xsl:if>
      </xsl:for-each>
    </inp1:CustomProcess_PO_007>
  </xsl:template>
</xsl:stylesheet>
