<?binding.jca ETH_DB_CallSP_GetReceiverTransaction_db.jca?>
<wsdl:definitions name="ETH_DB_CallSP_GetReceiverTransaction" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OutputServices/ETH_XMLGateway_ReceiverTransactionInitiate_Composite/ETH_DB_CallSP_GetReceiverTransaction" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_CUSTOM_SCHEMA/ETH_DBLISTENER2_PKG/GET_TRANSACTION_PRC/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OutputServices/ETH_XMLGateway_ReceiverTransactionInitiate_Composite/ETH_DB_CallSP_GetReceiverTransaction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ETH_DB_CallSP_GetReceiverTransaction_plt">
        <plt:role name="ETH_DB_CallSP_GetReceiverTransaction_role">
            <plt:portType name="tns:ETH_DB_CallSP_GetReceiverTransaction_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_CUSTOM_SCHEMA/ETH_DBLISTENER2_PKG/GET_TRANSACTION_PRC/" schemaLocation="xsd/ETH_CUSTOM_SCHEMA_ETH_DBLISTENER2_PKG_GET_TRANSACTION_PRC.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="ETH_DB_CallSP_GetReceiverTransaction_ptt">
        <wsdl:operation name="ETH_DB_CallSP_GetReceiverTransaction">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
