<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ETH_Mediator_RouteTo_POACKProvider"
     targetNamespace="http://xmlns.oracle.com/ETH_INBOUND_Receiver_Listener/ETH_XMLGateway_ReceiverTransactionInitiate_Composite/ETH_Mediator_RouteTo_POACKProvider"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/ETH_INBOUND_Receiver_Listener/ETH_XMLGateway_ReceiverTransactionInitiate_Composite/ETH_Mediator_RouteTo_POACKProvider"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ETH_Mediator_RouteTo_POACKProvider.ETH_Mediator_RouteTo_POACKProvider">
        <plnk:role name="execute_ptt">
            <plnk:portType name="tns:execute_ptt"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/ETH_INBOUND_Receiver_Listener/ETH_XMLGateway_ReceiverTransactionInitiate_Composite/ETH_Mediator_RouteTo_POACKProvider"
         location="ETH_Mediator_RouteTo_POACKProvider.wsdl"/>
</wsdl:definitions>
