<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="Routin_GetCustomer"
     targetNamespace="http://oracle.com/esb/namespaces/DefaultSystem"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://oracle.com/esb/namespaces/DefaultSystem"
     xmlns:inp1="http://www.gssamerica.com/mdm/esbgetcustomer"
    >
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.gssamerica.com/mdm/esbgetcustomer" schemaLocation="MDMSchemas/ServiceSchemas/GetCustomerService.xsd" />
      </schema>
    </types>
    <message name="ESBGetCustomerRequest_request">
        <part name="ESBGetCustomerRequest" element="inp1:ESBGetCustomerRequest"/>
    </message>
    <portType name="execute_ppt">
        <operation name="execute">
            <input message="tns:ESBGetCustomerRequest_request"/>
        </operation>
    </portType>
</definitions>
