<definitions
     name="ETH_PUTFTP_LIEBERT_POAcknowledgement"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ETH_PUTFTP_LIEBERT_POAcknowledgement/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ETH_PUTFTP_LIEBERT_POAcknowledgement/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:imp1="NS_31CA8D0F33324F95A0BF15D85539C27E20081212182610"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterOutboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="NS_31CA8D0F33324F95A0BF15D85539C27E20081212182610" schemaLocation="public_html/BODs/Standalone/EMR856V10.xsd" />
      </schema>
    </types>
    <message name="Transaction-856_msg">
        <part name="Transaction-856" element="imp1:Transaction-856"/>
    </message>
    <portType name="Put_ptt">
        <operation name="Put">
            <input message="tns:Transaction-856_msg"/>
        </operation>
    </portType>
    <binding name="Put_binding" type="tns:Put_ptt">
    <jca:binding  />
        <operation name="Put">
      <jca:operation
          FileType="binary"
          PhysicalDirectory="outfile\856"
          InteractionSpec="oracle.tip.adapter.ftp.outbound.FTPInteractionSpec"
          FileNamingConvention="FTP_LIEBERT_POAck%yyMMddHHmmssSS%.xml"
          NumberMessages="1"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="ETH_PUTFTP_LIEBERT_POAcknowledgement">
        <port name="Put_pt" binding="tns:Put_binding">
      <jca:address location="eis/Ftp/ETH_elsha" />
        </port>
    </service>
  <plt:partnerLinkType name="Put_plt" >
    <plt:role name="Put_role" >
      <plt:portType name="tns:Put_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
