<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETH_GETFTP_ELSHA_LiebertFlatFile.wsdl"/>
      <rootElement name="Root-Element" namespace="http://xmlns.emrsn.com/LiebertPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETH_ENQJMS_PO_LiebertFlatFile.wsdl"/>
      <rootElement name="CustomLiebertPO" namespace="http://xmlns.emrsn.com/CustomLiebertPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE MAR 10 12:48:24 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_ENQJMS_PO_LiebertFlatFile/"
                xmlns:imp1="http://xmlns.emrsn.com/LiebertPurchaseOrder"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.emrsn.com/CustomLiebertPurchaseOrder"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ETH_GETFTP_ELSHA_LiebertFlatFile/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
                exclude-result-prefixes="xsl imp1 plt pc ns0 jca tns hdr ns1 ns2 ns3 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns2:CustomLiebertPO>
     <imp1:Root-Element>
           <xsl:copy-of select="/imp1:Root-Element/*"/>
      </imp1:Root-Element>
      <Message_id>
        <xsl:value-of select="string('')"/>
      </Message_id>
     <Message_direction>
        <xsl:value-of select="string('OUT')"/>
      </Message_direction>
      <Sender_Document_number>
        <xsl:value-of select="string('')"/>
      </Sender_Document_number>
      <Sender_Message_type>
        <xsl:value-of select="string('FF')"/>
      </Sender_Message_type>
      <Sender_Message_standard>
        <xsl:value-of select="string('EMR Flat File')"/>
      </Sender_Message_standard>
      <Sender_Transaction_type>
        <xsl:value-of select="string('')"/>
      </Sender_Transaction_type>
      <Sender_Transaction_subtype>
        <xsl:value-of select="string('')"/>
      </Sender_Transaction_subtype>
      <Sender_System_type>
        <xsl:value-of select="string('Non Oracle')"/>
      </Sender_System_type>
      <Sender_Id>
        <xsl:value-of select="normalize-space(/imp1:Root-Element/record/HDGS02)"/>
      </Sender_Id>
      <Sender_Site_Id>
        <xsl:value-of select="string('')"/>
      </Sender_Site_Id>
      <Sender_Name>
        <xsl:value-of select="string('LIEBERTNA')"/>
      </Sender_Name>
      <Sender_Type>
        <xsl:value-of select="string('FTP')"/>
      </Sender_Type>
      <Receiver_System_type>
        <xsl:value-of select="string('')"/>
      </Receiver_System_type>
      <Receiver_Id>
        <xsl:value-of select="string('')"/>
      </Receiver_Id>
      <Receiver_Site_id>
        <xsl:value-of select="string('')"/>
      </Receiver_Site_id>
      <Receiver_Name>
        <xsl:value-of select="string('')"/>
      </Receiver_Name>
      <Receiver_type>
        <xsl:value-of select="string('')"/>
      </Receiver_type>
      <File_name>
        <xsl:value-of select='ehdr:getRequestHeader("/fhdr:InboundFTPHeaderType/fhdr:fileName","fhdr=http://xmlns.oracle.com/pcbpel/adapter/ftp/;")'/>
      </File_name>
      <Record_total>
        <xsl:value-of select="string('')"/>
      </Record_total>
      <Record_number>
        <xsl:value-of select="string('')"/>
      </Record_number>      
      <Flow_id_1>
        <xsl:value-of select="ehdr:getInstanceID()"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="string('')"/>
      </Flow_id_2>
      <Flow_id_3>
        <xsl:value-of select="string('')"/>
      </Flow_id_3>
      <Attribute1>
        <xsl:value-of select="string('')"/>
      </Attribute1>
      <Attribute2>
        <xsl:value-of select="string('')"/>
      </Attribute2>
      <Attribute3>
        <xsl:value-of select="string('')"/>
      </Attribute3>
      <Attribute4>
        <xsl:value-of select="string('')"/>
      </Attribute4>
      <Attribute5>
        <xsl:value-of select="string('')"/>
      </Attribute5>
    </ns2:CustomLiebertPO>
  </xsl:template>
</xsl:stylesheet>
