package com.emerson.eth.scheduler.proxy;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://usmtnz-dinfap19.dev.emrsn.org:8120/soa-infra/services/ETH_Temp/BPEL_HelloWorld/bpel_helloworld_ep_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Dhami_SOA/BPEL_HelloWorld/BPEL_HelloWorld",
  name="bpel_helloworld_ep_ep")
public class Bpel_helloworld_ep_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.emerson.eth.scheduler.proxy.Bpel_helloworld_ep_ep");
      URL baseUrl = Bpel_helloworld_ep_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Bpel_helloworld_ep_ep.class.getResource("http://usmtnz-dinfap19.dev.emrsn.org:8120/soa-infra/services/ETH_Temp/BPEL_HelloWorld/bpel_helloworld_ep_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://usmtnz-dinfap19.dev.emrsn.org:8120/soa-infra/services/ETH_Temp/BPEL_HelloWorld/bpel_helloworld_ep_ep?WSDL");
        }
      }
      else
      {
        if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
        wsdlLocationURL =
            new URL(baseUrl, "http://usmtnz-dinfap19.dev.emrsn.org:8120/soa-infra/services/ETH_Temp/BPEL_HelloWorld/bpel_helloworld_ep_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://usmtnz-dinfap19.dev.emrsn.org:8120/soa-infra/services/ETH_Temp/BPEL_HelloWorld/bpel_helloworld_ep_ep?WSDL",
          e);
    }
  }

  public Bpel_helloworld_ep_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/Dhami_SOA/BPEL_HelloWorld/BPEL_HelloWorld",
                    "bpel_helloworld_ep_ep"));
  }

  public Bpel_helloworld_ep_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="BPEL_HelloWorld_pt")
  public com.emerson.eth.scheduler.proxy.BPEL_HelloWorld getBPEL_HelloWorld_pt()
  {
    return (com.emerson.eth.scheduler.proxy.BPEL_HelloWorld) super.getPort(new QName("http://xmlns.oracle.com/Dhami_SOA/BPEL_HelloWorld/BPEL_HelloWorld",
                                                                                     "BPEL_HelloWorld_pt"),
                                                                           com.emerson.eth.scheduler.proxy.BPEL_HelloWorld.class);
  }

  @WebEndpoint(name="BPEL_HelloWorld_pt")
  public com.emerson.eth.scheduler.proxy.BPEL_HelloWorld getBPEL_HelloWorld_pt(WebServiceFeature... features)
  {
    return (com.emerson.eth.scheduler.proxy.BPEL_HelloWorld) super.getPort(new QName("http://xmlns.oracle.com/Dhami_SOA/BPEL_HelloWorld/BPEL_HelloWorld",
                                                                                     "BPEL_HelloWorld_pt"),
                                                                           com.emerson.eth.scheduler.proxy.BPEL_HelloWorld.class,
                                                                           features);
  }
}
