<wsdl:definitions
     name="ETH_FL_RD_PO_EBM"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Sarah_Mappings/ETH_Sarah_ConnectorService/ETH_FL_RD_PO_EBM"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Sarah_Mappings/ETH_Sarah_ConnectorService/ETH_FL_RD_PO_EBM"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.oracle.com/EnterpriseObjects/Manufacturing/EBO/PurchaseOrder/Emerson"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Read_PO_plt" >
    <plt:role name="Read_PO_role" >
      <plt:portType name="tns:Read_PO_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/EnterpriseObjects/Manufacturing/EBO/PurchaseOrder/Emerson" schemaLocation="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Manufacturing/EBO/PurchaseOrder/Emerson/PurchaseOrderEBM.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Read_PO_msg">
        <wsdl:part name="body" element="imp1:CreatePurchaseOrderEBM"/>
    </wsdl:message>
    <wsdl:portType name="Read_PO_ptt">
        <wsdl:operation name="Read_PO">
            <wsdl:input message="tns:Read_PO_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
