<wsdl:definitions
     name="ETH_FL_WR_PO_EDI"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Sarah_Mappings/ETH_Sarah_ConnectorService/ETH_FL_WR_PO_EDI"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Sarah_Mappings/ETH_Sarah_ConnectorService/ETH_FL_WR_PO_EDI"
     xmlns:imp1="http://schema.emerson.com/ETH/EDI/850/V5020"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="WritePOEDI_plt" >
    <plt:role name="WritePOEDI_role" >
      <plt:portType name="tns:WritePOEDI_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Sarah_Mappings/ETH_Sarah_ConnectorService/ETH_FL_WR_PO_EDI"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://schema.emerson.com/ETH/EDI/850/V5020" schemaLocation="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/ETH/EDI/V5020/V51/EDI_EMR850.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="WritePOEDI_msg">
        <wsdl:part name="body" element="imp1:Transaction-850"/>
    </wsdl:message>
    <wsdl:portType name="WritePOEDI_ptt">
        <wsdl:operation name="WritePOEDI">
            <wsdl:input message="tns:WritePOEDI_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
