<?binding.jca ETH_DB_CALL_INSMasterRecord_db.jca?>
<wsdl:definitions name="ETH_DB_CALL_INSMasterRecord" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Dhami-SOA/ETH_GLB_LSNA_PO_ConnectorService/ETH_DB_CALL_INSMasterRecord" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_DB3/ETH_INSERTMASTERRECORD_PD/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Dhami-SOA/ETH_GLB_LSNA_PO_ConnectorService/ETH_DB_CALL_INSMasterRecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ETH_DB_CALL_INSMasterRecord_plt">
        <plt:role name="ETH_DB_CALL_INSMasterRecord_role">
            <plt:portType name="tns:ETH_DB_CALL_INSMasterRecord_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_DB3/ETH_INSERTMASTERRECORD_PD/" schemaLocation="xsd/ETH_DB3_ETH_INSERTMASTERRECORD_PD.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="ETH_DB_CALL_INSMasterRecord_ptt">
        <wsdl:operation name="ETH_DB_CALL_INSMasterRecord">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
