<wsdl:definitions
     name="JMS_Dequeue"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/SOAApp/Message_Dequeue/JMS_Dequeue"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOAApp/Message_Dequeue/JMS_Dequeue"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://schema.emerson.com/SOAApp/Message"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Consume_Message_plt" >
    <plt:role name="Consume_Message_role" >
      <plt:portType name="tns:Consume_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://schema.emerson.com/SOAApp/Message" schemaLocation="xsd/Message.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Consume_Message_msg">
        <wsdl:part name="body" element="imp1:process"/>
    </wsdl:message>
    <wsdl:portType name="Consume_Message_ptt">
        <wsdl:operation name="Consume_Message">
            <wsdl:input message="tns:Consume_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
