<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Test_Temp_Call_Mediator"
     targetNamespace="http://xmlns.oracle.com/SOAApp/Test_Temp_Call/Test_Temp_Call_Mediator"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://xmlns.oracle.com/singleString"
     xmlns:tns="http://xmlns.oracle.com/SOAApp/Test_Temp_Call/Test_Temp_Call_Mediator"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/singleString" schemaLocation="xsd/singleString.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:singleString"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
