<definitions
     name="VDSTIDMWebService"
     targetNamespace="http://service.emerson.com/vdst/tool/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://service.emerson.com/vdst/tool/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <import namespace="http://service.emerson.com/vdst/tool/" location="http://10.236.94.105:8080/VDSTIDM/IDMWebService?wsdl"/>
    <plnk:partnerLinkType name="IDMWebService_PL">
        <plnk:role name="IDMWebService_Role">
            <plnk:portType name="tns:IDMWebService"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
