<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="CEH_FL_GET_FetchProductData.wsdl"/>
      <rootElement name="product" namespace="http://schemas.emerson.com/product"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://INEDEC-MOH-03:8888/orabpel/default/CEH_BPEL_ReceiveData/1.0/CEH_BPEL_ReceiveData?wsdl"/>
      <rootElement name="envelope" namespace="http://schemas.emerson.com/common/envelope"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI FEB 27 14:36:28 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:emr="http://schemas.emerson.com/common/envelope"
                exclude-result-prefixes="xsl xref xp20 bpws ora ehdr orcl ids hwf emr">
  <xsl:template match="/">
    <xsl:variable name="guid" select="orcl:generate-guid()" />
  <xsl:variable name="instanceid" select="ehdr:getInstanceID()" />
    <emr:envelope>
  <emr:header>
    <emr:flowID><xsl:value-of select="$guid"/></emr:flowID>
    <emr:transactionID><xsl:value-of select="$guid"/></emr:transactionID>
    <emr:originalSource>ProductApp</emr:originalSource>
    <emr:routingInfo>
      <emr:process emr:processID="{$instanceid}">CEH_ESB_FetchProductData</emr:process>
    </emr:routingInfo>
    <emr:destination>CEH_BPEL_Receivedata</emr:destination>
    <emr:userID>Unknown</emr:userID>
    <emr:headerProperties/>
  </emr:header>
  <emr:body>
    <emr:xmlPayload>
      <xsl:copy-of select="."/>
    </emr:xmlPayload>
  </emr:body>
</emr:envelope>
  </xsl:template>
</xsl:stylesheet>
