<?binding.jca ETH_FL_WR_LSNAArchive_file.jca?>
<wsdl:definitions name="ETH_FL_WR_LSNAArchive" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Dhami-SOA/ETH_GLB_LSNA_PO_ConnectorService1/ETH_FL_WR_LSNAArchive" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Dhami-SOA/ETH_GLB_LSNA_PO_ConnectorService1/ETH_FL_WR_LSNAArchive" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="WriteLSNAArchive_plt">
        <plt:role name="WriteLSNAArchive_role">
            <plt:portType name="tns:WriteLSNAArchive_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="opaqueElement" type="base64Binary"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="WriteLSNAArchive_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="WriteLSNAArchive_ptt">
        <wsdl:operation name="WriteLSNAArchive">
            <wsdl:input message="tns:WriteLSNAArchive_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
