// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.tempproxy.proxy.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class FindUserResponseType_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_UserType_QNAME = new QName("", "UserType");
    private static final QName ns3_UserType_TYPE_QNAME = new QName("http://service.emerson.com/vdst/tool/", "UserType");
    private CombinedSerializer myns3_UserType__UserType_LiteralSerializer;
    
    public FindUserResponseType_LiteralSerializer(QName type) {
        this(type,  false);
    }
    
    public FindUserResponseType_LiteralSerializer(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns3_UserType__UserType_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.tempproxy.proxy.UserType.class, ns3_UserType_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        com.tempproxy.proxy.FindUserResponseType instance = new com.tempproxy.proxy.FindUserResponseType();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("UserType");
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_UserType_QNAME))) {
            myns3_UserType__UserType_LiteralSerializer.setNullable( false );
            member = myns3_UserType__UserType_LiteralSerializer.deserialize(ns1_UserType_QNAME, reader, context);
            requiredElements.remove("UserType");
            if (member == null) {
                throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
            }
            instance.setUserType((com.tempproxy.proxy.UserType)member);
            context.setXmlFragmentWrapperName( null );
            reader.nextElementContent();
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.tempproxy.proxy.FindUserResponseType instance = (com.tempproxy.proxy.FindUserResponseType)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.tempproxy.proxy.FindUserResponseType instance = (com.tempproxy.proxy.FindUserResponseType)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.tempproxy.proxy.FindUserResponseType instance = (com.tempproxy.proxy.FindUserResponseType)obj;
        
        myns3_UserType__UserType_LiteralSerializer.setNullable( false );
        myns3_UserType__UserType_LiteralSerializer.serialize(instance.getUserType(), ns1_UserType_QNAME, null, writer, context);
    }
}
