// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.tempproxy.proxy.runtime;


import com.tempproxy.proxy.UserRoleIDType;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import javax.xml.namespace.QName;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;

public class UserRoleIDType_Encoder extends SimpleTypeEncoderBase {
    
    private static final SimpleTypeEncoder encoder = XSDIntEncoder.getInstance();
    private static final UserRoleIDType_Encoder instance = new UserRoleIDType_Encoder();
    
    private UserRoleIDType_Encoder() {
    }
    
    public static SimpleTypeEncoder getInstance() {
        return instance;
    }
    
    public String objectToString(Object obj, XMLWriter writer) throws Exception {
        int value = ((UserRoleIDType)obj).getValue();
        return encoder.objectToString(new Integer(value), writer);
    }
    
    public Object stringToObject(String str, XMLReader reader) throws Exception {
        return UserRoleIDType.fromValue(((Integer)encoder.stringToObject(str, reader)).intValue());
    }
    
    
}
