<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Validate"
     targetNamespace="http://services.emerson.com/sca/soapservice/SOAApp/Service_Validate/Validate"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://services.emerson.com/sca/soapservice/SOAApp/Service_Validate/Validate"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ETH_WS_Validate">
        <plnk:role name="execute_ptt">
            <plnk:portType name="tns:execute_ptt"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://services.emerson.com/sca/soapservice/SOAApp/Service_Validate/Validate"
         location="Validate.wsdl"/>
</wsdl:definitions>
