<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Validate"
     targetNamespace="http://services.emerson.com/sca/soapservice/SOAApp/Service_Validate/Validate"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://schema.emerson.com/ETH/Validate"
     xmlns:tns="http://services.emerson.com/sca/soapservice/SOAApp/Service_Validate/Validate"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schema.emerson.com/ETH/Validate" schemaLocation="xsd/validate.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Validate" element="inp1:Validate"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
