<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL"
    targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_INSRTDB_ELSHA_ARCHIVEDETAIL/"
    xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ETH_INSRTDB_ELSHA_ARCHIVEDETAIL/"
    xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
    xmlns:pc="http://xmlns.oracle.com/pcbpel/"
    xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ETHINSRTDBELSHAARCHIVEDETAIL"
    xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ETHINSRTDBELSHAARCHIVEDETAIL"
                schemaLocation="ETHINSRTDBELSHAARCHIVEDETAIL_table.xsd"/>
        </schema>
    </types>

    <message name="EthArchiveDetailTransactionCollection_msg">
        <part name="EthArchiveDetailTransactionCollection" element="top:EthArchiveDetailTransactionCollection"/>
    </message>


    <portType name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_ptt">
        <operation name="insert">
            <input message="tns:EthArchiveDetailTransactionCollection_msg"/>
        </operation>
    </portType>

    <binding name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_binding" type="tns:ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_ptt">
        <jca:binding />
        <operation name="insert">
            <jca:operation
                InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"

                DescriptorName="ETHINSRTDBELSHAARCHIVEDETAIL.EthArchiveDetailTransaction"
                DmlType="insert"
                DetectOmissions="true"
                OptimizeMerge="true"
                MappingsMetaDataURL="ETHINSRTDBELSHAARCHIVEDETAIL_toplink_mappings.xml" />
            <input>
                <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
            </input>
        </operation>
    </binding>

    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/DB/ETH_Business is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL">
        <port name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_pt" binding="tns:ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_binding">
            <jca:address location="eis/DB/ETH_Business"
                UIConnectionName="db_Elshat3_Business"
                ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
                mcf.DriverClassName="oracle.jdbc.OracleDriver"
                mcf.PlatformClassName="oracle.toplink.platform.database.oracle.Oracle10Platform"
                mcf.ConnectionString="jdbc:oracle:thin:@elshat1db.emrsn.com:20003:elshat3"
                mcf.UserName="SC_Report"
                mcf.Password="F44034A2DD8158AE53D924290C873D4A"
            />
        </port>
    </service>

    <plt:partnerLinkType name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_plt" >
        <plt:role name="ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_role" >
            <plt:portType name="tns:ETH_INSRTDB_ELSHA_ARCHIVEDETAIL_ptt" />
        </plt:role>
    </plt:partnerLinkType>

</definitions>
