<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_ProcessPO_RoutingRules_RS.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETH_ENQJMS_ProcessPO_B2B.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE MAR 31 21:22:45 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"
                xmlns:ns6="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns8="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ns5="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns2="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:ns4="http://www.openapplications.org/oagis/9"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/ETH_ENQJMS_ProcessPO_B2B/"
                xmlns:ns7="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns9="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                exclude-result-prefixes="xsl inp1 ns6 ns8 ns5 ns2 ns0 ns3 tns ns4 ns7 ns9 plt jca ns1 hdr bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <inp1:CustomProcessPO>
      <ProcessPO>
        <xsl:attribute name="releaseID">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@releaseID"/>
        </xsl:attribute>
        <xsl:attribute name="versionID">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@versionID"/>
        </xsl:attribute>
        <xsl:attribute name="systemEnvironmentCode">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@systemEnvironmentCode"/>
        </xsl:attribute>
        <xsl:attribute name="languageCode">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@languageCode"/>
        </xsl:attribute>
        <xsl:copy-of select="/inp1:CustomProcessPO/ProcessPO/*"/>
      </ProcessPO>
      <Message_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_id"/>
      </Message_id>
      <Message_direction>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_direction"/>
      </Message_direction>
      <Sender_Document_number>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Document_number"/>
      </Sender_Document_number>
      <Sender_Message_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Message_type"/>
      </Sender_Message_type>
      <Sender_Message_standard>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Message_standard"/>
      </Sender_Message_standard>
      <Sender_Transaction_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Transaction_type"/>
      </Sender_Transaction_type>
      <Sender_Transaction_subtype>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Transaction_subtype"/>
      </Sender_Transaction_subtype>
      <Sender_System_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_System_type"/>
      </Sender_System_type>
      <Sender_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Id"/>
      </Sender_Id>
      <Sender_Site_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Site_Id"/>
      </Sender_Site_Id>
      <Sender_Name>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Name"/>
      </Sender_Name>
      <Sender_Type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Type"/>
      </Sender_Type>
      <Receiver_System_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_System_type"/>
      </Receiver_System_type>
      <Receiver_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Id"/>
      </Receiver_Id>
      <Receiver_Site_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Site_id"/>
      </Receiver_Site_id>
      <Receiver_Name>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Name"/>
      </Receiver_Name>
      <Receiver_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_type"/>
      </Receiver_type>
      <File_name>
        <xsl:value-of select="/inp1:CustomProcessPO/File_name"/>
      </File_name>
      <Record_total>
        <xsl:value-of select="/inp1:CustomProcessPO/Record_total"/>
      </Record_total>
      <Record_number>
        <xsl:value-of select="/inp1:CustomProcessPO/Record_number"/>
      </Record_number>
      <Flow_id_1>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_1"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_2"/>
      </Flow_id_2>
      <Flow_id_3>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_3"/>
      </Flow_id_3>
      <Send_on_fail>
        <xsl:value-of select="/inp1:CustomProcessPO/Send_on_fail"/>
      </Send_on_fail>
      <Division_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_name"/>
      </Division_name>
      <Division_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_format"/>
      </Division_format>
      <Trading_partner_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_name"/>
      </Trading_partner_1_name>
      <Trading_partner_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_format"/>
      </Trading_partner_1_format>
      <Trading_partner_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_from"/>
      </Trading_partner_1_date_from>
      <Trading_partner_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_to"/>
      </Trading_partner_1_date_to>
      <Trading_partner_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_name"/>
      </Trading_partner_2_name>
      <Trading_partner_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_format"/>
      </Trading_partner_2_format>
      <Trading_partner_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_from"/>
      </Trading_partner_2_date_from>
      <Trading_partner_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_to"/>
      </Trading_partner_2_date_to>
      <Trading_partner_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_name"/>
      </Trading_partner_3_name>
      <Trading_partner_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_format"/>
      </Trading_partner_3_format>
      <Trading_partner_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_from"/>
      </Trading_partner_3_date_from>
      <Trading_partner_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_to"/>
      </Trading_partner_3_date_to>
      <Logistics_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_name"/>
      </Logistics_1_name>
      <Logistics_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_format"/>
      </Logistics_1_format>
      <Logistics_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_from"/>
      </Logistics_1_date_from>
      <Logistics_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_to"/>
      </Logistics_1_date_to>
      <Logistics_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_name"/>
      </Logistics_2_name>
      <Logistics_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_format"/>
      </Logistics_2_format>
      <Logistics_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_from"/>
      </Logistics_2_date_from>
      <Logistics_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_to"/>
      </Logistics_2_date_to>
      <Logistics_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_name"/>
      </Logistics_3_name>
      <Logistics_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_format"/>
      </Logistics_3_format>
      <Logistics_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_from"/>
      </Logistics_3_date_from>
      <Logistics_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_to"/>
      </Logistics_3_date_to>
      <Compliance_result>
        <xsl:value-of select="/inp1:CustomProcessPO/Compliance_result"/>
      </Compliance_result>
      <Attribute1>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute1"/>
      </Attribute1>
      <Attribute2>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute2"/>
      </Attribute2>
      <Attribute3>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute3"/>
      </Attribute3>
      <Attribute4>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute4"/>
      </Attribute4>
      <Attribute5>
        <xsl:value-of select="string('TP1')"/>        
      </Attribute5>
      <Attribute6>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute6"/>
      </Attribute6>
      <Attribute7>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute7"/>
      </Attribute7>
      <Attribute8>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute8"/>
      </Attribute8>
      <Attribute9>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute9"/>
      </Attribute9>
      <Attribute10>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute10"/>
      </Attribute10>
    </inp1:CustomProcessPO>
  </xsl:template>
</xsl:stylesheet>
