<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_Transform_CustomOAGIS_9_0_RS.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder_ETH_ProcessPO_SequencingChecker_RS.wsdl"/>
      <rootElement name="CustomProcessPO" namespace="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [MON MAR 30 18:43:44 IST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:inp1="http://xmlns.emrsn.com/CustomProcessPurchaseOrder"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns6="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns8="http://www.openapplications.org/oagis/9/currencycode/54217:2001"
                xmlns:ns5="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1"
                xmlns:ns2="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://www.openapplications.org/oagis/9/codelists"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns1="http://oracle.com/esb/namespaces/DefaultSystem"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_ProcessPurchaseOrder"
                xmlns:ns4="http://www.openapplications.org/oagis/9"
                xmlns:ns7="http://www.openapplications.org/oagis/9/unitcode/66411:2001"
                xmlns:ns9="http://www.openapplications.org/oagis/9/languagecode/5639:1988"
                exclude-result-prefixes="xsl inp1 ns6 ns8 ns5 ns2 ns0 ns3 tns ns4 ns7 ns9 ns1 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
  <xsl:variable name="apostrophe">'</xsl:variable>
    <inp1:CustomProcessPO>
      <ProcessPO>
        <xsl:attribute name="releaseID">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@releaseID"/>
        </xsl:attribute>
        <xsl:attribute name="versionID">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@versionID"/>
        </xsl:attribute>
        <xsl:attribute name="systemEnvironmentCode">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@systemEnvironmentCode"/>
        </xsl:attribute>
        <xsl:attribute name="languageCode">
          <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/@languageCode"/>
        </xsl:attribute>
        <xsl:copy-of select="/inp1:CustomProcessPO/ProcessPO/*"/>
      </ProcessPO>
      <Message_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_id"/>
      </Message_id>
      <Message_direction>
        <xsl:value-of select="/inp1:CustomProcessPO/Message_direction"/>
      </Message_direction>
      <Sender_Document_number>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Document_number"/>
      </Sender_Document_number>
      <Sender_Message_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Message_type"/>
      </Sender_Message_type>
      <Sender_Message_standard>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Message_standard"/>
      </Sender_Message_standard>
      <Sender_Transaction_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Transaction_type"/>
      </Sender_Transaction_type>
      <Sender_Transaction_subtype>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Transaction_subtype"/>
      </Sender_Transaction_subtype>
      <Sender_System_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_System_type"/>
      </Sender_System_type>
      <Sender_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Id"/>
      </Sender_Id>
      <Sender_Site_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Site_Id"/>
      </Sender_Site_Id>
      <Sender_Name>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Name"/>
      </Sender_Name>
      <Sender_Type>
        <xsl:value-of select="/inp1:CustomProcessPO/Sender_Type"/>
      </Sender_Type>
      <Receiver_System_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_System_type"/>
      </Receiver_System_type>
      <Receiver_Id>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Id"/>
      </Receiver_Id>
      <Receiver_Site_id>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Site_id"/>
      </Receiver_Site_id>
      <Receiver_Name>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_Name"/>
      </Receiver_Name>
      <Receiver_type>
        <xsl:value-of select="/inp1:CustomProcessPO/Receiver_type"/>
      </Receiver_type>
      <File_name>
        <xsl:value-of select="/inp1:CustomProcessPO/File_name"/>
      </File_name>
      <Record_total>
        <xsl:value-of select="/inp1:CustomProcessPO/Record_total"/>
      </Record_total>
      <Record_number>
        <xsl:value-of select="/inp1:CustomProcessPO/Record_number"/>
      </Record_number>
      <Flow_id_1>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_1"/>
      </Flow_id_1>
      <Flow_id_2>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_2"/>
      </Flow_id_2>
      <Flow_id_3>
        <xsl:value-of select="/inp1:CustomProcessPO/Flow_id_3"/>
      </Flow_id_3>
      <Send_on_fail>
        <xsl:value-of select="/inp1:CustomProcessPO/Send_on_fail"/>
      </Send_on_fail>
      <Division_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_name"/>
      </Division_name>
      <Division_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Division_format"/>
      </Division_format>
      <Trading_partner_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_name"/>
      </Trading_partner_1_name>
      <Trading_partner_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_format"/>
      </Trading_partner_1_format>
      <Trading_partner_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_from"/>
      </Trading_partner_1_date_from>
      <Trading_partner_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_1_date_to"/>
      </Trading_partner_1_date_to>
      <Trading_partner_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_name"/>
      </Trading_partner_2_name>
      <Trading_partner_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_format"/>
      </Trading_partner_2_format>
      <Trading_partner_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_from"/>
      </Trading_partner_2_date_from>
      <Trading_partner_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_2_date_to"/>
      </Trading_partner_2_date_to>
      <Trading_partner_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_name"/>
      </Trading_partner_3_name>
      <Trading_partner_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_format"/>
      </Trading_partner_3_format>
      <Trading_partner_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_from"/>
      </Trading_partner_3_date_from>
      <Trading_partner_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Trading_partner_3_date_to"/>
      </Trading_partner_3_date_to>
      <Logistics_1_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_name"/>
      </Logistics_1_name>
      <Logistics_1_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_format"/>
      </Logistics_1_format>
      <Logistics_1_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_from"/>
      </Logistics_1_date_from>
      <Logistics_1_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_1_date_to"/>
      </Logistics_1_date_to>
      <Logistics_2_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_name"/>
      </Logistics_2_name>
      <Logistics_2_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_format"/>
      </Logistics_2_format>
      <Logistics_2_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_from"/>
      </Logistics_2_date_from>
      <Logistics_2_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_2_date_to"/>
      </Logistics_2_date_to>
      <Logistics_3_name>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_name"/>
      </Logistics_3_name>
      <Logistics_3_format>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_format"/>
      </Logistics_3_format>
      <Logistics_3_date_from>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_from"/>
      </Logistics_3_date_from>
      <Logistics_3_date_to>
        <xsl:value-of select="/inp1:CustomProcessPO/Logistics_3_date_to"/>
      </Logistics_3_date_to>
      <Compliance_result>
        <xsl:value-of select="/inp1:CustomProcessPO/Compliance_result"/>
      </Compliance_result>
      <Attribute1>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute1"/>
      </Attribute1>
      <xsl:variable name="Receiver_Id_Var">      
        <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:SupplierParty/ns4:PartyIDs/ns4:ID"/>        
      </xsl:variable>
      <xsl:variable name="Receiver_Site_id_Var">
        <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:SupplierParty/ns4:Location/ns4:ID"/>
      </xsl:variable>
      <xsl:variable name="Attribute1_Var">
          <xsl:choose>
            <xsl:when test="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderLine/ns4:PurchaseOrderSchedule/ns4:UserArea/ns4:ShipToParty/ns4:Location/ns4:ID =''">        
                <xsl:value-of select="string('NA')"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderLine/ns4:PurchaseOrderSchedule/ns4:UserArea/ns4:ShipToParty/ns4:Location/ns4:ID"/>
            </xsl:otherwise>
        </xsl:choose>
      </xsl:variable>
      <xsl:variable name="Send_On_Duplicate_Var">
          <xsl:choose>
              <xsl:when test='(orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,$Receiver_Site_id_Var,$Attribute1_Var,/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR") != "ROUTING_ERROR")'>
                    <xsl:value-of select='orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,$Receiver_Site_id_Var,$Attribute1_Var,/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR")'/>
              </xsl:when>
              <xsl:when test='(orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,$Receiver_Site_id_Var,"NA",/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR") != "ROUTING_ERROR")'>
                    <xsl:value-of select='orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,$Receiver_Site_id_Var,"NA",/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR")'/>
              </xsl:when>
              <xsl:when test='(orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,"NA",$Attribute1_Var,/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR") != "ROUTING_ERROR")'>
                    <xsl:value-of select='orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,"NA",$Attribute1_Var,/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR")'/>
              </xsl:when>
              <xsl:otherwise>
                    <xsl:value-of select='orcl:lookup-dvm("Routing_DVM","Routing_ID",concat(/inp1:CustomProcessPO/Sender_Id,$Receiver_Id_Var,"NA","NA",/inp1:CustomProcessPO/Sender_Transaction_subtype),"Send_on_Duplicate","ROUTING_ERROR")'/>
              </xsl:otherwise>
          </xsl:choose>
      </xsl:variable>
      <xsl:variable name="RevisionID">
        <xsl:choose>
          <xsl:when test="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:RevisionID = ''">
            <xsl:value-of select="string('0')"/>
          </xsl:when>
          <xsl:otherwise>
            <xsl:value-of select="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:RevisionID"/>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:variable>      
      <xsl:variable name="XmlDocNumber_var">
        <xsl:choose>
          <xsl:when test="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:VariationID = 'STANDARD'">
            <xsl:value-of select="concat('S',':',/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:ID)"/>
          </xsl:when>
          <xsl:when test="/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:VariationID = 'BLANKET'">
            <xsl:value-of select="concat('B',':',/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:DocumentID/ns4:ID,':',/inp1:CustomProcessPO/ProcessPO/DataArea/ns4:PurchaseOrder/ns4:PurchaseOrderHeader/ns4:ReleaseNumber)"/>
          </xsl:when>
        </xsl:choose>
      </xsl:variable>
      <xsl:variable name="queryString">
        <xsl:value-of select="concat('select ETH_CHECK_TRANS_SEQ_PKG.get_transaction_seq(',$apostrophe,$XmlDocNumber_var,$apostrophe,',',$apostrophe,$RevisionID,$apostrophe,',',$apostrophe,/inp1:CustomProcessPO/Sender_Id,$apostrophe,',',$apostrophe,/inp1:CustomProcessPO/Sender_Transaction_subtype,$apostrophe,') result from dual')"/>
      </xsl:variable>
      <Attribute2>
        <xsl:value-of select="$RevisionID"/>
      </Attribute2>
      <xsl:choose>
        <xsl:when test="($Send_On_Duplicate_Var = 'Y') or ($Send_On_Duplicate_Var = 'ROUTING_ERROR')">
          <Attribute3>
            <xsl:value-of select="string('VALID')"/>
          </Attribute3>
        </xsl:when>
        <xsl:otherwise>
          <Attribute3>
            <xsl:value-of select="orcl:query-database($queryString,false(),false(),'jdbc/ETH_BusinessDB')"/>
          </Attribute3>
        </xsl:otherwise>
      </xsl:choose>
      <Attribute4>
        <xsl:value-of select="$XmlDocNumber_var"/>        
      </Attribute4>
      <Attribute5>      
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute5"/>        
      </Attribute5>
      <Attribute6>        
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute6"/>        
      </Attribute6>
      <Attribute7>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute7"/>                
      </Attribute7>
      <Attribute8>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute8"/>
      </Attribute8>
      <Attribute9>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute9"/>
      </Attribute9>
      <Attribute10>
        <xsl:value-of select="/inp1:CustomProcessPO/Attribute10"/>
      </Attribute10>
    </inp1:CustomProcessPO>
  </xsl:template>
</xsl:stylesheet>
