<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="ETH_ProcessPO_CustomEDI_5020_RemoveNamespace_RS"
     targetNamespace="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_B2BInOut"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://oracle.com/esb/namespaces/ETHSys_IntegrationServices_ETHSysGrp_B2BInOut"
     xmlns:inp1="http://xmlns.emrsn.com/CustomEDI850"
    >
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.emrsn.com/CustomEDI850" schemaLocation="public_html/Custom_EMR850V5020_ETH.xsd" />
      </schema>
    </types>
    <message name="CustomEDI850_request">
        <part name="CustomEDI850" element="inp1:CustomEDI850"/>
    </message>
    <portType name="execute_ppt">
        <operation name="execute">
            <input message="tns:CustomEDI850_request"/>
        </operation>
    </portType>
</definitions>
