<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="urn:crmondemand/ws/ecbs/opportunity/10/2004" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:crmondemand/ws/ecbs/opportunity/10/2004" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <plnk:partnerLinkType name="PL_OpportunityQuery">
      <plnk:role name="Opportunity">
         <plnk:portType name="tns:Opportunity"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="urn:crmondemand/ws/ecbs/opportunity/10/2004" location="Opportunity.wsdl"/>
</wsdl:definitions>
