// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package com.emerson.schemas.common.envelope;


public class SystemType implements java.io.Serializable {
    protected java.lang.String systemID;
    protected java.lang.String location;
    protected java.lang.String _value;
    
    public SystemType() {
    }
    
    public java.lang.String getSystemID() {
        return systemID;
    }
    
    public void setSystemID(java.lang.String systemID) {
        this.systemID = systemID;
    }
    
    public java.lang.String getLocation() {
        return location;
    }
    
    public void setLocation(java.lang.String location) {
        this.location = location;
    }
    
    public java.lang.String get_value() {
        return _value;
    }
    
    public void set_value(java.lang.String _value) {
        this._value = _value;
    }
}
